### ISSUE TITLE
Feature Request: Gesture Navigation

### ISSUE THREAD

**Issue by farisjarrah** [Docile-Alligator/Infinity-For-Reddit#1]
Hello,

Thank you for creating such a great open source Reddit client! This looks amazing! Lazy mode is super awesome as well!

If I may request a feature that Apollo for Reddit(on iOS) and Sync for Reddit(on Android) have, and is a pretty handy part of my Reddit workflow.

It would be very very useful to be able to customize some sort of gesture navigation. For example, I like to hide posts I have seen by swiping the individual post from the front page to hide it. Other apps allow you to customize the gesture navigation for various settings. 

Here is a sampling of possible with gesture navigations on posts on the regular home page feed: Short drag from right, long drag from right, short drag from left, long drag from left(same things for up and down), double tap post, three or four finger dragging, etc.

Here is an example of things that could be possible with the aformentioned gestures: hiding posts, up/down voting, star a post, leave a comment.

There is one major implementation detail that I can think of that would make this difficult: on the home page of Infinity is that in the current implementation, you currently are already using swipe left and swipe right to go from Popular to All.

Thank you once again for making such a great and compelling open source Reddit client. These things were just feature requests/suggestions, if you don't like these idea or they conflict with your vision, feel free to close this issue.

Thanks!

**Comment by Docile-Alligator** [comment]
Hi, thanks for your advice! Actually it is really hard to implement swiping a post to hide because the paging library I use doesn't support adding and removing items manually. So if anything in the lists is changing, the whole list will be invalidated and fetch again.
For other gestures, I will implement them but for now, I have to focus on fixing bugs.
