### ISSUE TITLE
[Feature request] Only thing keeping me on RIF is fun: zooming on videos/gifs

### ISSUE THREAD

**Issue by ivnvitx** [Docile-Alligator/Infinity-For-Reddit#100]
I know it may sound useless, but once you are able to do it, it's like you cannot go back.

RIF is fun, the Android app, does this, and it is really really cool when you want to check a specific part of a video, which happens quite a lot with horizontal videos on vertical screens and the reverse.

Also, it is not something that disrupts user experience, only *enhace* it for those who may find it useful.

**Comment by mortezadadgar** [comment]
> ok. i will try.

Any update?

**Comment by Wladefant** [comment]
> > ok. i will try.
> 
> Any update?

Yes, this feature is experimentally implemented for videos in settings>gestures & Buttons>Pinch to Zoom Video
