### ISSUE TITLE
Infinity can't display several levels of sup

### ISSUE THREAD

**Issue by Porkepix** [Docile-Alligator/Infinity-For-Reddit#101]
That's pretty corner case and nitpick, and maybe not even possible withing Android's Java, but I could notice on a post that several levels of HTML's `<sup>` where flattened to a single one. See screenshots below to make it explicit.

![Screenshot_20200515-122354](https://user-images.githubusercontent.com/709500/82041117-f1e14a80-96a7-11ea-92ef-78d0984ca804.png)
![reddit_sup](https://user-images.githubusercontent.com/709500/82041126-fad21c00-96a7-11ea-9f72-c2361a73e129.PNG)

**Comment by Docile-Alligator** [comment]
The markdown library I use has different rules than Reddit's. So I have to use some regex to make it work. Superscript is the hardest part and I haven't totally done it right yet.

**Comment by Docile-Alligator** [comment]
Fixed in v4.3.0-beta1
