### ISSUE TITLE
Material you theme

### ISSUE THREAD

**Issue by MrVoid23** [Docile-Alligator/Infinity-For-Reddit#1017]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

Version 12.1 Using custom rom(Arrow OS

### Device model

Poco F3

### First occurred

Forever

### Expected behaviour

Change the material you theme everytime the wallpaper is changed.This works fine with other apps i have installed on my device,for example Tachiyomi.

### Current behaviour

Currently using a wallpaper app that changes wallpaper everytime device is turned off(Doodle live wallpapers).Infinity does not change the theme,unless i manually apply it in settings.This also happens when literally changing wallpaper,unless you manually do it, it's going to stay the same as when you first applied it.

**Comment by Wladefant** [comment]
https://www.reddit.com/r/Infinity_For_Reddit/comments/woaizt/material_you_themes_not_changing/

**Comment by goat-oss** [comment]
Same here!

**Comment by Docile-Alligator** [comment]
This is due to a limitation in Infinity's design. And it will probably never be fixed. You have to make sure Infinity is running before changing the wallpaper.
