### ISSUE TITLE
App no longer respects "Separate posts and comments in portrait mode"

### ISSUE THREAD

**Issue by anthonyma94** [Docile-Alligator/Infinity-For-Reddit#1018]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

One UI 4.1 (Android 12)

### Device model

Samsung Galaxy Z Fold 3

### First occurred

about 2 months ago

### Steps to reproduce

1. Toggle "Separate posts and comments in portrait mode" on.
2. Open a post.

### Expected behaviour

Comments and post details should be separated into 2 columns.

### Current behaviour

Post details are on top, followed by comments on the bottom all in 1 column.

I first posted the issue on [Reddit](https://www.reddit.com/r/Infinity_For_Reddit/comments/vqkuz0/how_do_i_get_dual_column_mode_in_post_details_on/) in June, officially raising an issue now.

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/4b81d554a8d5e26d5f81cf6a0f400c2176b327da
