### ISSUE TITLE
Preview picture can be completely blury in the home thread

### ISSUE THREAD

**Issue by Porkepix** [Docile-Alligator/Infinity-For-Reddit#102]
See joined screenshots, that's a preview picture from a reddit link pointing to Twitter.

![Screenshot_20200515-124309](https://user-images.githubusercontent.com/709500/82042290-ed1d9600-96a9-11ea-9e36-585bde2ad397.png)
![Screenshot_20200515-124323](https://user-images.githubusercontent.com/709500/82042296-ee4ec300-96a9-11ea-8d7e-a431843a4cf0.png)
![Screenshot_20200515-124326](https://user-images.githubusercontent.com/709500/82042299-eee75980-96a9-11ea-8e74-66b40c0fd335.png)

**Comment by Porkepix** [comment]
Got the same issue with another website's picture right now. Could it be an issue with pictures in Open Graph decoding?

**Comment by Sonoma4K** [comment]
Issue could be related to #107
