### ISSUE TITLE
Bottom Navigation Bar - big empty space on Devices with physical buttons

### ISSUE THREAD

**Issue by tfuerholzer** [Docile-Alligator/Infinity-For-Reddit#1026]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

any

### Device model

Samsung Galaxy S5 -S7, Galaxy Tab S 1 - 3, Galaxy Note 3 - 5, Oneplus 2, 3, Honor 9 , HTC U11, HTC U Ultra , Leeco Le Pro 3 Elite,...

### Steps to reproduce

1. Get any device with physical Home, back and recent Apps Buttons
2. Enable Bottom Navigation.

### Expected behaviour

![Screenshot_20220821-165046](https://user-images.githubusercontent.com/31957099/185797017-84b884d6-3e3f-4aae-a719-38f63b414dd5.png)

Regular sized bottom bar, without any unnecessary white space. Like on phones without physical buttons. (Screenshot taken on Honor 8 Android 7)

### Current behaviour

![Screenshot_20220821-163424](https://user-images.githubusercontent.com/31957099/185797106-2c54b89b-3ea9-44e2-a868-fc91befc9d70.jpg)

Bottom bar but with a large empty white space.
(Screenshot taken on Oneplus 3 Android 9)

**Comment by tfuerholzer** [comment]
![20220821_171222_HDR](https://user-images.githubusercontent.com/31957099/185798032-1f1b7d31-902c-4e61-868a-ee95dfe85b77.jpg)

Honor 9 (left) and Huawei P10 (right) 
Bottom bar has is on the same exact height, despite the P10 needing to display the software navigation keys. The space on the Honor 9 is just white.

Both phones have identical screensize, dpi, Android 9 software.

**Comment by Docile-Alligator** [comment]
Could you try enabling Ignore Navigation Bar in Immersive Interface in Settings->Interface->Immersive Interface?

**Comment by tfuerholzer** [comment]
That seems to fix it, thanks.
