### ISSUE TITLE
Rules won't load in private subreddits

### ISSUE THREAD

**Issue by RSBat** [Docile-Alligator/Infinity-For-Reddit#1028]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

12

### Steps to reproduce

1. Be a member of a private subreddit (you can create one for yourself)
2. Go to that subreddit -> create post -> rules

### Expected behaviour

Rules load

### Current behaviour

Rules don't load, error message is shown:

> Error loading rules
> Tap to retry

Switching subreddit visibility to restricted or public fixes this

**Comment by Docile-Alligator** [comment]
Thanks for reporting it.

**Comment by Abi0711** [comment]
Can I please create a pull request for this issue?

**Comment by Docile-Alligator** [comment]
@Abi0711 Yes please. Thank you!
