### ISSUE TITLE
Not all subreddits are offered as a choice for search feature

### ISSUE THREAD

**Issue by Porkepix** [Docile-Alligator/Infinity-For-Reddit#104]
When user want to do a search, by default it search through all subreddits. But users can also select their profile, or a specific subreddit. Problem is that here, it only offer one subreddit, the last added one (out of the three I have that are registered).

**Comment by Docile-Alligator** [comment]
You mean some of your subscribed subreddits are not shown? You can click the search icon on the toolbar to search for a subreddit.

**Comment by Porkepix** [comment]
> You mean some of your subscribed subreddits are not shown?

Yes.

> You can click the search icon on the toolbar to search for a subreddit.

But that means searching through all existing subreddits.
Why the list before the search can't contain any of the subreddit user have subscribed to, and only show the last one, then?

**Comment by Docile-Alligator** [comment]
It shouldn't behave like this. It should show all your subscribed subreddits. Did you subscribed subreddits using this app or other apps?

**Comment by Porkepix** [comment]
I think I subscribed all of them (only three) from the website directly, if I remember correctly.

**Comment by Docile-Alligator** [comment]
Then you have to go to the subscription page in this app to let it refresh your subscriptions.

**Comment by Porkepix** [comment]
Yes, but the subscription page doesn't offer to search through those sub-reddits.

**Comment by Docile-Alligator** [comment]
Oh. Ok. I may misunderstand your meaning. So do you mean not all your subscriptions are shown when selecting subreddits before searching, even though you have refreshed your subscriptions in this app?

**Comment by Porkepix** [comment]
Yes. Only the last one I followed appears there.
