### ISSUE TITLE
Imgur links with an /a/ doesn't seem to open

### ISSUE THREAD

**Issue by Wladefant** [Docile-Alligator/Infinity-For-Reddit#1049]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.0

### Where did you get the app from

Other

### Android version

Android 12 Noble Rom 

### Device model

Galaxy Note 9

### Steps to reproduce

1. Open an imgur link with an /a/ for example: https://imgur.com/a/hPVoNhd

### Expected behaviour

The imgur link should show the same as the link without the /a/ for example; https://imgur.com/hPVoNhd.jpg

### Current behaviour

For https://imgur.com/a/hPVoNhd "Cannot load image"

**Comment by AndreiShpakovskiy** [comment]
@Wladefant, can you share any post link to reproduce the issue?

**Comment by Wladefant** [comment]
@AndreiShpakovskiy hey, strangely it does work now

**Comment by rharish101** [comment]
It doesn't work for me. I'm on v5.3.3 from F-Droid. Here's an example post: https://www.reddit.com/r/Guitar/comments/xllxcp/gear_picked_up_my_first_gretsch_a_couple_weeks_ago/.

**Comment by Wladefant** [comment]
@rharish101 probably is just not there anymore

**Comment by rharish101** [comment]
It is there when I open the link in my browser.

**Comment by Wladefant** [comment]
@rharish101 correct so I wasn't mistaken after all

**Comment by Wladefant** [comment]
@RSBat when opening the /a/ link in the browser you get redirected to imgur.io/a/... (not imgur.com/a/)

**Comment by RSBat** [comment]
I don't understand how to reproduce this - when I open the guitar post in Infinity and click on the link it opens in the app and the image loads fine

**Comment by Wladefant** [comment]
Haha @RSBat it also does for me now

**Comment by rharish101** [comment]
Yup, I can confirm that it works for me now.

**Comment by Re-Tails** [comment]
Having the same issue here as well, none of the imgur /a/ links display in app. They show up as thumbnails though, but opening it in full screen just show "Cannot load images".

**Comment by RSBat** [comment]
Finally managed to debug this, images don't load because imgur responds with "429 Too Many Requests". So I don't think anything can be done on Infinity's side to fix it

**Comment by Wladefant** [comment]
Yeah @RSBat as I wrote above we could try to change the request URL when not getting the correct response
