### ISSUE TITLE
Having two post filters applied to the same feed makes them not behave correctly.

### ISSUE THREAD

**Issue by user-727** [Docile-Alligator/Infinity-For-Reddit#1056]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

F-Droid

### Android version

12

### Device model

Samsung S20 FE 5G

### First occurred

3 days ago

### Steps to reproduce

1. Create a post filter and apply it to a feed.
2. Modify the post filter to exclude GIFs, for example.
4. Restart the app and test that the post filter works correctly by making sure no GIFs are shown in the feed anymore.
5. Make a second post filter, identical to the first one (excluded GIFs), and apply it to the same feed.
6. Scroll down the same feed again, you will now see GIFs appear (infrequently but still definitely present, as opposed to when there was only 1 post filter applied)

### Expected behaviour

The two post filters do not enter in conflict with each other and no GIFs are shown.

### Current behaviour

Some GIFs seem to be shown even though they should be excluded by the two post filters. Note that with only one post filter, everything behaves as expected. The problem only occurs when there are two or more post filters applied to the same feed.

Note that I used GIFs as an example in this issue, but from my testing the same behaviour also occurs with videos or text posts if you exclude those instead.

If you are wondering why I am making a second post filter with the same settings as an existing one, it was to try to find a workaround this other issue: https://github.com/Docile-Alligator/Infinity-For-Reddit/issues/1055 

### Logs

Would love to provide any if you tell me where they are and how to get them!

**Comment by Aidan223** [comment]
Can I make a pull request for this one @Docile-Alligator?

**Comment by Docile-Alligator** [comment]
@Aidan223 Go ahead. Thank you!
