### ISSUE TITLE
RedGifs not working atm.

### ISSUE THREAD

**Issue by kvanbiesen** [Docile-Alligator/Infinity-For-Reddit#1057]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.0

### Where did you get the app from

Google Play

### Android version

Lineage 18.1 / Stock Samsung Rom

### Device model

Mi pad 4 + samsung s20 fe

### First occurred

2 days ago

### Steps to reproduce

1. Go to a NSFW reddit, try to play titties from redgifs
2. No titties, just black screen.
3. Download doesnt work either

### Expected behaviour

Show titties from redgifs

### Current behaviour

Black screen when coming from redgifs; Tried on 2 different devices
Mi pad with LOS 18.1
S20FE with stock rom.

Both 5.3.0 working from play store.

Boost, redreader working as is the website reddit showing the videos/gifs. So not a dns issue.
Plus trired it on a different ISP and not working either.

**Comment by Wladefant** [comment]
Yes, it seems that there are many problems with redgif because of the app change

**Comment by amayra** [comment]
is this happened only in NSFW video like me or all of them

**Comment by AcruxCode** [comment]
RedGifs recently made some changes to their API and now require any application (like Infinity) which interacts with their services to authenticate their API requests.

This means that the maintainers now need to ask for [client credentials](https://github.com/Redgifs/api/wiki/Client-credentials) from RedGifs which they have to distribute with the app.
These credentials can than be used inside the app to generate a temporary [client token](https://github.com/Redgifs/api/wiki/Client-tokens) which is valid for 24 hours and must be send along with every other request to RedGif through the `Authorization` header as a `Bearer` token.

This unfortunately means that I am unable to submit a pull request to fix the issue as the official maintainers must request the client credentials.

**Comment by Wladefant** [comment]
Thank you @AcruxCode , I requested the keys and they should get them soon

**Comment by Wladefant** [comment]
@Docile-Alligator already has the keys and is implementing them right now

**Comment by Wladefant** [comment]
Should be working with a new release
https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/6d224c307d105c9b1d2a46f0f81a11cabc4d32b1

**Comment by MaggiWuerze** [comment]
Any idea when that might be?

**Comment by Wladefant** [comment]
@MaggiWuerze very soon

**Comment by MaggiWuerze** [comment]
Thanks, can't wait for ~~titties~~ the new release :grin:

**Comment by millydev98** [comment]
Still seems to be an issue with downloading clips.

**Comment by Wladefant** [comment]
@millydev98 please open a new issue for that

**Comment by Wladefant** [comment]
@millydev98 should be solved with the newest update (5.3.2)
