### ISSUE TITLE
Gray overlay on images

### ISSUE THREAD

**Issue by yephny** [Docile-Alligator/Infinity-For-Reddit#1060]
With some images, when you open them fullscreen and zoom in enough for it to fill the screen, a rectangular gray overlay appears at the bottom of the screen. This started with version 5.3.0.

**Comment by Wladefant** [comment]
@yephny Please fill out the bug report form correctly

**Comment by yephny** [comment]
@Wladefant I'd love to, but it doesn't appear in this repository. It's something that the owner needs to set up, I'm guessing. There is no bug report form for me.

**Comment by Wladefant** [comment]
@yephny I myself created the form. Please try that in the browser

**Comment by yephny** [comment]
@Wladefant I see, you've set up an issue form, which I think is going to replace issue templates once it's out of Beta. It's not supported by my Github client of choice, so I used my browser to fill out the form as you suggested.

**Comment by Wladefant** [comment]
@yephny correct
