### ISSUE TITLE
Gray overlay on images in Gallery posts

### ISSUE THREAD

**Issue by yephny** [Docile-Alligator/Infinity-For-Reddit#1062]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.0

### Where did you get the app from

F-Droid

### Android version

Android 10, LineageOS

### First occurred

Starting with v.5.3.0.

### Steps to reproduce

1. Open an image in a gallery post.
2. Zoom in enough to make it cover the screen.
3. See the rectangular gray overlay at the bottom of the image.

### Expected behaviour

The gray overlay is for when people put some text decription to the images they upload. I'd expect them to disappear when I tap the screen one time when the image is opened at full resolution. I also wouldn't expect to see them when there is no description for the image.

### Current behaviour

Go to [this post](https://www.reddit.com/r/pics/comments/x4chy9/oc_i_just_adopted_my_first_dog_i_am_so_excited/) and see for yourself.
![no caption](https://user-images.githubusercontent.com/88166326/188272409-4577efec-1e71-436d-aee3-a45e372a4959.png)
![caption](https://user-images.githubusercontent.com/88166326/188272420-cdc2f046-ea52-42c5-9379-c63a4f5d130b.png)

[This post](https://www.reddit.com/r/pics/comments/x4nxur/oc_im_drawing_on_vacation_and_it_has_been_great/) doesn't even have any images with caption, yet you can see the overlay on each image.
![32_](https://user-images.githubusercontent.com/88166326/188272514-ff790e46-6b27-4555-8ff3-bc03c5159951.png)

**Comment by adamantike** [comment]
It seems #1053 would fix this issue when merged.

**Comment by Wladefant** [comment]
@adamantike correct
