### ISSUE TITLE
Image preview is blurred in home tab

### ISSUE THREAD

**Issue by Sonoma4K** [Docile-Alligator/Infinity-For-Reddit#107]
Image preview in home tab is blurred. The same image appears to be clear when viewing it from the subreddit. 

![Screenshot_20200520-193526_Infinity](https://user-images.githubusercontent.com/65654141/82484537-f5266d00-9ad1-11ea-9f95-1107065bf85f.jpg)

**Comment by Sonoma4K** [comment]
Noticed that my issue is related to issue #102

**Comment by Porkepix** [comment]
Yup, those are probably the same issue, I could notice many more situations with the same problem since then.

**Comment by Docile-Alligator** [comment]
Fixed.
