### ISSUE TITLE
reached reddit's end?

### ISSUE THREAD

**Issue by fusionneur** [Docile-Alligator/Infinity-For-Reddit#1073]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.0

### Where did you get the app from

F-Droid

### Android version

11

### Steps to reproduce

1. scrolling like there's no tomorrow
2. reached the end

### Expected behaviour

infinite should not be finite

### Current behaviour

infinity is finite

**Comment by user-727** [comment]
Reddit can only serve 1000 posts in a feed. After that it stops, it's a known limitation and will be present in any client. If you have post filters set up on top of that, it might also prevent a lot of posts from showing in your feed and thus making it seem like you've seen less than 1000 posts before reaching the end of the feed.

**Comment by Wladefant** [comment]
@user-727 correct

**Comment by Wladefant** [comment]
@fusionneur well, for most people it is because they never xome to the end 😅
