### ISSUE TITLE
Scroll position is lost when changing screen orientation

### ISSUE THREAD

**Issue by vi** [Docile-Alligator/Infinity-For-Reddit#1095]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.1

### Where did you get the app from

F-Droid

### Android version

Android 12

### Device model

Pixel 3 XL

### Steps to reproduce

1. Open Inifinity. Screen orientation is portrait.
2. Open some post (e.g. the first one on "Popular" tab).
3. Scroll down. Remember what comment is displayed at the top now.
4. Change screen orientation to landscape.
5. Change screen orientation back to portrait.

### Expected behaviour

Comment that at the top of the viewport before changing screen orientation stays in the viewport (or at least is somewhere nearby). 

### Current behaviour

Scroll position is reset back to very top.

Workaround: Disabling "Separate Post And Comments in Landscape Mode" setting resolves the issue.

**Comment by HuilinChen943** [comment]
Can I please create a pull request for this issue?  @Docile-Alligator

**Comment by Docile-Alligator** [comment]
@HuilinChen943 Yes, please! Thank you.

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/pull/1173
