### ISSUE TITLE
Feature Request : Floating action button to auto-scroll to next comment

### ISSUE THREAD

**Issue by NatoBoram** [Docile-Alligator/Infinity-For-Reddit#11]
When reading a post's comments, sometimes we'll start to read a long comment chain, and it would be prohibitively long to try to minimize everything to get to the next parent comment. Adding a small FAB, like in the official app, would help scroll those long comments faster.

**Comment by Docile-Alligator** [comment]
Hi, that's really a good idea.

**Comment by Docile-Alligator** [comment]
Hi! This feature has already been implemented.
