### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ze0ss** [Docile-Alligator/Infinity-For-Reddit#110]
Sometimes, the comments are hidden/not visible in the comment section, especially when viewing through after clicking one from the "Inbox" tab, and many a times, the one which has been clicked is not visible too.
And "Show all comments" doesn't display every comment, tried reproducing this with the official reddit app from play store, but it cannot be reproduced because it works well and fine.

Android version - 8.1
Infinity version - 3.1.0 (F-droid)

**Comment by Docile-Alligator** [comment]
Do you mean the comments are shown as "Load more comments"?

**Comment by abh-oss01** [comment]
No, that is different and present as expected, but some (a large number of comments) are not visible, I have no idea why, cross checking with the reddit app from play store doesn't display this problem at all, all the comments are visible.

**Comment by Docile-Alligator** [comment]
Oh ok. Could you provide a post link?

**Comment by abh-oss01** [comment]
Uh, maybe, I'll try... nowadays I do not look at comments much, but ok, also, it is quite a long time ago, so .. ok

**Comment by abh-oss01** [comment]
@Docile-Alligator This issue is reproducible with any post, there isn't any specific one which I want to talk about.

**Comment by Docile-Alligator** [comment]
Maybe I misunderstood it. Clicking a comment in Inbox will lead you to the post detail page. It doesn't automatically scroll to the position where the comment is at. So, you need to scroll down to see it.

**Comment by abh-oss01** [comment]
Oh ok, this is intended, or you're going to add that ability? I was going to open an issue for this specifically, as this is also an "issue", but ok, and also since the current issue is actually not about clicking from inbox, but just any normal post, while browsing... any general post.

**Comment by Docile-Alligator** [comment]
I may add an option for this.

**Comment by abh-oss01** [comment]
The issue was about some comments not showing up, maybe I veered off too much from the original issue... lol

1) So like I said, I cannot see some comments below a post, any post, no specifics, randomly, but at the same time, if checked using the website or the Reddit app from play store, all comments are visible, ...

 2) Just a PSA to this, could you add an option in settings to view _deleted_ comments as well? 
Like [this](www.removeddit.com/) site.

**Comment by Docile-Alligator** [comment]
Viewing deleted comments is added.
