### ISSUE TITLE
Tapping once on video to see preview video player redirects to main video player.

### ISSUE THREAD

**Issue by Drangonfly30** [Docile-Alligator/Infinity-For-Reddit#1101]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.2

### Where did you get the app from

Other

### Android version

Android 7

### Device model

Lenovo k6 power

### First occurred

After new 5.3.2 update

### Steps to reproduce

1. Click on the video once
2. It should show video player on home screen
3. It directly opens main video player

### Expected behaviour

While clicking once it should show video player preview

### Current behaviour

It redirects to main video player.

**Comment by Drangonfly30** [comment]
https://www.reddit.com/r/Infinity_For_Reddit/comments/xgb884/this_is_a_bug_in_the_newest_version_532_whenever/

This is the post I made on reddit about this bug. I tried to add video but don't know why it didn't attach. Actually I don't know how to use github and it's my first time I'm raising an issue.

**Comment by Wladefant** [comment]
@Drangonfly30 yes thank you. Github is more important than reddit, but for a bigger audience you can post it to both

**Comment by Wladefant** [comment]
@Drangonfly30 yes thank you. Github is more important than reddit, but for a bigger audience you can post it to both

**Comment by Drangonfly30** [comment]
I cleared cache and even downloaded infinity again from playstore but getting the same output.

**Comment by JasonKraft** [comment]
I am also seeing this on 5.3.2 on my Galaxy S22+ it currently makes it impossible to pause auto played videos and/or mute/unmute.

**Comment by paulpark03** [comment]
> I am also seeing this on 5.3.2 on my Galaxy S22+ it currently makes it impossible to pause auto played videos and/or mute/unmute.

It used to require two taps to open video player. First to bring up embedded player controls and second tap to open video player. Now a single tap always opens video player. It prevents user from accessing embedded video controls (mute/unmute, play/pause, full screen, scroll bar) within the feed.

**Comment by Wladefant** [comment]
It seems to be device specific or settings specific

**Comment by paulpark03** [comment]
FYI. In the meantime, as a workaround, you can turn OFF this feature:

Settings > Video > Video Autoplay > Easier to Watch in Full Screen > OFF

**Comment by Docile-Alligator** [comment]
Just disable Settings > Video > Video Autoplay > Easier to Watch in Full Screen.
