### ISSUE TITLE
Infinity crash on startup after i update to 5.3.2 version

### ISSUE THREAD

**Issue by amayra** [Docile-Alligator/Infinity-For-Reddit#1117]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.2

### Where did you get the app from

Google Play

### Android version

6.0.1

### Device model

galaxy s5 SM-G990H 

### First occurred

when i updated to 5.3.2 version

### Steps to reproduce

1.  install the app and run it 
2.   app crash

### Expected behaviour

to run normally 

### Current behaviour

app crash within the first second or less I can't get to even copy error log 

to make sure this is not my phone problem I tried with two different phones with some version of android and get the same crash 

### Logs

i can't get this because the app crash very quickly but I sent a report one time to the google play report system or something I tried to make it appear again to copy the error log but I can't do it again I only get this screenshot :
https://i.imgur.com/adYyydy.png

**Comment by Wladefant** [comment]
Hey, @Docile-Alligator fixed that with the version 5.3.3. Additionally you can find crash reports directly in the app: settings>advanced>crash reports

**Comment by amayra** [comment]
> Hey, @Docile-Alligator fixed that with the version 5.3.3. Additionally you can find crash reports directly in the app: settings>advanced>crash reports

I couldn't run the app there no way to do anything when the app crash in first s1 it strated
