### ISSUE TITLE
Items with horizontal scrolling in a post can't be scrolled to the left

### ISSUE THREAD

**Issue by Porkepix** [Docile-Alligator/Infinity-For-Reddit#112]
If there's something that can be horizontally scrolled in the post we read, such as a table too large for the screen, user can scroll it to the right to read more.
But if one needs to scroll to the left, it doesn't work as the feature that goes back to the posts list by sliding the post pane to the right gets priority over scrolling post's items.

**Comment by Docile-Alligator** [comment]
You can scroll the table to the right and then immediately scroll it to the left. Just make sure your finger remains on the screen.

**Comment by Porkepix** [comment]
Yeah, but in that case that makes it pretty difficult to know, and result in quite some usability issues.
