### ISSUE TITLE
Inconsistent Download Location

### ISSUE THREAD

**Issue by AndhikaWB** [Docile-Alligator/Infinity-For-Reddit#114]
Downloaded images (and probably videos?) are saved on different locations based on the file format. For example, JPGs are saved on `/sdcard/pictures` but GIFs and WEBPs are saved on `/sdcard/download`.

I hope they can be saved to a fixed path like `/sdcard/download/Infinity`. It's also good if the download path can be changed manually from in-app settings.

**Comment by Docile-Alligator** [comment]
On Android 10 and above, the images, gifs and videos are saved in /sdcard/Pictures while on other versions, they are saved in /sdcard/Pictures/Infinity.

**Comment by AndhikaWB** [comment]
> On Android 10 and above, the images, gifs and videos are saved in /sdcard/Pictures while on other versions, they are saved in /sdcard/Pictures/Infinity.

Is this a limitation or something? I once have a not-so-similar issue with Chromium based browser as well (affecting only Android 10 users). Seems like the storage management 'thing' has changed on Android 10 (and upper).

**Comment by Docile-Alligator** [comment]
Yes. It is a limitation on Android 10 and above. But it seems that apps can request user permission to save files in a directory. I just need to find a way to do this.

**Comment by Docile-Alligator** [comment]
Customize download locations for images, gifs and videos will be available in the next update.
