### ISSUE TITLE
App crashes when trying to play GIFs (or other media).

### ISSUE THREAD

**Issue by perrsona1234** [Docile-Alligator/Infinity-For-Reddit#115]
Hello.

Recently I encountered an issue with the app crashing, when I try to play GIFs or other multimedia files. Also some images are not being loaded (this seems to be fixed, after I cleaned app's data). Downloading images works fine, tho.

My system:
Device: Xiaomi Redmi Note 5 Pro 4/64 (whyred)
ROM: Official AOSP Extended 7.1 (Android 10)
Kernel: 4.4.218-Extended
SELinux: Enforcing
GApps: None
Infinity for Reddit (installed via Aurora Store): 3.1.0

Do You need more info?
Thank You.

**Comment by Docile-Alligator** [comment]
Could you provide the post link for the GIF?

**Comment by perrsona1234** [comment]
Sorry for not replaying for so long. Basically any GIF file was crashing the app. But I installed Your app from external F-Droid repo (https://apt.izzysoft.de/fdroid/repo?fingerprint=3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A) and it works fine, all GIF files are being played without issues.

**Comment by Docile-Alligator** [comment]
That's really weird. I cannot reproduce this. The app from Aurora Store and Izzy repo is the same.

**Comment by PhoenixFlame101** [comment]
Similar issue, app doesn't crash per se, but stops responding once you leave the gif. This doesn't happen if you leave the gif playback quickly enough.

It seems to be particular to gyfcat gifs. redd.it links seem to be working fine. They also take a while to load up for me, even though redd.it links load fine.

Let me now if there is any other info you need, because it happens every single time I open up a gyfcat link.

**Comment by Docile-Alligator** [comment]
Does this still happen in v4.0.1?

**Comment by PhoenixFlame101** [comment]
Unfortunately, yes. The only difference I could notice with the new version is that all videos take a second to start moving from the thumbnail/still that they start of on.

P.S I didn't mention it before, but I've had this happen from redgifs.com gifs as well.

**Comment by Docile-Alligator** [comment]
Which Android version are you using?

**Comment by PhoenixFlame101** [comment]
Sorry for the late reply. I'm using android 10. Something I hadn't noticed when I commented previously was that the app was frozen for 5-10 seconds and then was back to normal after playing something.

**Comment by Docile-Alligator** [comment]
This is a known issue in ExoPlayer, a video playing library. Link here: https://github.com/google/ExoPlayer/issues/4352
