### ISSUE TITLE
Bottom taskbar overlaps FAB in One UI 4.1.1

### ISSUE THREAD

**Issue by sturmen** [Docile-Alligator/Infinity-For-Reddit#1165]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.3

### Where did you get the app from

F-Droid

### Android version

12

### Device model

Samsung Galaxy Z Fold4

### First occurred

today

### Steps to reproduce

Enable bottom bar in OS settings. (Enabled by default)
Unfold the device to full "tablet" size.

### Expected behaviour

Floating action button adjusts its Y position to be above the bottom bar.

### Current behaviour

Bottom bar overlaps floating action button.

![Screenshot_20221015_084922_Infinity](https://user-images.githubusercontent.com/169858/195987315-abba9483-5c0d-4800-a59a-c97b33c5999d.png)

**Comment by Docile-Alligator** [comment]
Is immersive interface enabled?

**Comment by sturmen** [comment]
> Is immersive interface enabled?

Ah, so it was. Disabling that fixed it.
