### ISSUE TITLE
Open with removeddit

### ISSUE THREAD

**Issue by Fatcakes** [Docile-Alligator/Infinity-For-Reddit#1166]
It would be nice if there was an option to direct under the removeddit url so that you can read the removed comments. https://github.com/gurnec/removeddit

**Comment by patrickdemers6** [comment]
The "See Removed Comment" button allows you to see removed comments. To get to it, click the three dots on a comment.

![Screenshot_20221019-001324_Infinity.jpg](https://user-images.githubusercontent.com/12687723/196603075-f7d0658c-514b-47b5-ba2d-e6156767951b.jpg)

**Comment by Wladefant** [comment]
Hello, That is already done, as @patrickdemers6 already states. We are using the pushshift and reveddit service

**Comment by Wladefant** [comment]
Another thing. That is not a bug. So please refrain to post questions or ideas here. Do it rather in discussions
