### ISSUE TITLE
Regex Filter crashes app

### ISSUE THREAD

**Issue by newhinton** [Docile-Alligator/Infinity-For-Reddit#1167]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.5.3

### Where did you get the app from

F-Droid

### Android version

Lineageos 18

### First occurred

1

### Steps to reproduce

Create new filter
Add Regex filter: \*Predictions Tournament\*
Apply filter to subreddit (empty field, for all)
Restart app

### Expected behaviour

The filter beeing applied

### Current behaviour

The app crashes irrecoverably.

# Aditional Notes:
I am a new user, transitioning from slide. The filter function is extremely confusing and hard to set up, I only got it working by trial & error, maybe a guided setup would be better, with examples. Also a wiki entry would help a long way.

**Comment by Docile-Alligator** [comment]
Could not reproduce this. Could you try applying this filter to a specific subreddit and then go to that subreddit and then after it crashes, go to Settings->Advanced->Crash Logs and send a screenshot?

**Comment by scria1000** [comment]
<img height="600" src="https://user-images.githubusercontent.com/91804886/197327900-b1e747fc-513f-4fd8-9190-d616b24306fc.png"/>

`*Predictions Tournament*` is a wildcard pattern rather than a valid Regex pattern. It should probably show a message instead of crashing.

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/785bb205f63fd3b269c2450e4b1f0e8a6a34c075
