### ISSUE TITLE
App crashing while adding account

### ISSUE THREAD

**Issue by krugerheadshot** [Docile-Alligator/Infinity-For-Reddit#117]
Hey devs,

I am a big fan of your Reddit android client. I had no issues in previous versions but now I do have issues on my new phone! The app crashes while trying to add the account. This is literally annoying!

Here are my device details -
Device - Redmi Note 9 Pro
Android Version - Android 10
RAM - 6 GB
ROM - EvolutionX
Kernel - Stock
Rooted - Yes

Error log url - https://del.dog/nucebising

**Comment by Docile-Alligator** [comment]
Thank you! And thank you for your log! It seems that your phone doesn't have WebView installed. Did you recently uninstalled Android System WebView?

**Comment by krugerheadshot** [comment]
Yeah I uninstalled Android System Webview. I am degoogling my devices so I did that. So the problem is because of Android System Webview? Well I just reinstalled Android System Webview and the app works fine. Can you recommend any open source webview app?

**Comment by OHermesJunior** [comment]
There is [Bromite](https://github.com/bromite/bromite/wiki/Installing-SystemWebView).
