### ISSUE TITLE
History does not work

### ISSUE THREAD

**Issue by Matszwe02** [Docile-Alligator/Infinity-For-Reddit#1175]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.3

### Where did you get the app from

Google Play

### Android version

12

### Device model

Samsung S22

### First occurred

a few months ago

### Steps to reproduce

-Set up history in infinity
-Open a few posts
-Check history

### Expected behaviour

post history working

### Current behaviour

History sometimes saves some posts, but majority of them doesn't appear there.

**Comment by Docile-Alligator** [comment]
Fixed.
https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/cf3595f22dd35e0bd15d1344c11408f73f64c144
