### ISSUE TITLE
Crosspost videos not loading

### ISSUE THREAD

**Issue by Matszwe02** [Docile-Alligator/Infinity-For-Reddit#1176]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.3

### Where did you get the app from

Google Play

### Android version

12

### Device model

Samsung S22

### First occurred

a few months ago

### Steps to reproduce

-Open reddit / subreddit where crosspost videos appear
-Try to view video

### Expected behaviour

Video from crosspost loading or redirecting to original post

### Current behaviour

Video not loading, showing an error that it cannot be loaded, no way of getting to the original post where the video was posted

**Comment by Wladefant** [comment]
not able to reproduce it, but shouldnt be an issue
