### ISSUE TITLE
Feature Request: Go to a subreddit directly 

### ISSUE THREAD

**Issue by amanharwara** [Docile-Alligator/Infinity-For-Reddit#118]
It would be great if you could just directly go to a subreddit instead of having to search it first

**Comment by Docile-Alligator** [comment]
That's great.

**Comment by Docile-Alligator** [comment]
4.1.0-beta has this feature.

**Comment by shibotto** [comment]
I'm probably dumb, but how does this work? I'm on 4.1.1 and tapping the plus on search results says "Subscribe Failed", trying to subscribe within a subreddit page says I need to log in (I don't have an account).

**Comment by daraul** [comment]
AFAIK it uses the Reddit api to subscribe, meaning you'll need an account.
Did you want to subscribe without one?

**Comment by amanharwara** [comment]
> I'm probably dumb, but how does this work? I'm on 4.1.1 and tapping the plus on search results says "Subscribe Failed", trying to subscribe within a subreddit page says I need to log in (I don't have an account).

I think this might be the wrong issue for asking this. This issue is just for the feature of directly going to a subreddit, not for subscribing.

**Comment by shibotto** [comment]
Well what I'm looking for is actually some kind of shortcuts for the subreddits I'm interested in without having to manually search for them every time. I said "subscribe" because it's the only vaguely similar concept I found with a button and I thought it worked similar to NewPipe 😅

**Comment by daraul** [comment]
So like a list of favourite subs? Might be easier if you did a new issue
for that.

**Comment by shibotto** [comment]
Spot on! Is there currently no feature like this? Did I misunderstand what this issue was originally about? 🤔

**Comment by daraul** [comment]
I think you did. This was mean to allow the user to tap on a sub's name to
go directly to it (I think). What you're asking for would be considered a
new feature. It'd be best to create a new issue here to discuss it. That
would also make it easier for others that have the same idea to find it and
provide input.

**Comment by shibotto** [comment]
I see, thank you folks for the support! 👌
