### ISSUE TITLE
Fully collapsed comments with hidden votes sometimes display score

### ISSUE THREAD

**Issue by RSBat** [Docile-Alligator/Infinity-For-Reddit#1193]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

current master

### Where did you get the app from

Other

### Android version

12

### Steps to reproduce

1. Collapse some comments with non-hidden score
2. Collapse some comments with hidden score
3. Scroll between them

### Expected behaviour

Probably comments with hidden score should display nothing or "hidden pts."

### Current behaviour

Comments with hidden score display score of other comments

Note: 5.3.3 doesn't have support for hidden score, so it is not noticeable there

**Comment by Wladefant** [comment]
can confirm that, also works the other way around

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/bc03d20845ac18e4aab850ee3ca04ffae65703e0
