### ISSUE TITLE
Feature Request: Resize Cards on home screen

### ISSUE THREAD

**Issue by farisjarrah** [Docile-Alligator/Infinity-For-Reddit#12]
Hello,

I was playing with Lazy Mode(which is so freaking awesome!), and it seems that some picture posts don't fit all the way on the screen. Would be very useful to be able to customize the cards so they can show more or less and have the card fit fully on the screen during lazy mode.

Thanks!

**Comment by Docile-Alligator** [comment]
Thank you for your advice! I will try.
