### ISSUE TITLE
"Continue thread" button can do nothing at the end of comments

### ISSUE THREAD

**Issue by RSBat** [Docile-Alligator/Infinity-For-Reddit#1206]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

Google Play

### Android version

12

### Steps to reproduce

1. Have "Continue thread" as the last comment and some comments that can be collapsed before that
Example:
- Top level 1
-  - comment 1.2
- Top level 2
-  - ....
-  - - continue thread

2. Collapse `Top level 1`
3. Click `continue thread`

### Expected behaviour

Opens thread

### Current behaviour

Nothing happens.

Not always reproducible, works best if all comments fit on screen

**Comment by Wladefant** [comment]
Thanks for your overall motivation, ot would be also really nice if you could share example posts (you probably already create many) because two eyes are good but many are better.

**Comment by RSBat** [comment]
I do have a private subreddit where I test this stuff, but I planned to keep it private. If you want me to link Reddit posts to issues then I can think of something. But I don't really post anything if I don't know the problem already - I find bugs by reading the code, not by using the app

**Comment by Wladefant** [comment]
That makes sense, but you can also be sometimes wrong 🤷‍♂️

**Comment by RSBat** [comment]
@Wladefant maybe you could add a new field to the bug issue template for the post link?

**Comment by Wladefant** [comment]
@RSBat yes that seems reasonable
