### ISSUE TITLE
Some comments don't render properly

### ISSUE THREAD

**Issue by saloniamatteo** [Docile-Alligator/Infinity-For-Reddit#121]
Example: [this comment here](https://www.reddit.com/r/iiiiiiitttttttttttt/comments/h80lod/whats_your_worst_github_code/fuojamm/) doesn't show up properly while using the latest version of Infinity. The original text is:

```
<script>
var id ="<?php echo $id ?>"
</script>
```

although this shows up as a blank comment, like this:

```
‏‏‎ 
```

***

Another example: https://www.reddit.com/r/PerfectPythonLoops/comments/h7vade/rperfectpythonloops_lounge/fuokfn2/

This comment uses the special characters `^(text)` to make the text appear small ʟɪᴋᴇ ᴛʜɪs; it works in the Reddit app but not with Infinity

***

Or this other example: https://www.reddit.com/r/Unexpected/comments/h81hqv/what_a_lovely_young_lady/fuof6da/

The text uses `>!these characters!<` to make the text appear "covered" (generally used for spoilers), but it appears as quoted text.

**Comment by Docile-Alligator** [comment]
The markdown library I use has some limitations and doesn't have the same standard as Reddit. So, I haven't totally made it look right.
