### ISSUE TITLE
Posts in my profile disappear

### ISSUE THREAD

**Issue by eg-mart** [Docile-Alligator/Infinity-For-Reddit#1215]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

12

### Device model

vivo y33s 

### First occurred

about 1 day ago

### Steps to reproduce

1.  Click "Profile" button from the left panel
2. Open "Posts" tab
3. If there are any posts, refresh it a couple of times via dragging and releasing
4. All posts eventually disappear, and the "No posts found" screen is diplayed

### Expected behaviour

I expected to see all of my posts, however, often I see only some of them, and even those disappear after refreshing (top ones, according to the current sorting applied, disappear first)

### Current behaviour

Instead, Infinity shows this:

!["No posts found" screen](https://user-images.githubusercontent.com/60982455/201158711-2a20eee0-2289-4b7f-93ee-25c1b349e971.jpg)

**Comment by eg-mart** [comment]
I think I've just figured it out - I have a "mark read on scroll" and "hide read posts automatically" options enabled, so it was just doing its thing and hiding posts I've already seen. I guess that's not s bug? Still, whenever I click on my or someone else's profile, I expect to see all user's posts regardless of whether I've seen them or not. I see this as logical and I believe this is what official client and reddit's site do too, is there a possibility to change app's behaviour?

**Comment by Wladefant** [comment]
Yes you are correct with your assumption, and I do agree with you that it seems a bit illogical. I think we need to change the hide read posts automatically a little bit

**Comment by Wladefant** [comment]
Here #1007 is already a request for that
