### ISSUE TITLE
App crashes when trying to add account

### ISSUE THREAD

**Issue by cookiei** [Docile-Alligator/Infinity-For-Reddit#122]
Hi,
The app crashes when adding an account, I'm on lineageOs 17.1 without Gapps and no microG. I'm using bromite system webview but tried with android system webview still crashes.

My system:
Device: Xiaomi Pocophone F1 6/128 (Beryllium)
ROM: LineageOs 17.1 (Android 10)
Kernel: 4.9.226-perf-ga6ed0e6
SELinux: Enforcing
Rooted: NO
Webview: Bromite System WebView
GApps: None
Infinity for Reddit (installed via package installer from GitHub):v 3.2.0

**Comment by Docile-Alligator** [comment]
This is weird. I will search it on google.

**Comment by cookiei** [comment]
It was bromite system webview, after reverting back to the stock webview it's working fine, but any fixes for bromite webview?
