### ISSUE TITLE
Redgifs is broken again

### ISSUE THREAD

**Issue by N0-0NE-Dev** [Docile-Alligator/Infinity-For-Reddit#1232]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

Google Play

### Android version

Custom 12L

### Device model

Poco F3

### First occurred

15th Of November

### Steps to reproduce

1. Open the app
2. Try to play a redgifs gif/video

### Example post, link, markdown...

Warnings NSFW:

https://www.reddit.com/r/Whiteworld/comments/yv0cfu/wife_films_me_fuck_a_big_booty_black_girl/

### Expected behaviour

Play the gif/video

### Current behaviour

The "Fetch Redgifs video failed" message appears

**Comment by scria1000** [comment]
Video plays fine for me on 5.3.4, try cleaning app cache. Maybe it is a network issue.

**Comment by N0-0NE-Dev** [comment]
I think it depends on the region? When turning on a VPN the videos play fine, but on the stock reddit app the videos play without a VPN just fine.

**Comment by scria1000** [comment]
That's it! The official app is probably streaming the video from its own media storage (redditmedia.com, v.redd.it) instead of the original redgifs url blocked by your network.

**Comment by N0-0NE-Dev** [comment]
Is there a way for Infinity to do the same?

**Comment by anay-p** [comment]
This issue has been closed as completed but I'm still facing this issue. I'm on version 5.4.0.
