### ISSUE TITLE
no notifications anymore on android 13, it is missing android.permission.POST_NOTIFICATIONS

### ISSUE THREAD

**Issue by o13e** [Docile-Alligator/Infinity-For-Reddit#1237]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

[actual master branch](https://github.com/Docile-Alligator/Infinity-For-Reddit/tree/67b6906ead02ceb7d7e46f28ae5c27a510956038)

### Where did you get the app from
Github

### Android version

13

### Device model

Device with android 13

### First occurred

since upgrade to target sdk 33 i think, https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/071ce78b7cb6e1249e56faaef6f05fa311b83a1c

### Steps to reproduce

Compile it from master branch or download [this action apk ](https://github.com/Docile-Alligator/Infinity-For-Reddit/actions/runs/3460836837)and try to display any kind of notifications or to enable them in android apps settings, on android 13. I believe that the issue is the app now targeting sdk 33 and it is missing [android.permission.POST_NOTIFICATIONS
](https://developer.android.com/develop/ui/views/notifications/notification-permission)

### Expected behaviour

Notifications for various channels

### Current behaviour

No notifications at all

**Comment by Docile-Alligator** [comment]
Ok. I will fix this.

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/605129517ec811deb416f1bebecca6391e743cb7
