### ISSUE TITLE
Anonymous Mode does not load any content in Infinity

### ISSUE THREAD

**Issue by MetalNeo** [Docile-Alligator/Infinity-For-Reddit#1245]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

13, GrapheneOS

### Device model

Pixel 5A

### First occurred

11/20/2022

### Steps to reproduce

1. Open Anonymous mode or freshly install the app.
2. Try to access any subscription page, search, or the frontpage.
3. Error loading posts. Tap to retry.
4. Tapping to retry displays the same message.

### Expected behaviour

I expected the page/content to load.

### Current behaviour

Infinity displays the following error on every page: "Error loading posts. Tap to retry." This behavior does not occur when using an active Reddit account. I have also been able to reproduce this behavior with and without a VPN.

**Comment by Janybanny** [comment]
The same happens here. I'm happy to provide logs if possible (Haven't figured out where they're saved by myself so help for that would be appreciated). Using CalyxOS

**Comment by luffy3298** [comment]
same issue 

model : motog40
os: android 13 (PE rom)
app version: 5.3.4
app source: fdroid
gplay services enabled

**Comment by Akruidenberg** [comment]
Same for me.

**Comment by poubellier** [comment]
Can relate too, GrapheneOS A13, Pixel 7, version 5.3.4 dowbloaded from fdroid.
The app just does not work anymore

**Comment by Kobalt-nl** [comment]
Motorola Stylus 5G (2022) running Android 12,
5.3.4 Google play version, exact issue

**Comment by Donkey-Doug** [comment]
Same, also with other reddit apps.

**Comment by MarissaRS** [comment]
Occurs on GrapheneOS on Pixel 4, even with a fresh install.

**Comment by Douile** [comment]
It seems like glide failing to load an image from styles.redditmedia.com causes the whole load to fail.

<details><summary>Log</summary>



```
11-21 00:19:03.942 W/Glide   (11538): Load failed for https://styles.redditmedia.com/t5_2zmfe/styles/communityIcon_rbbsilkbkz481.png?width=256&s=0595a71076960043394dc8b65cfcb7208ce21d5d with size [132x132]
11-21 00:19:03.942 W/Glide   (11538): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
11-21 00:19:03.942 W/Glide   (11538): There was 1 root cause:
11-21 00:19:03.942 W/Glide   (11538): com.bumptech.glide.load.HttpException(, status code: 404)
11-21 00:19:03.942 W/Glide   (11538):  call GlideException#logRootCauses(String) for more detail
11-21 00:19:03.942 W/Glide   (11538):   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
11-21 00:19:03.942 W/Glide   (11538): There was 1 root cause:
11-21 00:19:03.942 W/Glide   (11538): com.bumptech.glide.load.HttpException(, status code: 404)
11-21 00:19:03.942 W/Glide   (11538):  call GlideException#logRootCauses(String) for more detail
11-21 00:19:03.942 W/Glide   (11538):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
11-21 00:19:03.942 W/Glide   (11538): There was 1 root cause:
11-21 00:19:03.942 W/Glide   (11538): com.bumptech.glide.load.HttpException(, status code: 404)
11-21 00:19:03.942 W/Glide   (11538):  call GlideException#logRootCauses(String) for more detail
11-21 00:19:03.942 W/Glide   (11538):       Cause (1 of 1): class com.bumptech.glide.load.HttpException: , status code: 404
11-21 00:19:03.943 I/Glide   (11538): Root cause (1 of 1)
11-21 00:19:03.943 I/Glide   (11538): com.bumptech.glide.load.HttpException: , status code: 404
11-21 00:19:03.943 I/Glide   (11538): 	at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.onResponse(OkHttpStreamFetcher.java:71)
11-21 00:19:03.943 I/Glide   (11538): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
11-21 00:19:03.943 I/Glide   (11538): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-21 00:19:03.943 I/Glide   (11538): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-21 00:19:03.943 I/Glide   (11538): 	at java.lang.Thread.run(Thread.java:923)
```


</details>

**Comment by Wave6677** [comment]
Pixel 6a, CalyxOS A13
not that i think this is device specific but everyone else is doing it so /shrug

**Comment by blahberi** [comment]
reddits API is currently unbussin

**Comment by vishalnandagopal** [comment]
Same bug, not fixed on reinstall or by using a VPN so it's either a reddit API bug or Infinity bug. Started a few days ago, but was inconsistent then. Now it's always showing the error fetching posts issue.

**Comment by RoguedBear** [comment]
working for me too. seems like something from reddit's side was down
