### ISSUE TITLE
hiding a lot of read posts results in an empty feed that requires a refresh

### ISSUE THREAD

**Issue by blahberi** [Docile-Alligator/Infinity-For-Reddit#1248]
I have already created a pull request for the fix

### Checklist

- [x] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

Google Play

### Android version

12

### First occurred

ever since i started using infinity

### Steps to reproduce

1. go to a feed where all the rendered posts are read
2. hide read posts

### Expected behaviour

https://user-images.githubusercontent.com/53308841/202900257-02d6fa27-19d3-4f2b-8c98-17e78ebde334.mp4

### Current behaviour

https://user-images.githubusercontent.com/53308841/202900254-6d047afc-2cb5-4412-9b69-847acb63e41e.mp4

**Comment by Wladefant** [comment]
still an issue? Not able to reproduce it. And if it runs in the simulator but on the phone, that normally means that the bug in the main branch is fixed.
