### ISSUE TITLE
RPAN discontinued

### ISSUE THREAD

**Issue by Nojuuu** [Docile-Alligator/Infinity-For-Reddit#1249]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

Google Play

### Android version

11

### Steps to reproduce

1. Try to view RPAN

### Example post, link, markdown...

https://www.reddit.com/r/pan/comments/yl5zzd/update_on_the_future_of_live_video_broadcasting/

### Expected behaviour

Remove related code at some point?

### Current behaviour

Not working.

**Comment by Docile-Alligator** [comment]
It will be removed.
