### ISSUE TITLE
Videos using http://i.imgur.com do not play

### ISSUE THREAD

**Issue by Para-lyzed** [Docile-Alligator/Infinity-For-Reddit#1259]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

Android 11 LineageOS 18.1

### Device model

OnePlus 7 Pro

### First occurred

yesterday was first recorded occurrence

### Steps to reproduce

1. Find a video which uses the http://i.imgur.com link when you click share video option (I've found multiple on r/BetterEveryLoop)
2. Attempt to play the video using Infinity
3. Video does not play

### Example post, link, markdown...

https://www.reddit.com/r/BetterEveryLoop/comments/z1te2l/what_uh_what/ (first recorded link with this issue, verified by other users in #1058)
https://www.reddit.com/r/BetterEveryLoop/comments/zb865g/jump_forward_fall_back_take_a_nap/
https://www.reddit.com/r/BetterEveryLoop/comments/zannex/you_crepey_bastard/

Direct video links for each post above (in order):
http://i.imgur.com/EDPLqCa.mp4
http://i.imgur.com/hplPnfP.mp4
http://i.imgur.com/60o65pk.mp4

### Expected behaviour

Video should play with no problem

### Current behaviour

Video does not play. When I tap on the video to fullscreen it, I see a black screen (see screenshot provided), and I do not get any error message no matter how long I keep it open.

![Screenshot_20221203-105728_Infinity](https://user-images.githubusercontent.com/73729354/205457420-b5b8a6be-a0a1-4be7-835d-1cd8a30d53b2.png)

I have only found http://i.imgur.com links when I experience this issue, but I do not think it is limited to i.imgur.com. I believe this is a general issue with http video links, as https://i.imgur.com links work perfectly fine for me. Ex:

https://www.reddit.com/r/BetterEveryLoop/comments/z1fu6v/she_keeps_on_swimming_swimming_swimming/

This post uses the following link for the video:

https://i.imgur.com/EQvLn7V.mp4

Since the video plays exactly as expected, the issue does not appear to be with i.imgur.com videos, just with the ones using http instead of https. I have not yet found any other direct video links that have used http instead of https except those using i.imgur.com links. As such, I have not been able to test if this behavior is consistent with other domains when using http instead of https.

I would also like to clarify that since all my post links are *NOT* NSFW, this is a different issue than is being experienced in #1232 and other similar issues with NSFW videos. I am also able to play the video in #1058 just fine, and it is *NOT* the result of the same http issue, hence me opening a new issue for this.

Additionally, I should clarify that the video links work fine when opened in a browser or other media player such as VLC. That verifies that it is an Infinity issue, and not an issue on Imgur's side. Though it may be that the links are converted to https when they are opened in a browser or through other players like VLC (which could potentially be an easy fix for this issue).

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/pull/1240
