### ISSUE TITLE
Material you theme has odd coloring

### ISSUE THREAD

**Issue by muznyo** [Docile-Alligator/Infinity-For-Reddit#1264]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Other

### Android version

Android 13, Lineage OS

### Expected behaviour

I use Sync for Reddit and Infinity for Reddit. Infinity has material you palette like this:
![image](https://user-images.githubusercontent.com/24987471/205489904-5cb9abec-7d9d-44a8-b355-529c5536cc35.png)

### Current behaviour

Sync for Reddit has color palette like this: 
![image](https://user-images.githubusercontent.com/24987471/205489894-9c7aa3d3-2739-45da-862c-5c650032ba4b.png)

It is much less vibrant and better for user experience.

**Comment by Docile-Alligator** [comment]
Because Sync does not use a card view.

**Comment by noodlejetski** [comment]
thing is, I find it almost impossible to use Infinity with a Material You theme. some colours that it chooses are much more vivid than their counterparts virtually any other app using Material You that I've tried, some UI elements (like comment depth markers or usernames) never change their colours, and the result is incredibly garish.
