### ISSUE TITLE
Swipe gesture has become very unreliable

### ISSUE THREAD

**Issue by seirdotexe** [Docile-Alligator/Infinity-For-Reddit#1265]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Google Play

### Android version

Android 11

### Device model

OnePlus 7T

### First occurred

Today, right after the update

### Steps to reproduce

1. Set your threshold to below 0.4
2. Try a swipe to up vote, it's very unreliable (even on 0.4, it's still barely working)

### Example post, link, markdown...

This happens on *any* post/comment

### Expected behaviour

It should behave normally and you should see the color on the arrow

### Current behaviour

This is the behavior: https://streamable.com/zgx397

**Comment by seirdotexe** [comment]
Swipe also isn't working when there's a gallery post, as seen in this post: https://www.reddit.com/r/CrackWatch/comments/zc6bco/saint_kotar_the_crawling_man_v103_1122022_290mb/

**Comment by seirdotexe** [comment]
Also, swipe isn't really working when there's a gallery post. Perhaps you can create an option to disable gallery swiping?

**Comment by Toastie** [comment]
For me this issue only appears with gallery posts, after viewing the gallery fullscreen. 
Though it happens 100% of the time for me, I'd thus guess that it is related to the gallery view.

**Comment by seirdotexe** [comment]
@Toastie I'm not sure why you decided to post your comment on a separate issue. I recommend that you remove your comment, as it may be confusing to the authors of this repository.

**Comment by Wladefant** [comment]
Not able to reproduce still an issue?

**Comment by seirdotexe** [comment]
Not able to reproduce either anymore. New device (Pixel 7 pro) and on version 5.4.0-beta4.
