### ISSUE TITLE
Swipe right to return not working after viewing gallery post

### ISSUE THREAD

**Issue by Toastie** [Docile-Alligator/Infinity-For-Reddit#1269]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Google Play

### Android version

13

### Device model

S22 Ultra

### First occurred

About a Week ago

### Steps to reproduce

1. Open any gallery post (multiple pictures)
2. View the gallery fullscreen and swipe through it
3. After leaving fullscreen swiping right does not return 

### Example post, link, markdown...

https://streamable.com/3yulxj

1. Expected behavior
2. Bugged behavior
3. Again expected behavior after using the return button

### Expected behaviour

The post is closed as if you hit the back button, and you are returned to whatever page was open previously

### Current behaviour

Nothing happens, closing the post with the back button still works, after opening the post again (and not viewing the gallery) swipe right to retun works again as expected.

**Comment by Toastie** [comment]
This is similar to #1265 though I do not use the swipe gestures but simply swipe right to return.

**Comment by gbakeman** [comment]
Even just viewing a gallery post non-fullscreen, you're unable to swipe right to return to the previous screen. Would be nice if we could still swipe right to go back, if we're currently at the first item in a gallery.

**Comment by wsy2220** [comment]
This is anoying sometimes

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/d65a355bdce31a7c3659477ae786712f433b609c
