### ISSUE TITLE
No download button when viewing photos of a gallery

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#1271]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

12

### Device model

Xiaomi Mi 9T Pro

### First occurred

Recently, do not know exactly

### Steps to reproduce

1. View any image in a gallery 
2. There is no download button

### Expected behaviour

There should be a download button to save the images

### Current behaviour

No download button

**Comment by Docile-Alligator** [comment]
Fixed in v5.4.0-beta1.
