### ISSUE TITLE
Cannot Search for NSFW Subs

### ISSUE THREAD

**Issue by Foxtrek64** [Docile-Alligator/Infinity-For-Reddit#1283]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

Android 13 (Graphene OS)

### Device model

Google Pixel 5

### First occurred

November 30, 2022 (initial app install)

### Steps to reproduce

1. In the app under Setings -> NSFW & Spoiler, ensure Enable NSFW is enabled
2. On the Reddit website, go to your account settings -> Feed Settings and ensure Adult Content is enabled.
3. If changes were made in steps 1 or 2, restart the app.
4. In the app, search for an NSFW subreddit, such as `gonewild`. This subreddit does not appear in search results, even when the full name of the subreddit is provided.
  * The posts tab will show results from SFW subreddits where the contents of the post have a text match with the search. For instance, the first search at the time of writing result shows a post from `r/WhitePeopleTwitter` where the title contains the text "#Gonewild."
  * The subreddits tab shows subs that allow nsfw content but are not themselves marked as NSFW. For instance, `r/circlejerk` and `r/sex` are in the top three.

### Expected behaviour

With NSFW enabled, NSFW subreddits should appear in the search results alongside related results.

### Current behaviour

When searching for a NSFW subreddit by name, even when the full name is provided, the desired search result is still filtered from the displayed list. I suspect that the NSFW filter is not being properly disabled for search results when the NSFW option is toggled on.

**Comment by Foxtrek64** [comment]
Is there possibly some third configuration I need to make besides enabling nsfw both in reddit and in infinity? Search results are the same whether or not I allow a sort of implicit search like your screenshot or if I submit the query and it shows the options for Post, Subreddits, or Users.

As pointed out in my original post, none of the subreddits in my search results are NSFW, so this isn't just related to this one specific sub. 

![NSFW Settings](https://cdn.discordapp.com/attachments/468748717684686868/1053582836952731718/Screenshot_20221217-020147.png "NSFW Settings")
![Search Results](https://media.discordapp.net/attachments/468748717684686868/1053582723769450496/Screenshot_20221217-020109.png?width=420&height=910 "Search Results")

**Comment by us3rname101** [comment]
I could replicate your situation by turning off show NSFW content in the official reddit app and in the reddit website and checking Infinity after. You could double check that it is enabled.

**Comment by Foxtrek64** [comment]
This is the only option I could find related to this, and it is enabled. Searching for and browsing NSFW subreddits works just fine in Slide for Reddit, but I've come to Infinity because Slide is abandonware. I do not have the official reddit app installed anywhere and just use the website.

![Settings](https://cdn.discordapp.com/attachments/468748717684686868/1053651095290921071/image.png "Settings")

**Comment by Masterjoona** [comment]
A long shot but could it be the vpn that is interfering?

**Comment by Docile-Alligator** [comment]
@Foxtrek64 You can go to https://old.reddit.com/prefs/ and enable `include not safe for work (NSFW) search results in searches` and other related settings.
