### ISSUE TITLE
Do not post user mentions as links, because it breaks bots

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Docile-Alligator/Infinity-For-Reddit#1285]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.5

### Where did you get the app from

Google Play

### Android version

9.0

### First occurred

N/A

### Steps to reproduce

- Go to any post
- Try to make a comment that's just a mention of another user: `u/usernamehere` for example.

The user mention will automatically be transformed into a hyperlink before getting posted. This prevents users from interacting with bots that require just a username to be provided.

### Example post, link, markdown...

`u/usernamehere`

### Expected behaviour

That the comment posted be `u/usernamehere`

### Current behaviour

The comment posted is `[u/usernamehere](https://www.reddit.com/u/usernamehere)`

**Comment by patrickdemers6** [comment]
The automatic hyperlinking is performed automatically by Reddit ([source](https://www.reddit.com/r/changelog/comments/38ao4t/reddit_change_automatic_linking_of_rsubreddit_and/)).

To get around this, you can escape the forward slash. If commenting a username or subreddit that should not be hyperlinked, use `u\/usernamehere` instead of `u/usernamehere`.

**Comment by RSBat** [comment]
> The automatic hyperlinking is performed automatically by Reddit ([source](https://www.reddit.com/r/changelog/comments/38ao4t/reddit_change_automatic_linking_of_rsubreddit_and/))

But that's not what they are reporting about - if you check markdown in json response it will have no hyperlinks. 

But also the reproduction steps don't work for me. The only way I know to get something similar is to edit a comment that already has user mentions.

**Comment by ItsIgnacioPortal** [comment]
> The automatic hyperlinking is performed automatically by Reddit ([source](https://www.reddit.com/r/changelog/comments/38ao4t/reddit_change_automatic_linking_of_rsubreddit_and/)).
> 
> To get around this, you can escape the forward slash. If commenting a username or subreddit that should not be hyperlinked, use `u\/usernamehere` instead of `u/usernamehere`.

Oh, you're right. I thought this behaviour was unique to Infinity :p
