### ISSUE TITLE
Change home tabs

### ISSUE THREAD

**Issue by UltraBlackLinux** [Docile-Alligator/Infinity-For-Reddit#129]
So Ive used red reader before and when I saw this app I instandly switched. 
One thing though: Please add a feature to rearrange or remove tabs from the home screen, cause im absolutely not interested in "Popular" or "All"

**Comment by Docile-Alligator** [comment]
Good idea. Currently, you can customize tabs in settings -> interface -> customize tabs in main page.

**Comment by UltraBlackLinux** [comment]
oh lol! i just couldnt find that, thank you for the response!
Should I keep this open?

**Comment by Docile-Alligator** [comment]
You are very welcome!
