### ISSUE TITLE
Images have infinite height in gallery 

### ISSUE THREAD

**Issue by RSBat** [Docile-Alligator/Infinity-For-Reddit#1295]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Google Play

### Android version

12

### First occurred

5.4.0-beta1

### Steps to reproduce

Enable "Fixed height in card"
Open subreddit that has posts with galleries

### Example post, link, markdown...

https://www.reddit.com/r/lego/comments/zlmpuo/lego_harry_potter_2023_megathread/ - currently stickied

### Expected behaviour

Displays normally

### Current behaviour

Post has infinite height

**Comment by StaticRocket** [comment]
This seems to especially be the case for galleries containing GIFs.
