### ISSUE TITLE
Change video Resolution

### ISSUE THREAD

**Issue by UltraBlackLinux** [Docile-Alligator/Infinity-For-Reddit#130]
Another suggestion for ppl that would like to have a web connection that lasts longer than 2 vids cause they have no more mobile data left lol
(Im one of those)
hope it gets added!

**Comment by Docile-Alligator** [comment]
Do you mean changing to a lower resolution by default?

**Comment by UltraBlackLinux** [comment]
Yes, take a look at newpipe and the resolution thingy

**Comment by Docile-Alligator** [comment]
This is added in 4.1.0-beta.
