### ISSUE TITLE
Filtered posts in an nsfw subreddit sould not be blurred when "Don't blur NSFW Images in NSFW Subreddits" is on

### ISSUE THREAD

**Issue by ywssp** [Docile-Alligator/Infinity-For-Reddit#1301]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

Google Play

### Android version

Android 10, Hades Rom 3.0 for Samsung Galaxy S8

### Device model

Galaxy S8

### First occurred

N/A

### Steps to reproduce

1. Go to Settings > NSFW & Spoiler, and make sure that:
a. "Blur NSFW Images" is on, and
b. "Don't blur NSFW Images in NSFW Subreddits" is off.
2. Go to an NSFW-Tagged Subreddit
3. Press the three dots on the top-right, and press "Filter Posts"

### Expected behaviour

The NSFW images should not be blurred

### Current behaviour

The NSFW images are blurred

**Comment by Wladefant** [comment]
Not able to reproduce
