### ISSUE TITLE
subsequent images in gallery take long time to load

### ISSUE THREAD

**Issue by Offerel** [Docile-Alligator/Infinity-For-Reddit#1303]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

13

### Device model

Galaxy S20

### First occurred

1 week ago 

### Steps to reproduce

1. Search a gallery post
2. Open first image
3. Image load instantly
4. Load next image 
5. Image load insane long time or not at all 

### Example post, link, markdown...

Every gallery post 

### Expected behaviour

The subsequent images should load in a faster time of only some milliseconds or seconds.

### Current behaviour

It takes ages until the next image is loaded. Sometimes the next is never loaded or I give up, after some minutes.

**Comment by seirdotexe** [comment]
Like any other Reddit app, it's best to load all the images first and then show the post.

**Comment by Wladefant** [comment]
That is a feature not a bug (First picture instant load) ;)
