### ISSUE TITLE
Gallery of gifs locks the app

### ISSUE THREAD

**Issue by seirdotexe** [Docile-Alligator/Infinity-For-Reddit#1304]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Google Play

### Android version

Android 11

### Device model

OnePlus 7T

### First occurred

Ever since the gallery features were added (04-12-2022)

### Steps to reproduce

1. Come across a gallery of gifs
2. You're now stuck! You can't hide it or scroll past it, and clicking on it crashes the app

### Example post, link, markdown...

https://www.reddit.com/r/ModernWarfareII/comments/zzg3s6/what_it_feels_like_to_play_shipment_as_mediocre/

### Expected behaviour

A gallery of gifs should behave normal.

### Current behaviour

https://streamable.com/qnhy3u

**Comment by twizzlebizzle** [comment]
Had the same, had to revert to 5.3.4

**Comment by Sepruko** [comment]
I can reproduce this issue on `5.4.0-beta1`.

**Comment by seirdotexe** [comment]
The app doesn't crash when a gallery of 1 gif and 2 images come by. For reference, https://www.reddit.com/r/DeepRockGalactic/comments/10bu5is/armskore_coil_gun_i_designed_and_printed/

**Comment by Black-StellarSpectrum** [comment]
I'm facing the same issue as well the gif gallery does on forever and in every layout card layout/2, gallery layout as well, it just goes on forever can't reach next post! Please fix this.
I'm on version **5.4.0-beta1**

**Comment by Docile-Alligator** [comment]
Fixed.
