### ISSUE TITLE
Voting buttons are buggy

### ISSUE THREAD

**Issue by seirdotexe** [Docile-Alligator/Infinity-For-Reddit#1322]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Google Play

### Android version

Android 11

### Device model

OnePlus 7T

### First occurred

Unknown

### Steps to reproduce

1. Upvote or downvote a post
2. Open the post
3. Change your vote
4. Go back
5. The post is now upvoted and downvoted at the same time

### Example post, link, markdown...

Any post

### Expected behaviour

Upvoting or downvoting should be set correctly

### Current behaviour

![Screenshot_20230110-234315](https://user-images.githubusercontent.com/80536518/211678010-dfc53f47-5cd9-49fa-9a60-a8eebcb4df12.jpg)

**Comment by Wladefant** [comment]
Not able to reproduce

**Comment by seirdotexe** [comment]
Not able to reproduce either anymore. New device (Pixel 7 pro) and on version 5.4.0-beta4.

**Comment by starchyunderscore** [comment]
possibly reopen? i was able to reproduce on 5.4.2-beta1, moto g stylus 5g (2022), android 12

i dont think the steps were the same though, and am unsure what exactly caused it. i also recall it happening on 5.4.0 an my old phone, SM-A102U, android 11

screenshot from today:

![Screenshot_20230504-083650.png](https://user-images.githubusercontent.com/102399926/236207909-92c69823-1e5e-4180-b983-c69b866fc3c4.png)

**Comment by seirdotexe** [comment]
Based on the comment by @starchyunderscore, I tried to reproduce this on my Pixel 7 Pro (Android 13).

I wasn't able to reproduce it with the method I did in Android 11, but I was able to reproduce this by tapping the up-and downvote quickly together and then going back out the post.

I think the method I just found is a new "bug", and possibly what happened with @starchyunderscore.

**Comment by starchyunderscore** [comment]
> I think the method I just found is a new "bug", and possibly what happened with @starchyunderscore.

i actually went back to check, i was able to reproduce wtih the changing vote & hitting back button method i have a screen record but i dont have the time to upload it due to school. will as soon as i can.

**Comment by seirdotexe** [comment]
Android 11/12 has this problem then. Android 13 only has it when you tap the up-and downvote quickly together and then go out of the post.

**Comment by starchyunderscore** [comment]
ok i finally got the time, here is nhe screen record of me reproduring the bug twice, at about 0:25 and 0:50

https://youtu.be/bhnbocUbLYc

**Comment by starchyunderscore** [comment]
and heres a screen record of the methed @seirdotexe described, which seems to be more consistant, though less likely to happen in general use.

https://cdn.discordapp.com/attachments/887433156855201795/1103708277361090660/screen-20230504-112746.mp4

**Comment by starchyunderscore** [comment]
also found a similar situation that may be caused by the same bug.

1. upvote a post
2. enter the comments
3. un-upvote the post
4. swipe to the next post (unconfirmed if this is needed)
5. hit back button

upvote arrow stays colored despite your vote not counting toward the number, and you can click the upvote button again to cast your vote.

vid: https://cdn.discordapp.com/attachments/1104898178085556384/1105275564413165588/screen-20230508-192917.mp4

**Comment by starchyunderscore** [comment]
Well at least I wont be wasting as much of my life on my phone I guess.

**Comment by starchyunderscore** [comment]
also, even though that may be the case it is no reason to close the issue, after all the api changes can be worked around so it is not necessarily the death of the app.
