### ISSUE TITLE
Paused videos continue after slight scroll

### ISSUE THREAD

**Issue by seirdotexe** [Docile-Alligator/Infinity-For-Reddit#1325]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Google Play

### Android version

Android 11

### Device model

OnePlus 7T

### First occurred

Unknown

### Steps to reproduce

1. Play a video in the feed
2. Pause it
3. Make a slight scroll
4. The paused video unpauses itself for no reason

### Example post, link, markdown...

Any video in your feed

### Expected behaviour

Paused videos should stay paused no matter what

### Current behaviour

Paused videos seem to not realize when to be unpaused

**Comment by Brendan-McDonnell** [comment]
I can confirm I'm facing the same issue.

It also interacts with the volume of the video for me. When it resumes play on its own it mutes the video but does not update the mute button on the video, making it falsely appear to be unmuted. Pressing the button puts it back in the right state (video unmuted, button unmuted).

My video settings that might be relevant:
```
Mute Videos: false
Mute Autoplaying Videos: true
Remember muting Option in Post Feed: true
Autoplay Videos Visible Area Offset (Portrait): 75%
```
