### ISSUE TITLE
Saved tab shows only saved posts and hides saved comments

### ISSUE THREAD

**Issue by jcperil** [Docile-Alligator/Infinity-For-Reddit#1328]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

12

### Steps to reproduce

1. Settings >> Interface >> Customize Tabs in Main Page
2. Modify one of the tabs to type **Saved**
3. Return to feed and swipe to the Saved Tab

### Expected behaviour

Show saved posts and saved comments.

Otherwise, please create separate Tab types for Saved Posts and Saved Comments.

### Current behaviour

Shows only saved posts.

**Comment by Wladefant** [comment]
That is not a bug. But you can definitely request this feature in our discussions.
