### ISSUE TITLE
Cached image not shown in Fullscreen view

### ISSUE THREAD

**Issue by sepehrsohrabi** [Docile-Alligator/Infinity-For-Reddit#1330]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.5

### Where did you get the app from

Google Play

### Android version

10

### First occurred

Today

### Steps to reproduce

1. Open any image or video

### Expected behaviour

Cached Media should be loaded in while going into Fullscreen view until a higher resolution version can be downloaded.
Black screen with a progress bar ain't pretty. Specially when there is already something cached and ready to be shown.

**Comment by Wladefant** [comment]
This is not implemented and therefore not a bug, but you can definitely propose this feature in the [discussions](https://github.com/Docile-Alligator/Infinity-For-Reddit/discussions/new?category=ideas) tab.
