### ISSUE TITLE
Fetching removed content no longer works, due to breaking changes in the Pushshift API

### ISSUE THREAD

**Issue by JVT038** [Docile-Alligator/Infinity-For-Reddit#1334]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

F-Droid

### Android version

Android 12 /e/OS

### Device model

Fairphone 4

### First occurred

2 months

### Steps to reproduce

1. Search for a removed comment / post
2. Click 'See removed comment'
3. Error 'Could not find removed comment' pops up

### Example post, link, markdown...

This thread has a removed [comment](https://www.reddit.com/r/science/comments/10ef0z7/seeing_allgender_signs_in_public_places_was/).

It is shown on [reveddit](https://www.reveddit.com/v/science/comments/10ef0z7/seeing_allgender_signs_in_public_places_was/).

The pushshift API has been undergoing breaking changes, listed [here](https://www.reddit.com/r/pushshift/comments/zkggt0/update_on_colo_switchover_bug_fixes_reindexing/).

### Expected behaviour

I expected Infinity to properly show the comment like it used to.

### Current behaviour

Infinity is unable to fetch the removed content and instead shows 'Could not find removed comment'

**Comment by HiddenLeveI** [comment]
I was just about to post an issue like this, it just doesn't work now. Maybe Reddits cracking down?
