### ISSUE TITLE
Can the function of user-defined language selection be added?

### ISSUE THREAD

**Issue by DeeEi** [Docile-Alligator/Infinity-For-Reddit#1342]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.5

### Where did you get the app from

Google Play

### Android version

12

### Steps to reproduce

Can the function of user-defined language selection be added?

My phone language is traditional Chinese,

But the app language is English.

I hope that I can define my favorite language in apps manually...

**Comment by Docile-Alligator** [comment]
Traditional Chinese is not available right now. You can go to https://poeditor.com/join/project/b2IRyfaJv6 to translate the strings.

To change the language in Infinity, you can go to Settings->Miscellaneous->Language.
