### ISSUE TITLE
Changing theme makes the floating button invisible

### ISSUE THREAD

**Issue by Drangonfly30** [Docile-Alligator/Infinity-For-Reddit#1344]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0 beta 2

### Where did you get the app from

Other

### Android version

Android 7.0

### Device model

Lenovo K6 power

### First occurred

Today

### Steps to reproduce

1. Apply a new theme
2. That's it, there is no background color in floating button.
![Screenshot_2023-01-26-02-19-52-106](https://user-images.githubusercontent.com/113085944/214690101-3fd8aa34-1e16-4c27-b3db-475c673d1871.jpeg)

**Comment by Wladefant** [comment]
Hey, you need to be more specific. I am not able to reproduce this issue. Please provide the changes you have made.

**Comment by Drangonfly30** [comment]
Sorry to not make it clear, so, there is [this](https://www.reddit.com/r/Infinity_For_Reddit/comments/y5ipja/official_reddit_app_theme_for_infinity/) reddit theme which I use but when I applied this theme on latest version, the floating button's + icon is not visible anymore. I hope this will help.

**Comment by bama35453** [comment]
I can confirm this issue with a white theme on the Samsung  Galaxy S22 Ultra and the Samsung Galaxy Tab S7.

![Screenshot_20230208_223725_Infinity.jpg](https://user-images.githubusercontent.com/118128192/217656750-5d9c2b77-3511-4599-a310-22c122e4484a.jpg)

**Comment by n0eL1405** [comment]
I have the same Issues with "White", "White Dark", "White Amoled" und "Dracula" themes. The Indigo ones are working fine. In the dracula theme it looked like the Floating Button Color is very similar to the Icon Color, so maybe there is something wrong. In the theme option I can't find a Floating Button Color option to test this.

Device: One Plus Nord
Android 12
App Version 5.4.0

**Comment by bama35453** [comment]
There is somewhat of a workaround:

If you change the accent color and the color for the icon on the floating button you can more or less recover the previous look and feel.
Sometimes it might be necessary to also change the  color of the background for the round progress bar. In my case after changing the accent colorI had a white progressbar on a white background which impairs the visibility a bit.
