### ISSUE TITLE
Following Fails via Search

### ISSUE THREAD

**Issue by elea11** [Docile-Alligator/Infinity-For-Reddit#1361]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.6

### Where did you get the app from

F-Droid

### Android version

Lineage OS for microG (LOS 20, Android 13)

### Device model

Pixel 4a 5G (bramble)

### First occurred

3 months, v 5.3.4

### Steps to reproduce

1. Search for a user
2a. Tap follow (+) in the search results or
2b. Open a user profile from the search results and tap "follow" in the profile
3. a toast appears: "Following Failed"

### Example post, link, markdown...

Searched for u/dietageszeitung
Opened https://www.reddit.com/user/dietageszeitung and hit "follow"

### Expected behaviour

Following the user chosen via search.

### Current behaviour

a toast appears: "Following Failed"

### Logs

Let me know if there is a way to log the error.

**Comment by Docile-Alligator** [comment]
{
    "message": "Forbidden",
    "error": 403
}

Either the user or Reddit does not allow you to follow them.

**Comment by Wladefant** [comment]
Yes, how didn`t I thought about that

**Comment by elea11** [comment]
Well. A little embarrassing that this possibility didn't come to my mind. But UX wise: would you see a way to reflect the reason for the fail to follow in a more differentiated way in the toast message or is this system inherent by reddit itself?
