### ISSUE TITLE
The "scroll to next comment" button can be moved

### ISSUE THREAD

**Issue by MihaiBojescu** [Docile-Alligator/Infinity-For-Reddit#1374]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta4

### Where did you get the app from

F-Droid

### Android version

13

### Device model

OnePlus 6T

### First occurred

Today, 17 feb 2023

### Steps to reproduce

1. Open a subreddit;
2. Open a post;
3. Drag the "scroll to next comment" button;

### Example post, link, markdown...

https://imgur.com/a/afGhgYQ

### Expected behaviour

The "scroll to next comment" button should not be able to be moved.

### Current behaviour

The "scroll to next comment" can be moved.

**Comment by Docile-Alligator** [comment]
This is a feature. Not a bug.
