### ISSUE TITLE
Imgur links not working

### ISSUE THREAD

**Issue by Amu1et** [Docile-Alligator/Infinity-For-Reddit#1375]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0

### Where did you get the app from

Google Play

### Android version

13

### Device model

Samsung Galaxy S22

### First occurred

Not sure, been happening for a while

### Steps to reproduce

1. Find a post that links to imgur to display images
2. Images appear to load, but are not shown fully
3. Tap the image to see the full thing
4. It says that the images cannot be loaded

### Example post, link, markdown...

https://www.reddit.com/r/rarepuppers/comments/10zt1w1/happy_weekend/

This is just an example, this happens with any post that links to imgur

### Expected behaviour

Show me the full image

### Current behaviour

![Screenshot_20230219_012447_Infinity](https://user-images.githubusercontent.com/125786426/219932627-25d1b310-566e-413c-9ec8-19093441dd52.jpg)

**Comment by camporter** [comment]
Looks like imgur is throttling the client ☹️

**Comment by Wladefant** [comment]
@camporter yeah probably
