### ISSUE TITLE
Redgif videos fail to load

### ISSUE THREAD

**Issue by reachrishav** [Docile-Alligator/Infinity-For-Reddit#1378]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0

### Where did you get the app from

Other

### Android version

13

### Steps to reproduce

Open any video from Redgifs, it fails to load.

**Comment by wyjek** [comment]
I have the same problem.

**Comment by Seltyk** [comment]
For me, every video that fails to load (citing a Redgifs fetch failure) points to https://v.redd.it/randomchars/DASH_XXX.mp4 (where XXX is 480 or 360) when tapping the share button. Not all videos with this link format fail to load, however.

**Comment by Nosnahc** [comment]
+1

**Comment by Seltyk** [comment]
The bug seems to have disappeared?

**Comment by test2a** [comment]
Its still not working

**Comment by Wladefant** [comment]
Try it out with a VPN and then say whether it worked

**Comment by skypeias** [comment]
still not working as of now
