### ISSUE TITLE
Last hour upvoted/downvote problem 

### ISSUE THREAD

**Issue by Turhvjbufv** [Docile-Alligator/Infinity-For-Reddit#1379]
### Checklist

- [x] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0 beta 4

### Where did you get the app from

F-Droid

### Android version

12

### Steps to reproduce

In the last hour trying to upvote or downvote a post/comment results in an error most of the time 
Also comments section doesn't work

Edit: currently seems like there was a problem with reddit servers so I'm closing this

### Expected behaviour

No error 

### Current behaviour

Error

**Comment by msr8** [comment]
+1, also having some problems loading comments

**Comment by dawierha** [comment]
I can't see the comments as of today. upvote/down vote works for me at the moment. 
Using infinity v5.4.0 from fdroid on android 10

**Comment by SZenglein** [comment]
Everything worked with the Stealth reddit app.

In the meantime, all problems appear to have disappeared.
