### ISSUE TITLE
Error loading posts

### ISSUE THREAD

**Issue by wetbandits6** [Docile-Alligator/Infinity-For-Reddit#1381]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

Infinity 5.4.0-beta4

### Where did you get the app from

Easyondroid repo via Fdroid

### Android version

13 - using GrapheneOS stable build TQ1A.230205.002.2023021000

### Device model

Google Pixel 4a

### First occurred

About 10 minutes ago

### Steps to reproduce

I've opened the app and I was unable to make it work. Regardless of what I choose, I get the "Error loading posts" text. I have tried to restart my phone and I get the same result. I was thinking that maybe Reddit changed something on their side and that there was no update in the easyondroid repo.

### Expected behaviour

The app should load normaly.

### Current behaviour

![Screenshot_20230222-110727](https://user-images.githubusercontent.com/104840134/220575068-c01b62b7-cf38-4978-9efb-0d55a597d0ca.png)

**Comment by Wladefant** [comment]
Yeah that seems to a reddit issue. Does happen sometimes
