### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by yephny** [Docile-Alligator/Infinity-For-Reddit#1382]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0

### Where did you get the app from

F-Droid

### Android version

10

### First occurred

Noticed it today

### Steps to reproduce

In my case, this is how it played out:
1. "Add an account".
2. Enter your username and password. This didn't work, some characters got replaced with the new ones as I typed in, so I ended up copy-pasting my credentials.
3. A blank screen appears.
4. Hit the button in the bottom right to try a different login method. It loads a modern version of Reddit.
5. Enter your credentials.
6. The screen is blank once again, with no way to go back to the old login method.

### Expected behaviour

I expect to log in successfully. It's worked previously.

### Current behaviour

You'll find a screenshot of the blank screen down below.
![infinitybug](https://user-images.githubusercontent.com/88166326/220837157-c937bfc4-d9b5-4522-8d31-573b3cea2d05.jpg)
I've also tried logging in with a VPN. It's not network related.

**Comment by Wladefant** [comment]
You probably mean this with the new reddit screen? ![Screenshot_20230223-140121_Infinity.jpg](https://user-images.githubusercontent.com/79611093/220913830-85a9a657-a838-4186-a900-1540f6804348.jpg)

**Comment by yephny** [comment]
I downgraded Infinity and cleared its data, yet I still can't log into my accounts. I wonder what's changed, could it be on Reddit's end? Could it be related to Webview somehow?

**Comment by leoacevedo** [comment]
Something definitely changed on Reddit's end, as RedReader another Reddit client has the same issue.

**Comment by yephny** [comment]
@leoacevedo You're right, I can't log in with RedReader anymore.

**Comment by ayesc9000** [comment]
I am no longer able to use Infinity at all. Login is completely broken. Something definately changed on Reddit's side, as accounts with 2FA don't need to include the 2FA code in the password field anymore.

**Comment by CamilleHbp** [comment]
Can't login at all either.

**Comment by erri120** [comment]
I'm getting this error when trying to login:

![Screenshot_2023-03-14-20-33-46-01_2656fe66d4cc08342e93fbdd9fd1d373.jpg](https://user-images.githubusercontent.com/16577545/225160168-b22a01bb-423a-4c74-8bce-bebaecc69c72.jpg)

![Screenshot_2023-03-14-20-33-51-02_2656fe66d4cc08342e93fbdd9fd1d373.jpg](https://user-images.githubusercontent.com/16577545/225160167-de20b335-ab5b-4a6f-93af-ed9bea334bfb.jpg)

**Comment by yephny** [comment]
@ayesc9000 @CamilleHbp @erri120 Can you log in now? Reddit was down for a while.

**Comment by hennaoh** [comment]
> @ayesc9000 @CamilleHbp @erri120 Can you log in now? Reddit was down for a while. I still can't.

I've been trying for a week now. Still can't log in.

**Comment by erri120** [comment]
Works fine now.

**Comment by ayesc9000** [comment]
> @ayesc9000 @CamilleHbp @erri120 Can you log in now? Reddit was down for a while. I still can't.

Yes, login is working again.

**Comment by hennaoh** [comment]
Updated Android System Webview. Login works fine now.

**Comment by yephny** [comment]
@hennaoh Thanks it worked for me as well. Updating WebView is the solution.

**Comment by CamilleHbp** [comment]
Sorry about that, I can confirm it's working as well. Thanks!
