### ISSUE TITLE
[Bug] Button for follow other user Multireddits didn't show

### ISSUE THREAD

**Issue by l2eused** [Docile-Alligator/Infinity-For-Reddit#1391]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0

### Where did you get the app from

F-Droid

### Android version

10

### Steps to reproduce

1. open post that share multireddits
2. try to following but didn't find follow button
3. try to follow by using edit multireddits option but seems didn't work `can't edit this multireddit` <--- that's true (I just tried)
4. open this issue

### Example post, link, markdown...

Example post [r/Catsubs wiki](https://www.reddit.com/r/Catsubs/wiki/index) 
Example multireddits [Multireddits in Catsubs wiki](https://www.reddit.com/user/ickybus/m/generalcats/)

**Comment by mangkoran** [comment]
Hi @l2eused. Is the issue already fixed? I notice that we I still couldn't add public multireddit.
