### ISSUE TITLE
[bug] Left swiping in multireddit gallery goes back

### ISSUE THREAD

**Issue by terraxus94** [Docile-Alligator/Infinity-For-Reddit#1392]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0

### Where did you get the app from

Google Play

### Android version

One Ui 5.1, Android 13

### First occurred

First noticed on 20230227

### Steps to reproduce

1. Create a multireddit and open it
2. Within the multireddit find a post with a gallery of images
3. Swiping right on the gallery goes through the images, swiping left doesn't change the image but goes back to the multireddit screen

### Expected behaviour

Left swipe on gallery changes the images to the previous one 

### Current behaviour

Left swipe on gallery goes to the previous (multireddit) screen

**Comment by terraxus94** [comment]
Issue in action
https://photos.app.goo.gl/qVNqw8FE1aqRvMpH6

**Comment by Docile-Alligator** [comment]
Fixed in v5.4.2-beta1.
