### ISSUE TITLE
Left swipe not always working 

### ISSUE THREAD

**Issue by Matszwe02** [Docile-Alligator/Infinity-For-Reddit#1401]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.1

### Where did you get the app from

Google Play

### Android version

13

### Device model

Samsung S22

### First occurred

2 weeks - a month ago 

### Steps to reproduce

Go to different subreddits, click posts, click users etc
Left swipe in order to go back to subreddits, reddit main page 
Sometimes, the left back swipe doesn't go back, it thinks there's nothing to go back to (screen stretches like in home page) 

### Expected behaviour

Left swipe always working 

### Current behaviour

Sometimes (can't find the rule) it just doesn't work

**Comment by yephny** [comment]
Yes, this was introduced along with the feature that allows you to swipe to go through images in a gallery post without opening the images in full screen.

**Comment by Docile-Alligator** [comment]
Fixed in v5.4.2-beta1.
