### ISSUE TITLE
Videos rendered in bad quality

### ISSUE THREAD

**Issue by seirdotexe** [Docile-Alligator/Infinity-For-Reddit#1426]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.1

### Where did you get the app from

Google Play

### Android version

Android 12

### Device model

Pixel 7 Pro

### First occurred

Unknown

### Steps to reproduce

1. Play any video
2. The quality is bad
3. Wait 5 seconds or skip in the video
4. Quality is now good

### Example post, link, markdown...

Any video on mobile data or wifi

### Expected behaviour

Videos should be rendered in the best quality, especially when I set it up like that in my settings

### Current behaviour

Videos are rendered in bad quality for at least 5 seconds

**Comment by Docile-Alligator** [comment]
Which option did you change in settings?

**Comment by seirdotexe** [comment]
> Which option did you change in settings?

Nothing related to quality. Data savings is also disabled on the app and in my phone.
![Screenshot_20230503-153528.png](https://user-images.githubusercontent.com/80536518/235931904-60c3f7eb-480b-45a1-bc7e-0b257e47029c.png)

![Screenshot_20230503-153537.png](https://user-images.githubusercontent.com/80536518/235931939-de2f922d-397b-4649-bce2-bae78a2182d4.png)

**Comment by seirdotexe** [comment]
@Docile-Alligator It could be that this happens on mobile data only. I'm not sure yet, but something is off.

**Comment by Alvie** [comment]
This is also my experience. It starts off on a low quality and then increases to full quality after a few seconds. On both wifi and mobile data. Setting the option manually to the highest resolution/bitrate does help but it would be nice if it starts at highest quality (perhaps a setting for it in the settings similar to the way youtube does it e.g. highest quality/data saving/full auto.

**Comment by Alvie** [comment]
> Closing as Reddit is killing third party apps

The developer has stated they're going to look into allowing custom API keys in the app I believe.
