### ISSUE TITLE
Infinity crashes loading comments of particular post

### ISSUE THREAD

**Issue by mrhappy200** [Docile-Alligator/Infinity-For-Reddit#1438]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.1.9

### Where did you get the app from

Google Play

### Android version

11

### Device model

OnePlus Nord n10

### First occurred

Today 19-04-2023

### Steps to reproduce

Open the post 
Scroll down a bit
App crashes

Alternatively you can:
Open the post
Minimize the first two comment threads
The third one also crashes the app

### Example post, link, markdown...

https://www.reddit.com/r/linux/comments/12r4xqe/spot_the_backdoor_can_you_tell_whats_wrong_with/

![Screenshot_20230419-132337](https://user-images.githubusercontent.com/74416511/233060500-41e0380e-0501-42b4-9a0b-5d9ea58bcb74.jpg)
It seems like it might be this comment, large parts of it were hidden with the spoiler tag.

### Expected behaviour

Keep showing comments without a crash

### Current behaviour

It crashed (sorry for lack of detail I don't know what to add)

https://user-images.githubusercontent.com/74416511/233058305-e5dbf786-1f4b-42ff-ac70-3007b809f30d.mp4

### Logs

I can't seem to copy and paste from the crash reports section of settings, what am I doing wrong?

It seems to be some kind of rendering bug since once that particular comment gets on screen regardless of how it happened the app crashes.
If I sort the comments by some other metric it crashes after scrolling further, this implies that it really is a particular comment crashing the app.

**Comment by mrhappy200** [comment]
Wait after further searching I believe it might be a duplicate of this issue: #1104 should I close this issue?

**Comment by us3rname101** [comment]
The reason is that you're a year late on updates.

**Comment by mrhappy200** [comment]
I see, I should check if auto updates are working correctly
