### ISSUE TITLE
Are private messages possible? 

### ISSUE THREAD

**Issue by cdysthe** [Docile-Alligator/Infinity-For-Reddit#144]
I see that I get incoming private messages in Infinity but can't for the life of me figure out how to send one, so maybe it's not supported? If not consider this a feature request.

**Comment by Docile-Alligator** [comment]
Will be available in the next update.

**Comment by tegutistgut** [comment]
Is Available in version 4.0.0 can be closed

**Comment by Docile-Alligator** [comment]
Done
