### ISSUE TITLE
Edited text goes over username

### ISSUE THREAD

**Issue by us3rname101** [Docile-Alligator/Infinity-For-Reddit#1448]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.2-beta1

### Where did you get the app from

Other

### Android version

12

### Device model

OnePlus Nord 

### First occurred

Today

### Steps to reproduce

1. Find a comment that has been edited and the username is long
2. Have hidden toolbar on comments enabled
3. Observe the edited text go over the username 

### Example post, link, markdown...

https://www.reddit.com/r/pics/comments/132ueaa/the_first_photo_of_the_chernobyl_plant_taken_by/ji79k8g/

### Expected behaviour

The text should move somewhere else and not go over other text.

### Current behaviour

https://user-images.githubusercontent.com/95178906/235325206-38909718-5c71-422e-abbd-589be804d663.mp4

**Comment by starchyunderscore** [comment]
also seems to go ovor flair

![Screenshot_20230506-222532](https://user-images.githubusercontent.com/102399926/236654525-18d38ec4-aee3-49eb-9ea4-e3a5502640b8.png)
