### ISSUE TITLE
typo in notification for mixing audio and video when downloading a video

### ISSUE THREAD

**Issue by PigeonCoding** [Docile-Alligator/Infinity-For-Reddit#1452]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.1

### Where did you get the app from

F-Droid

### Android version

miui 13.0.1

### Device model

poco m3

### First occurred

today

### Steps to reproduce

Download a video with audio 

### Example post, link, markdown...

https://drive.google.com/file/d/1Mq6apdyF33vBG4dP3bOTj3fYLDxmUFk8/view?usp=drivesdk

### Expected behaviour

Say "mixing video and audio"

### Current behaviour

Say "Muxing video and audio"

**Comment by us3rname101** [comment]
Muxing is the correct word
[Multiplexing refers to the process of interleaving audio and video into one coherent data stream](https://en.wikipedia.org/wiki/Multiplexing)

**Comment by PigeonCoding** [comment]
> Muxing is the correct word
> [Multiplexing refers to the process of interleaving audio and video into one coherent data stream](https://en.wikipedia.org/wiki/Multiplexing)

Oh ok sorry for the inconvenience and thank you for the information
