### ISSUE TITLE
[Feature Request] Bring moderator tools

### ISSUE THREAD

**Issue by milindgoel15** [Docile-Alligator/Infinity-For-Reddit#147]
As title says, the most important feature infinity lacks is mod tools without which many users will have to use other apps just because of that. I personally have to keep official reddit (which I don't want to).

**Comment by Docile-Alligator** [comment]
Yes, I know the pain. But I need to implement other features for normal browsing first.

**Comment by milindgoel15** [comment]
So I wanted to know if moderator tools have been implemented or infinity still lacks as of now?

Being 7 months since I last used it and just now I installed again but couldn't find mod tools in subreddit thread I am mod in.

**Comment by sudhirkhanger** [comment]
@Docile-Alligator I am curious if you would be willing to accept mod related feature PRs. And help out with directions on it.
