### ISSUE TITLE
Update translation(s?)

### ISSUE THREAD

**Issue by solokot** [Docile-Alligator/Infinity-For-Reddit#1470]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.2

### Where did you get the app from

F-Droid

### Android version

11

### Steps to reproduce

Use app

### Current behaviour

App translations don't merged from POEditor.com over half of year. For some languages (f.e. Russian) it made 100% months ago (for 5.4.x versions), but not used.

**Comment by trlef19** [comment]
I second that

**Comment by Docile-Alligator** [comment]
Done
