### ISSUE TITLE
dissapearing username

### ISSUE THREAD

**Issue by starchyunderscore** [Docile-Alligator/Infinity-For-Reddit#1475]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.2

### Where did you get the app from

Other

### Android version

12

### Device model

moto g stylus 5g 2022

### First occurred

today

### Steps to reproduce

visit the linked comment

### Example post, link, markdown...

https://www.reddit.com/r/femboymemes/comments/13n0k9m/3/jkxta89/

### Expected behaviour

username is displayed

### Current behaviour

![Screenshot_20230520-232020-532](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102399926/d8f04c4e-f371-4819-ac35-b4dac99cc4ad)

**Comment by starchyunderscore** [comment]
better screenshot

![Stitch1883c59e861.png](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102399926/3a848d39-acd5-49b5-9606-1655f412f012)

**Comment by Gitchick57** [comment]
Yes, I've noticed this also.



May 20, 2023, 11:25 PM by ***@***.***:

**Comment by starchyunderscore** [comment]
another example

![Screenshot_20230521-103153-512.png](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102399926/8770a691-a538-428d-9eb7-7beaa9945763)

https://www.reddit.com/r/linuxmemes/comments/13mi8c6/ublock_origin_to_the_death/jkxmmc2/

**Comment by starchyunderscore** [comment]
another one

![Screenshot_20230521-131838.png](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102399926/de9b5e4c-784e-4ec9-b859-5f3260666969)

https://www.reddit.com/r/CuratedTumblr/comments/13nyxsr/please_buy_my_curdled_mayonnaise_please_i_just/jl1nu2h/
