### ISSUE TITLE
[Feature Request]: Add Privacy Policy and describe why access is needed to the Redditor's account

### ISSUE THREAD

**Issue by nitramwin** [Docile-Alligator/Infinity-For-Reddit#148]
Finding no such info while looking for it here, I'd like to recommend the following be implemented on GitHub and in the app:

* Privacy Policy: overview of what data is being transferred, read or stored
* Describe in the app why access is needed when giving permission to I-F-R for writing/reading/modifying the Redditor's account

**Comment by Docile-Alligator** [comment]
OK I will try

**Comment by nitramwin** [comment]
Thanks - much appreciate your effort for improved transparency. Cheers!

**Comment by Docile-Alligator** [comment]
https://docile-alligator.github.io/
