### ISSUE TITLE
clicking on video before it loaded opens fullscreen

### ISSUE THREAD

**Issue by Matszwe02** [Docile-Alligator/Infinity-For-Reddit#1488]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.2

### Where did you get the app from

Google Play

### Android version

13

### Device model

samsung S22

### First occurred

always

### Steps to reproduce

1. scroll through posts
2. find a video
3. click on it before it started autoplaying
4. fullscreen turns on instead of video controls

### Current behaviour

Clicking should be consistent, so this click needs to open vdeo controls instead of going fullscreen. If I want to pause video or unmute, I need to wait until it fully loads (which may take a while)

**Comment by Docile-Alligator** [comment]
This is expected.

**Comment by Matszwe02** [comment]
> This is expected.

Ok, but I think making it the way I described is more useful. Maybe add an option in settings if you want to keep that default action?
