### ISSUE TITLE
[Feature Request]: Add Relay-like subreddit selector & search menu to clean up the navbar

### ISSUE THREAD

**Issue by alexsmithfanning** [Docile-Alligator/Infinity-For-Reddit#149]
Moving the subreddits you're subscribed to into the title bar (accessible by tapping on the title bar and then choosing the subreddit) would remove a ton of clutter from the navbar so the navbar isn't 3 miles long.

[Like this](https://imgur.com/a/egwUOdD)

**Comment by Docile-Alligator** [comment]
Thanks for this. I will think about it.
