### ISSUE TITLE
error loading posts

### ISSUE THREAD

**Issue by flippette** [Docile-Alligator/Infinity-For-Reddit#1492]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.2

### Where did you get the app from

F-Droid

### Android version

13 - GrapheneOS

### Device model

Google Pixel 7

### First occurred

now

### Steps to reproduce

1. open app
2. if signed in -> error loading posts
2.2. if signed out -> loading icon spins forever

### Expected behaviour

load the posts

### Current behaviour

not load the posts

i'm not sure if you're supposed to put notes here but
- the boost app works fine so that's not a reddit issue (and thus different from #1381? maybe?)
- infinity will load about sections of subreddits but never any posts

**Comment by RGBCube** [comment]
sometimes this happens after you enable 2fa, try logging out and logging back in
