### ISSUE TITLE
i can't use app after update 

### ISSUE THREAD

**Issue by amayra** [Docile-Alligator/Infinity-For-Reddit#1504]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.0.1

### Where did you get the app from

Google Play

### Android version

6.0.1

### Device model

Samsung Galaxy s5

### First occurred

after updating to the last version

### Steps to reproduce

when i click in the app i received notice about API change and i can't removed or do everything 

### Example post, link, markdown...

your post about API change and future of your app

### Expected behaviour

see the home page or something

### Current behaviour

i can only see notice about API change post

### Logs

i can't access this anymore

**Comment by amayra** [comment]
should i downgrade to keep using it this month

**Comment by Gitchick57** [comment]
I am not touching that update until 7/1 as I knew this would happen..



Jun 21, 2023, 3:16 PM by ***@***.***:

**Comment by nalnajar** [comment]
Can you post an image of this issue?
