### ISSUE TITLE
Unable to build due to customtextview missing from JCenter

### ISSUE THREAD

**Issue by aman207** [Docile-Alligator/Infinity-For-Reddit#1506]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

NA

### Where did you get the app from

Google Play

### Android version

NA

### First occurred

June 22 2023

### Steps to reproduce

Hello,
It appears that com.libRG:customtextview is missing from JCenter which is preventing this project from being built. Not sure if its possible to use the alternate method described here? https://github.com/Rajagopalr3/CustomizedTextView#import-as-module

Thanks,
-Aaron

**Comment by nalnajar** [comment]
StudyGuidex from reddit here. I put a PR for the fix i provided on reddit. Compiles and is running for me on my phone right now :)

**Comment by aman207** [comment]
Fixed in #1507
