### ISSUE TITLE
[Bug] preview.redd.it crashes infinity

### ISSUE THREAD

**Issue by Kadragon604** [Docile-Alligator/Infinity-For-Reddit#151]
I've included the specific link at the bottom. When attempting to open this image to help a user with something my infinity crashed multiple times. This is also with "open link in app" turned off so I don't see why it would be crashing. It attempts to open, but partway through loading it crashes. 

https://preview.redd.it/8u6306wugl951.png?width=1916&format=png&auto=webp&s=b0634d39c51b5a408022e3edcda15bd9e04b20c9

**Comment by OHermesJunior** [comment]
It happens with some images that are too big. But it's already fixed, will be on the next release!
