### ISSUE TITLE
app still working

### ISSUE THREAD

**Issue by Turhvjbufv** [Docile-Alligator/Infinity-For-Reddit#1517]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.0.2

### Where did you get the app from

Other

### Android version

Android 12

### First occurred

1 July 

### Steps to reproduce

App is still working for me Although it should be off, telling you this so you won't get charged or something but still work for me even tho it's July 1

### Expected behaviour

Sould not load reddit 

### Current behaviour

Loads reddit

**Comment by kajdo** [comment]
came here to report the same ... would be a shame if spez gets some foss devs into debt

**Comment by Turhvjbufv** [comment]
@Docile-Alligator

**Comment by ExecutableMarley** [comment]
The update is not fully out yet. So we have a few hours longer.
Source: https://www.reddit.com/r/Infinity_For_Reddit/comments/14nl2kv/infinity_will_still_be_free_to_use_until_the/

**Comment by BlastboomStrice** [comment]
It works even with the older version, 5.4.2.

**Comment by Turhvjbufv** [comment]
It's fine, until the next version is out, it will work on every version.
