### ISSUE TITLE
"Color Primary Light Theme" is no longer applied to the floating action bar, despite the subtitle in the settings

### ISSUE THREAD

**Issue by SuperStormer** [Docile-Alligator/Infinity-For-Reddit#1519]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.0.2

### Where did you get the app from

Other

### Android version

13

### First occurred

yesterday

### Steps to reproduce

1. Open Infinity and note the color of the FAB
2. Go to the "Customize Theme" page for your current theme
3. Observe that "Color Primary Light Theme" is no longer the color used for the FAB, but that it is instead the "Color Accent" that is used

### Expected behaviour

Use the "Color Primary Light Theme" for the FAB, or have the subtitle match the current behavior

### Current behaviour

Use the "Color Accent" for the FAB
<details>
<summary>Screenshots</summary>
![Screenshot_20230711_021333_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/41648788/bf63449d-9e2b-43cd-bb15-cc2b467b7ee9)

![Screenshot_20230711_021324_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/41648788/e626f8db-264b-4ce9-9509-ad127344a33d)
</details>

**Comment by SuperStormer** [comment]
Related issue: https://github.com/Docile-Alligator/Infinity-For-Reddit/issues/1344
I believe the current issue is the cause of the linked issue, which still occured on the current release when I imported my settings from an old version (don't remember which) to 6.0.2. [The theme in question](https://paste.pythondiscord.com/igagabohav).

------
It looks like the FAB's coloration was changed in https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/8a6eb8e025f388c9bc23e5ef30a0991eb33b7365 and https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/c5d4ac64a0c93bec80e45cdbbed15ee348283d9e 

------

The two obvious ways to fix this (at least to me) would be to removing FAB from the "Color Primary Light Theme" subtitle, or to change the FAB color back to "Color Primary Light Theme". 

Here is my kinda biased opinion in support of the latter option: Color Accent" has to be a light color—otherwise, the headings on the settings pages would be unreadable, and likely other text using the accent color as the text color. This means that themes like Dracula and White Amoled which formerly had a dark colored FAB have a light colored one now, which seems counterproductive for a dark theme (granted, their old colors lacked contrast against the post backgrounds, but that's a different issue). Of course, this is a bit of a https://xkcd.com/1172/ moment, so I would understand if you don't change it back.

**Comment by Docile-Alligator** [comment]
Subtitle changed.
