### ISSUE TITLE
NSFW posts not displaying properly 

### ISSUE THREAD

**Issue by MikaelaMuller** [Docile-Alligator/Infinity-For-Reddit#1520]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.0.2

### Where did you get the app from

F-Droid

### Android version

12 Pixel Experience+

### Device model

Samsung A02s

### First occurred

2 weeks ago

### Steps to reproduce

Go into any NSFW subreddit

### Example post, link, markdown...

![Screenshot_20230716-224903_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/91151184/e954f2e1-925c-4d23-89cc-8e795570f603)

### Expected behaviour

Nsfw post shows up

### Current behaviour

It shows the one on the photo

**Comment by Ultra980** [comment]
It's due to the reddit api changes. There's no way to view nsfw content with 3rd party clients anymore.

**Comment by gmankab** [comment]
maybe there is a way to decompile official app and extract api keys from it?

**Comment by C0deBr3ak3r** [comment]
> maybe there is a way to decompile official app and extract api keys from it?

I saw an app who uses the RSS/JSON feed features to get the messages, maybe this works for NSFW too

**Comment by C0deBr3ak3r** [comment]
But like, I don't think this would be addressed by someone, reddit basically kills 3rd party apps, so don't expect any changes in the app

**Comment by 1RandomDev** [comment]
Couldn't you use something like `GET https://www.reddit.com/r/cumshot.json`? It seems to properly return all posts as json. Even if it's not possible to vote or comment through the API, Infinity could at least show the posts.

**Comment by adhiraj-ranjan** [comment]
You can go anonymous and view NSFW subreddits in the app

**Comment by Felting** [comment]
Make yourself a mod on a sub Reddit then it will work

**Comment by 1RandomDev** [comment]
I have now found this app that pretends to be the official Reddit app and utilizes internal APIs to make content load faster and bypass all API restrictions. https://github.com/KhoalaS/Infinity-For-Reddit

**Comment by Docile-Alligator** [comment]
There is nothing I can do about this.
