### ISSUE TITLE
error loading posts

### ISSUE THREAD

**Issue by fusionneur** [Docile-Alligator/Infinity-For-Reddit#1521]
today, it seems no posts/comments load anymore. after clearing cache, home feed os empty

**Comment by d4rklynk** [comment]
It's because Reddit API policy ahs chanegd on 12th July.
You can read this from Libreddit https://github.com/libreddit/libreddit/issues/840

**Comment by d4rklynk** [comment]
TLDR, it will probably kill Infinity and Libreddit unfortunately

**Comment by Docile-Alligator** [comment]
You will be rate limited if you use anonymous mode too much.
