### ISSUE TITLE
Audio in downloaded video not working

### ISSUE THREAD

**Issue by pufferffish** [Docile-Alligator/Infinity-For-Reddit#1526]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.0.2

### Where did you get the app from

F-Droid

### Android version

Graphene OS Android 13

### Device model

Pixel 6

### First occurred

About a week ago

### Steps to reproduce

1. Download any video with audio
2. Play the video with anything
3. Discover audio is missing

Seems to be caused by this change: https://www.reddit.com/r/redditdev/comments/15cdln3/reddit_changed_what_url_audio_from_a_video_is/

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/c5243ade5647b6a788b6c0a318863caad57a18f7
