### ISSUE TITLE
Some Reddit GIFs Play Slower than Normal

### ISSUE THREAD

**Issue by MetalNeo** [Docile-Alligator/Infinity-For-Reddit#1535]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.1.1

### Where did you get the app from

Google Play

### Android version

13 (GrapheneOS)

### Device model

Google Pixel 5a

### First occurred

Today

### Steps to reproduce

1. Open the app.
2. View an affected GIF/post.
3. Compare the playback speed to the official app/website.

### Example post, link, markdown...

https://www.reddit.com/r/SpyxFamily/comments/zf34bv/made_this_into_a_fluid_looping_gif_because_yes/

### Expected behaviour

Infinity should play the GIF at full speed.

### Current behaviour

Infinity plays some GIFs at a slower speed.

**Comment by Docile-Alligator** [comment]
Fixed https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/af6b92ffa3e28ef56ececa23fa30aef21aa41e98
