### ISSUE TITLE
Colors for dark theme on main screen are broken

### ISSUE THREAD

**Issue by craig872** [Docile-Alligator/Infinity-For-Reddit#1539]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.2.5

### Where did you get the app from

Other

### Android version

13

### Device model

Samsung S21

### First occurred

9/10/2023

### Steps to reproduce

Have an issue with the dark theme. The theme on the main listing of post summaries is off. The background color of the summary "cards" in dark mode seem to be using the color of the light theme (pink) while the text of the cards is still using the dark theme (aka white). Pink on white impossible to read. Light mode is fine but dark mode of the main screen is messed up. Dark mode of an individual post it okay. See attached image.

Don't think this should matter, but I'll mention in case it does...

Used the [guide](https://www.reddit.com/r/Infinity_For_Reddit/comments/14c2v5x/build_your_own_apk_with_your_personal_api_key_in/) written by [AllMFHH](https://www.reddit.com/user/AllMFHH/) to make a build with my own key for version 6.2.5

![Color_Theme_Issue](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/8135394/bdc92e3d-0ed3-4ce0-8e44-564f9baa55de)

### Example post, link, markdown...

See attached image

### Expected behaviour

Cards from the main screen should use the dark background color when in dark mode

### Current behaviour

Cards from the main screen are using the background color from light mode when dark mode is active

**Comment by craig872** [comment]
FWIW... I re-ran the build with the older 6.0.4 version and dark theme colors there are okay

**Comment by ItsRogueRen** [comment]
> 

I'm having the same issue, how did you get the Google Collab script to build an older version?

**Comment by craig872** [comment]
@ItsRogueRen 
One of the script blocks has a `git clone` command.
You can edit those blocks inline before clicking the run button.
At the end of the clone command, add the directive to get one of the older branches `-b v6.0.4`
6.0.4 was the first and only one I tried

**Comment by drishal** [comment]
> @ItsRogueRen One of the script blocks has a `git clone` command. You can edit those blocks inline before clicking the run button. At the end of the clone command, add the directive to get one of the older branches `-b v6.0.4` 6.0.4 was the first and only one I tried

Hi. I am unable to use the -b v___ flag anymore, it says `fatal: unable to access 'https://github.com/Docile-Alligator/Infinity-For-Reddit -b v6.2.3/': URL using bad/illegal format or missing URL` even though I have not added a / at the end of the url string 
```
 !git clone "https://github.com/Docile-Alligator/Infinity-For-Reddit -b v6.2.3
```

**Comment by hasezoey** [comment]
i just ran into the same problem, a quick git bisect leads me to 2342fd06bb5704ceddd63940bef2c8960fcce120 (which is not buildable and i dont know enough to resolve this), and in more detail [this change is the problem](https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/2342fd06bb5704ceddd63940bef2c8960fcce120#diff-d3d73356b5b3868b4547af7672f6fe50755e1d9c30df24d8656a7c91e5081db1R322-R323), because reverting those lines fixes the issue on current latest master

**Comment by Docile-Alligator** [comment]
Please use the latest tag when building Infinity.

**Comment by craig872** [comment]
As of last week 625 was the latest version. Tried older version to see if version change was a contributing factor. It was. Several other users confirm. 

Are you saying there is now a new version where this is resolved?

**Comment by Docile-Alligator** [comment]
I mean you need to use the commit with the latest 625 tag to build infinity. Apparently the 625 public version doesn't have such an issue. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/40d12c3a425914b3f152021eceae914fa4c33586
