### ISSUE TITLE
Sometimes random comments are upvoted when I open a post, even though I didn't upvote them

### ISSUE THREAD

**Issue by PopeRigby** [Docile-Alligator/Infinity-For-Reddit#154]

**Comment by Docile-Alligator** [comment]
Ok. I haven't encountered this problem. But I will look into it.

**Comment by PopeRigby** [comment]
Anything I can do to help diagnose?

**Comment by Docile-Alligator** [comment]
Have you voted for some comments before seeing another comment labeled as upvoted in the same post?

**Comment by PhoenixFlame101** [comment]
I'm having the same issue as well. The comments only appear as upvoted or downvoted (coloured arrows), but they haven't actually been voted on. If you manually vote, the points change as normal and removing your vote gets rid of the issue. Collapsing and un-collapsing

**Comment by PopeRigby** [comment]
No. It always happens when it's my first time opening the post.

**Comment by Docile-Alligator** [comment]
ok. Thanks for the info.

**Comment by PopeRigby** [comment]
I don't think this issue is fixed. It's still happening in the latest beta.
