### ISSUE TITLE
Links shared from Offical Reddit app don't open in Infinity (supported web addresses)

### ISSUE THREAD

**Issue by Gangoke** [Docile-Alligator/Infinity-For-Reddit#1543]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.2.5

### Where did you get the app from

Other

### Android version

13 (OneUI 5.1.1

### Device model

Samsung Galaxy Fold 4

### First occurred

unsure

### Steps to reproduce

1. From external app click Reddit link https://reddit.com/r/Infinity_For_Reddit/s/L9vVOkpKhN

(Links shared from offial Reddit app uses schema: https://reddit.com/r/{{SUBREDDIT}}/s/{{HASH}}  )

### Example post, link, markdown...

Reddit Offical app link: https://reddit.com/r/Infinity_For_Reddit/s/L9vVOkpKhN
Normal Link: https://www.reddit.com/r/Infinity_For_Reddit/comments/147bhsg/the_future_of_infinity/

### Expected behaviour

Link opens in Infinity app

### Current behaviour

Link open is browser

### Notes
I have open supported links and all supported web addresses enabled
Normal Reddit links open Infinity

**Comment by Docile-Alligator** [comment]
Don't know the pattern. Will not support the new links.

**Comment by MichalisSak** [comment]
That is a bummer, I hope you find a way in the future.
