### ISSUE TITLE
Error: Invalid request to 0auth API login issue

### ISSUE THREAD

**Issue by kiiru501** [Docile-Alligator/Infinity-For-Reddit#1545]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.2.3

### Where did you get the app from

F-Droid

### Android version

Android version 13

### Device model

Samsung A53

### First occurred

5 days ago

### Steps to reproduce

Hi,

App was not loading my account. 
Decided to uninstall and install again.
Now unable to log into reddit through infinity.

I  get the error 
Error: Invalid request to 0auth API login issue

Please assist 
![Screenshot_20230917_125014_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/4168690/efd30239-81d9-45be-a490-4bb4ac013df5)

### Expected behaviour

When I log in, I should be able to access my reddit account on infinity 

### Current behaviour

Unable to log in to reddit from infinity

**Comment by Andoriax** [comment]
Ditto. Identical experience; has been like this for a couple weeks now.
I wouldn't be surprised if Reddit and it's corporate partnerships are causing this block discriminatively.

**Comment by Docile-Alligator** [comment]
F-Droid's Infinity does not work anymore since I have already deleted the old API key. Please use Google Play's or find the release apk here.

**Comment by DodoLeDev** [comment]
This error still appears on the github version....
