### ISSUE TITLE
Colortheme not applying for the background of unread Posts

### ISSUE THREAD

**Issue by metzger100** [Docile-Alligator/Infinity-For-Reddit#1546]
### Checklist

- [ ] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
(MAYBE DUBLICATION OF #1519)
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.2.5

### Where did you get the app from

Other

### Android version

13

### Device model

Realme 5 Pro

### First occurred

Today, after updating

### Steps to reproduce

1. I downloaded the new apk with the Google Colab [Infinity APK Builder](https://colab.research.google.com/drive/13AE8RvjnCfuBJGaACEqxeBIMo33_l-Sc?usp=sharing)
2. I opened the App and it was a mess.
2.1. The background of unread posts was pink no matter what changes I made in the Theming Settings
2.2. The background went normal when i activated the post history and the host got the status of read (See pictures)
2.3. It looks fine in the Theme Preview
3. Changing the Material You Theme in the android settings didn't help nor did it change the pink color
4. Tried reinstallation, recompilation, deletion of Cache and Storage. Nothing helped

### Example post, link, markdown...

Theme preview: 
![Screenshot_20230918-231325_Infinity_1](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/62517154/6450bcba-5715-437f-875d-26d3f816dac1)

Post marked as unread: 
![Screenshot_20230918-231053_Infinity_1](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/62517154/a25692d4-d6c6-4377-947d-2fb57b4177d8)

Post marked as read:
![Screenshot_20230918-231101_Infinity_1](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/62517154/46763e27-716f-4aaa-8b4d-5decbd4029f2)

**Comment by DudeGrim** [comment]
Got this exact bug on a manually built app on 78ea14b3ae7d8f769ee869a654390dd376aee50f. Tried everything @metzger100 did on his Step 4 but to no avail. 

Last working that build was 40d12c3a425914b3f152021eceae914fa4c33586. AFAIK as I haven' tried tried to build the commits in between. (Sorry don't have time to check out the changes🙏)

**Comment by metzger100** [comment]
e6dd1c3aacfbb47380b775442e149d1d39f5266e fixed it. Looks like I compiled something, while it was WIP.
