### ISSUE TITLE
titles on the new video player don't have the font style

### ISSUE THREAD

**Issue by idontveapc** [Docile-Alligator/Infinity-For-Reddit#1552]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [ ] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.3.0 beta1

### Where did you get the app from

Other

### Android version

` `

### Device model

``` ```

### First occurred

... when the app got the new player

### Steps to reproduce

1. set a font to titles (or all three).
2. play a video which has a title.
3. the fallback font is used (roboto).

### Example post, link, markdown...

...
any video post.

### Expected behaviour

font style to be used everywhere

### Current behaviour

` `

### Logs

** **

**Comment by jayeshdalvi4692** [comment]
What is the current state of this possible bug, and from where do i change the font for title from, was trying to do the same but coudnt find the option

**Comment by jayeshdalvi4692** [comment]
Thanks, ill let you know if i find the bug on my device, just installed it and going through all of the settings

**Comment by jayeshdalvi4692** [comment]
> > ### change font style
> 
> 1. go to interface.
> 2. then font.
> 3. you would see **Font Family**, choose one. >> _**from the font family option.**_
>    _or_
> 4. choose **custom font family** and choose a font file (.ttf,.otf,.ttc or other maybe).
> 
> > ### current behaviour
> 
> currently the applied font doesn't show up on titles when playing a video.

Yup its definitely a bug, can confirm that font does'nt change on any device i've tested
Also the distance between Settings > Interface top app bar and the " Font " option is a bit less which makes it look like its not a clickable item that should be increased too
