### ISSUE TITLE
Votes count isn't centered

### ISSUE THREAD

**Issue by severtheskyline** [Docile-Alligator/Infinity-For-Reddit#1556]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.3.0

### Where did you get the app from

Other

### Android version

One UI Core, Android 11

### Device model

Samsung Galaxy A02

### First occurred

About 6.3.0 Beta 1

### Steps to reproduce

1. See a post/comment 

### Example post, link, markdown...

![IMG_20231004_205504](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/79670265/008d39a5-4a85-43e9-9a56-ea5852c438cb)

### Expected behaviour

The votes count is in the center of the upvote and downvote of the buttons.

### Current behaviour

The vote is skewed to the left, or to the upvote button.

### Logs

Not necessary.

**Comment by Docile-Alligator** [comment]
It's now centered in v6.4.0-beta1.

**Comment by severtheskyline** [comment]
> It's now centered in v6.4.0-beta1.

Thanks a lot! :D
