### ISSUE TITLE
Downvotes don't change number of votes' color

### ISSUE THREAD

**Issue by severtheskyline** [Docile-Alligator/Infinity-For-Reddit#1557]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.3.0

### Where did you get the app from

Other

### Android version

One UI Core, Android 11

### Device model

Samsung Galaxy A02

### First occurred

About 6.3.0 Beta 1

### Steps to reproduce

1. Downvote a post/comment.

### Example post, link, markdown...

![IMG_20231004_210238](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/79670265/0e914fd2-3793-4784-9950-36dfa50d26e2)
![IMG_20231004_210211](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/79670265/540562ca-40df-424d-8142-ecad014ae6d8)

### Expected behaviour

The number of votes should change to the theme's color for the downvote button when selected, just like when upvoting.

### Current behaviour

The color of number of votes stays grayed when downvotes stay gray.

### Logs

Not necessary.

**Comment by Docile-Alligator** [comment]
This is intended.

**Comment by severtheskyline** [comment]
> This is intended.

Why tho? This with the votes count being offset towards the up vote button, is there any reason for this?
