### ISSUE TITLE
Toolbar Layout of Compact Post Theme was inadvertently altered

### ISSUE THREAD

**Issue by SilverSynch** [Docile-Alligator/Infinity-For-Reddit#1558]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.3.0

### Where did you get the app from

Google Play

### Android version

13

### First occurred

Today, on update to 6.3.0

### Steps to reproduce

1. Change post layout to Compact
2. Observe that the post toolbar layout no longer matches any Post Layout but Card Layout 3

### Expected behaviour

Maintain the same toolbar layout as in other layouts, for example, Card Layout 1, as well as when viewing post details.
![Screenshot_20231005-151431](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/11240087/aacaba48-ca8c-4e5c-ae06-6ea545894bbd)

### Current behaviour

![Screenshot_20231005-150831](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/11240087/a0dddf3b-ea71-4050-8ed5-0c0ea0385136)

This was likely incurred when updating the vote buttons of all layouts for 6.3.0.

After extensively checking all settings related to layouts, I have not found any settings which set the layout of post toolbars.

Fortunately, the problem is only that my muscle memory doesn't match my preferred post layout anymore. The toolbar is still fully functional and all buttons perform their intended actions.

**Comment by Docile-Alligator** [comment]
They are not switched back to the original layout in v6.4.0-beta1.
