### ISSUE TITLE
Login screen reports wrong password while the browser site does not

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#156]
###### something happened and my phone had to go through a factory reset (an actual one this time :P), so this is how i came to encounter this bug.

Version 3.2.0 (from Github) under Android 5.1.1

in the login screen for including a new account, every time i try to login, the Reddit login page always returns an error of wrong password. i have double-checked and changed my password multiple times and so i came to realize that it does not happens at all in the other login page provided by the updated Reddit page.

a workaround which i was thinking of doing would be to try and get the tokens/cookies from the login page and use those in my browser to see if it works to login in the app, but a button or text box is nowhere to be seen on the screen. other than that, i have no idea what the problem could be if not an issue being the page being outdated or something. i don't have a logger right now either.

**Comment by Docile-Alligator** [comment]
Does your password contain some special characters?

**Comment by Wilker-a** [comment]
tried all kinds of combinations, including password lengths

**Comment by Docile-Alligator** [comment]
Ok. One difference between my app and other apps I can think about is that I use setDomStorageEnabled(true) in the login screen. I can build an apk without this enabled and do you want to help me test it yourself?

**Comment by Docile-Alligator** [comment]
I have heard of this problem by only 2 other users so it is hard for me to debug.

**Comment by Docile-Alligator** [comment]
Without this dom storage enabled, users cannot log in if they have 2FA enabled. They need to type their passwords like the following: <password>:<2FA code>.

**Comment by Wilker-a** [comment]
i can test it, sure \^\^

**Comment by Docile-Alligator** [comment]
Thank you! Here it is: https://drive.google.com/file/d/17Dk3GeL6sV_T_8Bigqt3H8XTCsYKTB7D/view?usp=sharing

**Comment by Docile-Alligator** [comment]
This is not a final release for the next version. So when you update the app through the play store and find some problems like crashing, you can reinstall the app.

**Comment by Wilker-a** [comment]
..i am having some issues downloading from Google Drive (even when the download is going, i can't tell if it is actually downloading because of DRMs and weird design by Google \^\^\' i will return here when i get the file :p

**Comment by Docile-Alligator** [comment]
Oh Ok. No problem. Did you open the link in incognito mode?

**Comment by Wilker-a** [comment]
no,  but i have uBlockOrigin set to block everything i didn't give explicit permission to access, although Google won't let me see the file size either way.

btw, i tested it now, and it works fine :3

**Comment by Docile-Alligator** [comment]
Oh, that's good to hear! I will retain this change in the next release!

**Comment by Wilker-a** [comment]
thank you :heart:

**Comment by Wilker-a** [comment]
just a sidenote: in this snapshot i've noticed that the doubletap+drag to manage zooming images was gone and only toggles the zoom between two levels now. is the feature back in this update?

**Comment by Wilker-a** [comment]
i think it is okay to close this issue as fixed. the update was also pushed into the IzzyOnDroid repository and it seems to be working well.

**Comment by Docile-Alligator** [comment]
Done and doubletap+drag to manage zooming images is back.
