### ISSUE TITLE
Found a way to get around the payment screen on Android 12

### ISSUE THREAD

**Issue by MaxMatti** [Docile-Alligator/Infinity-For-Reddit#1563]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

Unknown (have updated since)

### Where did you get the app from

F-Droid

### Android version

12

### Device model

Fairphone 4

### First occurred

When mandatory payments were introduced

### Steps to reproduce

I'm unsure whether I should publicize these as it might lead to missed revenue for the developer(s).

### Expected behaviour

payment screen not skippable (same behaviour as in Android 13)

### Current behaviour

payment screen can be skipped without paying

**Comment by Docile-Alligator** [comment]
Hi, are you using the F-Droid version?

**Comment by Docile-Alligator** [comment]
Thank you. I didn't add a subscription option in the fdroid version so that's why people can access the app. It does not work anymore since I have already changed the API key.
