### ISSUE TITLE
F-Droid 404 Page Not Found

### ISSUE THREAD

**Issue by onkq** [Docile-Alligator/Infinity-For-Reddit#1568]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

-

### Where did you get the app from

F-Droid

### Android version

14

### First occurred

22 Oct

### Steps to reproduce

Infinity has disappeared from F-Droid

**Comment by apprehensions** [comment]
can reproduce..?

**Comment by Stu75e** [comment]
NOTE: The app can no longer login as API keys are not included

app moved to f droid archive repository

**Comment by Docile-Alligator** [comment]
The version on fdroid is not working anymore.
