### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by dkoao** [Docile-Alligator/Infinity-For-Reddit#157]
Hello, I have a few feature requests that you might find interesting:

-Mark edited comments as such.
-Color the votes number accordingly if you upvoted/downvoted a comment and the comment toolbar is hidden.
-Indicate that the votes of a comment are hidden rather than putting them at 1 vote.
-Allow the user to see the link's URL without having to click on it.
-Stop the app from removing every post and replacing it with "Error loading posts" if a user refereshes the page and they're offline. A better approach (in my opinion) would be to show a toast (or something similar) that indicates that loading new content failed without replacing existing content.
-Allow the user to go to other subreddits and users directly. 
-Indicate when a user commets/posts as an admin (by coloring their names or putting some sign).
-Add support for the new Reddit Gallery feature. 
-Add the ability to subscribe to/visit quarantined subreddits.
-Add the ability to visit a subreddit's wiki
-In Amoled Black, the quotation line (not sure how to describe it but it's basically the line that appears when you quote something in a post/comment) is very dark and can't be seen properly. Perhaps a lighter shade is more suitable.
-Add interpretation for Reddit markdown's '#' in sidebars, see /r/linux's sidebar for example.
-Add support for Reddit polls.
-Add supports for seeing the usernames of moderators of a subreddit.
-Add support for messaging mods and users.
-Add support for XKCD links (so that the images can be viewed without opening the browser).

Btw thanks for all the hard work you've put into the app, I've enjoyed using it a lot so far.

**Comment by Wilker-a** [comment]
it will be easier to keep track of the each suggestion if these are posted as individual issues, and it would help new people to see what is already acknowledged to avoid duplicated issues :3

**Comment by JustAnotherStrange** [comment]
I'm pretty sure reddit polls support is impossible due to the Reddit API itself not supporting them :/

**Comment by Docile-Alligator** [comment]
Done:
> -Color the votes number accordingly if you upvoted/downvoted a comment and the comment toolbar is hidden.
-Allow the user to see the link's URL without having to click on it. (You can long press a link)
-Allow the user to go to other subreddits and users directly.
-Indicate when a user commets/posts as an admin (by coloring their names or putting some sign).
-Add support for the new Reddit Gallery feature.
-In Amoled Black, the quotation line (not sure how to describe it but it's basically the line that appears when you quote something in a post/comment) is very dark and can't be seen properly. Perhaps a lighter shade is more suitable.
-Add interpretation for Reddit markdown's '#' in sidebars, see /r/linux's sidebar for example.
-Add support for messaging users.

**Comment by NomarCub** [comment]
Shouldn't this split into several separate feature request? That way people can track the individual issues' progress, and also the devs can see how popular each request is by the votes.
Among these I'm particularly interested in the "visit a subreddit's wiki" and "see the link's URL without having to click on it" feature, but I have no clue when, if ever they're going to be implemented and how many others care.

**Comment by tasmo** [comment]
-Add support for XKCD links (so that the images can be viewed without opening the browser).

That would be very great indeed.

And of course:

> Btw thanks for all the hard work you've put into the app, I've enjoyed using it a lot so far.
