### ISSUE TITLE
Utility bar on comments widens when minimising replies.

### ISSUE THREAD

**Issue by Aspect250** [Docile-Alligator/Infinity-For-Reddit#1574]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.4.0

### Where did you get the app from

Other

### Android version

13 one UI 5.1

### Device model

Galaxy A34

### First occurred

Today

### Steps to reproduce

1. Hide replies to a comment including coloured Guidelines on the side (blue, magenta, teal, yellow)
2. Observe the utility bar widen in length and sometimes clip under other stuff.

### Example post, link, markdown...

Installed/updated through google collab

### Expected behaviour

Utility bar (upvote, sharing, bookmarking, etc.) does not widen

### Current behaviour

Utility bar widens and sometimes clips.
https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102602600/d9071278-c0f9-4ed2-874a-d04bdc0b54d1

**Comment by Docile-Alligator** [comment]
Not a bug.

Settings->Interface->Comment->Show Fewer Toolbar Options Starting From

Just choose a smaller number (less than 5).
