### ISSUE TITLE
buttons are out of screen (unfit), and options are also missing

### ISSUE THREAD

**Issue by idontveapc** [Docile-Alligator/Infinity-For-Reddit#1576]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.4.1

### Where did you get the app from

Other

### Android version

* *

### Device model

* *

### First occurred

i think when the comments and bookmark button’s  position changed

### Steps to reproduce

1. find a comment thread with 4 or more comments in the distinct rows...
2. see the first button half missing and last one completely.

### Example post, link, markdown...

1. ![ResizedImage_2023-11-20_12-40-29_2242](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/122597295/8952422b-2ec4-4d7c-8f02-b71be687662c)
2. 
![ResizedImage_2023-11-20_12-40-59_4804](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/122597295/3025035d-fbda-4130-85c2-0db6d545f017)
3. 
![ResizedImage_2023-11-20_12-41-45_1754](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/122597295/05662b6a-9824-47a0-a717-e0c36c197c99)

### Expected behaviour

buttons should minimize their space as columns change.

### Current behaviour

buttons in comments are spced a lot

### Logs

!?
* * *

**Comment by Docile-Alligator** [comment]
Settings->Interface->Comment->Show Fewer Toolbar Options Starting From

Just choose a smaller number (less than 5).
