### ISSUE TITLE
Trending page broken

### ISSUE THREAD

**Issue by the9655a** [Docile-Alligator/Infinity-For-Reddit#1581]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.5.6

### Where did you get the app from

Google Play

### Android version

11

### Device model

ONEPLUS A6013

### First occurred

(Also the duration of the issue) 2-3 months ago.

### Steps to reproduce

1. Buy or patch infinity for Reddit
2. Open trending page
3. See that the results are stuck and don't change. You will see 2-3 months old trending headlines.

### Example post, link, markdown...

What the page looks like at the moment:

![image](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/149513282/e6d0e9c7-0ca8-4dbc-873d-b83175166055)

### Expected behaviour

Current trending headlines.

### Current behaviour

Old trending headlines from months ago and hasn't changed since then.

**Comment by Docile-Alligator** [comment]
Not a bug. I have removed this page.

**Comment by the9655a** [comment]
What do you mean it was removed? Why?

And it still shows in the latest version.

**Comment by Docile-Alligator** [comment]
Because Reddit now uses an internal API to get trending queries, and no 3rd-party clients can use it.
