### ISSUE TITLE
Image/GIFs don't appear properly in comments

### ISSUE THREAD

**Issue by RowanSkie** [Docile-Alligator/Infinity-For-Reddit#1588]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.5.7

### Where did you get the app from

Google Play

### Android version

Android 10

### Device model

Vivo Y93S

### First occurred

A few days ago

### Steps to reproduce

1. Open a post
2. Check comments with embedded images

### Example post, link, markdown...

1. https://www.reddit.com/r/gmod/comments/18s9p9m/what_is_this_it_started_appearing_in_my_game/
2. https://www.reddit.com/r/TheDigitalCircus/comments/18si0mp/daily_wholesome_delivery_39_pomnis_lost_father/

### Expected behaviour

Show images as is

### Current behaviour

Show them as a bunch of links

**Comment by Docile-Alligator** [comment]
Please update to v6.6.0.
