### ISSUE TITLE
Awarded posts have a fully orange background

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#159]
![doof.png](https://user-images.githubusercontent.com/10854855/87953172-3e774680-ca9a-11ea-8555-f3cc4023f0f1.png)

###### version 4.0.0 as of now, under Android 5.1.1

**Comment by Docile-Alligator** [comment]
I have reverted the color in v4.0.1. You can change this color in theme settings.
