### ISSUE TITLE
User infos can't be viewed

### ISSUE THREAD

**Issue by FrankJeager** [Docile-Alligator/Infinity-For-Reddit#1594]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.6.0

### Where did you get the app from

Other

### Android version

14

### Device model

Samsung Galaxy A52 + Samsung Galaxy Tab S7+

### Steps to reproduce

1. Tap on the name of a reddit user
2. A tooltip appear with the error
3. No user info are shown

### Expected behaviour

The user infos are shown and you can subscribe to that user.

### Current behaviour

No info are shown and you can't subscribe to that user.

**Comment by engdyn** [comment]
Same problem also on 6.7.0

**Comment by Docile-Alligator** [comment]
Sorry, will be fixed soon.

**Comment by FrankJeager** [comment]
Fixed in 6.7.3
