### ISSUE TITLE
Bug: Some Gifs are laggy (with video proof) 

### ISSUE THREAD

**Issue by SkyLord52** [Docile-Alligator/Infinity-For-Reddit#16]
Some Gifs are laggy. As you can see in the video, I watch the same gif on Infinity, and then on Boost. The gif is not laggy on Boost.
https://gfycat.com/nervousnippyangwantibo

**Comment by Docile-Alligator** [comment]
Thank you for your feedback. Could you send the post link so that I can look into it.

**Comment by SkyLord52** [comment]
https://www.reddit.com/r/oddlysatisfying/comments/d4j03x/laser_engraving_on_an_iphone/

It's happened with some other Gifs as well

**Comment by Docile-Alligator** [comment]
Thank you! Maybe I have to change a video link to play. Currently, it plays HLS video if possible to save data usage.
