### ISSUE TITLE
Minor issue: Reply button is covered up by down arrow when scrolled all the way down in comments section

### ISSUE THREAD

**Issue by JustAnotherStrange** [Docile-Alligator/Infinity-For-Reddit#160]
minor issue
![picture](https://user-images.githubusercontent.com/64844168/87967078-49c37580-ca8c-11ea-96ac-d57d5761084b.jpg)

**Comment by Docile-Alligator** [comment]
Ok. I will try fixing this.

**Comment by Wilker-a** [comment]
just adding a bit of an empty space after the last parent comment easily solves this, but in parallel it also gives an easier visual cue for spotting the end of the comments section. :3

**Comment by Docile-Alligator** [comment]
Done
