### ISSUE TITLE
Comment icon under a post is a noticeably different color from the other icons 

### ISSUE THREAD

**Issue by SuperStormer** [Docile-Alligator/Infinity-For-Reddit#1604]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.7.1

### Where did you get the app from

Other

### Android version

14

### Device model

Galaxy S22

### Steps to reproduce

1. Use White Dark theme (I only tested it and Red Dark, but it'll likely be reproducible on other themes as well)
2. View any post

### Expected behaviour

Comment icon should be the same color as the other icons (vote, share, etc) as they share the same color in the theme configuration
![Screenshot_20240127_052824_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/41648788/93f75efe-fa32-4dfd-8eff-5f8ffb8cb539)

### Current behaviour

![Screenshot_20240127_052749_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/41648788/100e7b3b-e670-4892-baa9-2a8627c0cf8c)
The comment icon is noticeably darker than the others.

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/da0135a0344e58b3be368b591e1275d5d8d55f3b
