### ISSUE TITLE
Searching for a subreddit doesn't work in anonymous mode

### ISSUE THREAD

**Issue by SirenGlitch** [Docile-Alligator/Infinity-For-Reddit#1605]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.7.2

### Where did you get the app from

Other

### Android version

11

### Device model

OnePlus 6T

### First occurred

Around v6.7.0

### Steps to reproduce

1. Switch to anonymous mode
2. Search for any query
3. Switch to "Subreddits" tab
4. "Error searching subreddits. Tap to retry"

### Expected behaviour

List subreddits matching search query

### Current behaviour

"Error searching subreddits."
"Tap to retry."

**Comment by robgbc** [comment]
Confirming above issue. 

Searching provides Posts and Users results, but Subreddits gives: Error searching subreddits. Tap to retry.

App version
6.7.1- 6.7.2 Infinity for Reddit+

Where did you get the app from
Play Store

Android version
14

Device model
Pixel 7 Pro

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/4a2a277af9bd81f157b2bdcf6041f3f4343fce09
