### ISSUE TITLE
The latest version still shows "error loading posts" in anonymous mode

### ISSUE THREAD

**Issue by popogomo** [Docile-Alligator/Infinity-For-Reddit#1607]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.7.2

### Where did you get the app from

Other

### Android version

GrapheneOS

### Device model

Pixel 8 Pro

### First occurred

Some time ago

### Steps to reproduce

1. Use the app in anonymous mode
2. It will not show any content nor return search results, and will display "error loading posts" message

### Expected behaviour

The app should work as expected, without the error

### Current behaviour

Shows "error loading posts" message

**Comment by Docile-Alligator** [comment]
Fixed in v6.7.3. It will be available very soon on Google Play. Or if you want to get it now you can download it here: https://github.com/Docile-Alligator/Infinity-For-Reddit/releases/tag/v6.7.3
