### ISSUE TITLE
Clicking on a poll creates an infinite loop

### ISSUE THREAD

**Issue by feedmesource** [Docile-Alligator/Infinity-For-Reddit#1610]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.7.1

### Where did you get the app from

Other

### Android version

13

### Device model

Google Pixel 4a

### First occurred

Today

### Steps to reproduce

1. Open post of **Reddit poll**
2. Click on the "link" of it (because polls are not supported by Infinity)

### Example post, link, markdown...

Try with [this poll](https://www.reddit.com/r/twentyonepilots/comments/1ae7bjo/how_old_are_you/).

### Expected behaviour

Open poll in an in-app browser.

### Current behaviour

Infinitely keeps opening in-app browser windows/tabs on top of one another.

**Comment by Docile-Alligator** [comment]
Do you have chrome or firefox installed?

**Comment by feedmesource** [comment]
The bug doesn't seem to occur anymore.
(by the way, I use mostly Firefox)
