### ISSUE TITLE
Comment thread does not collapse if top comment is a GIF

### ISSUE THREAD

**Issue by PJansky** [Docile-Alligator/Infinity-For-Reddit#1612]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.0.0

### Where did you get the app from

Other

### Android version

14 (GrapheneOS)

### Device model

Pixel 8 Pro

### First occurred

This week

### Steps to reproduce

1. Find a comment thread where the top comment (of the thread/not post) is a GIF (possibly also the case for pictures)
2. Collapse the thread by long clicking it
-> Comment thread does not collapse

### Expected behaviour

The comment thread should collapse like it does with text posts

### Current behaviour

The comment thread does not collapse

**Comment by splat15** [comment]
The gif extends to the right side of the screen even if the content itself doesn't so you are taping on the gif element. Tap on the footer of the comment to collapse it.

**Comment by Docile-Alligator** [comment]
It's not fixable atm.
