### ISSUE TITLE
Missing comments icon in Compact Layout for Posts

### ISSUE THREAD

**Issue by voltaek** [Docile-Alligator/Infinity-For-Reddit#1614]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.0.0

### Where did you get the app from

Other

### Android version

13

### First occurred

after upgrading from v6.3.0 to v7.0.0

### Steps to reproduce

1. Change post layout to Compact Layout

### Expected behaviour

Expected to see a comment icon between the downvote arrow and the number of comments, but it is missing. When going into a post, though, there is a comment icon in this same location as expected.

This issue might be related to the changes made recently in da0135a0344e58b3be368b591e1275d5d8d55f3b.

### Current behaviour

![Screenshot_20240213-150530](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/7809420/453a98a2-987e-4c9f-b147-eb9aa50e93d3)

**Comment by Docile-Alligator** [comment]
Fixed.
