### ISSUE TITLE
False advertising

### ISSUE THREAD

**Issue by JapanYoshi** [Docile-Alligator/Infinity-For-Reddit#1618]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.0.0

### Where did you get the app from

F-Droid

### Android version

11

### Steps to reproduce

Locate the app on the F-Droid app.

### Example post, link, markdown...

https://f-droid.org/packages/ml.docilealligator.infinityforreddit/

### Expected behaviour

The app should state in its description that logging in is a paid feature.

**Note:** I am not telling you to make logging in free. I am telling you to be honest about logging in being paid.

### Current behaviour

The app listing does not have any statement of that sort.

![Screenshot_2024-02-27-22-47-15-17_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/8707990/91f895b7-b288-4c57-9009-2cd195c40708)
![Screenshot_2024-02-27-22-47-22-39_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/8707990/450a728c-a292-4f19-830c-7fe4728f5d9b)
![Screenshot_2024-02-27-22-47-28-63_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/8707990/d6f07558-0feb-4fda-9aac-fc1be36b9d8e)
![Screenshot_2024-02-27-22-47-34-41_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/8707990/7ba030c2-9af8-4cfd-91e5-9d5887b1c34d)

**Comment by Docile-Alligator** [comment]
It's already delisted from fdroid.
