### ISSUE TITLE
There is no login with google account

### ISSUE THREAD

**Issue by SupFlynn** [Docile-Alligator/Infinity-For-Reddit#1620]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.0.2

### Where did you get the app from

Google Play

### Android version

Android 14 (Dr Ketan OneUI update 3)

### Device model

Samsung S24Ultra

### First occurred

Today

### Steps to reproduce

Opening left bar and then pressing on anynomous to login and there is no login with google it doesnt matter how many times i press the question mark on the right down.

**Comment by Docile-Alligator** [comment]
Right. It's because Infinity uses a webview to show the login page.
