### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kgoerbig** [Docile-Alligator/Infinity-For-Reddit#163]
Any chance a backup feature can be added to be able to backup settings?

**Comment by Docile-Alligator** [comment]
I think google drive can automatically backup your apps. I don't have a server so I can't add backup settings.

**Comment by neodada** [comment]
> I think google drive can automatically backup your apps. I don't have a server so I can't add backup settings.

Local backup?

**Comment by Docile-Alligator** [comment]
This is added in v4.3.0-beta1.
