### ISSUE TITLE
reddit.com/media links handled incorrectly

### ISSUE THREAD

**Issue by starchyunderscore** [Docile-Alligator/Infinity-For-Reddit#1636]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.0.0

### Where did you get the app from

Other

### Android version

13

### Device model

Moto G Stylust 5g 2022

### First occurred

first noticed 2 weeks ago

### Steps to reproduce

1. click a reddit.com/media link
2. be redirected to [this post](https://www.reddit.com/r/funny/comments/media/nice_hat/) instead of the correct media

### Example post, link, markdown...

this comment: https://www.reddit.com/r/HFY/comments/18ljist/dungeon_life_179/kdylz6q/

should link to this: https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2F9iamzovpcrta1.png%3Fwidth%3D720%26auto%3Dwebp%26s%3Da6d1287094fc6ad986e1245a5fc3869b2f0c7da4

![Screenshot_20240415-220951](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102399926/c3d57c75-2e42-4a87-a8f9-883f78372760)

but instead links to this: https://www.reddit.com/r/funny/comments/media/nice_hat/

![Screenshot_20240415-221051](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102399926/1ba3875e-f7a6-4381-8476-bd0e54c923e1)

### Expected behaviour

reddit.com/media links show intended media

### Current behaviour

reddit.com/media links redirect to this post: https://www.reddit.com/r/funny/comments/media/nice_hat/

**Comment by Docile-Alligator** [comment]
Is this only for image or is video also possible?

**Comment by starchyunderscore** [comment]
if you're asking for a video of the bug:
https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/102399926/6ae052ec-cc3a-4787-ae40-cfefbf813781


if you're asking for an example of a video `reddit.com/media` link: i don't know. i've only ever seen ones for images and i don't know how to make them
