### ISSUE TITLE
Backup feature missing comment filters

### ISSUE THREAD

**Issue by Kotaless** [Docile-Alligator/Infinity-For-Reddit#1640]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.1.1

### Where did you get the app from

Google Play

### Android version

14

### Steps to reproduce

1. Advanced->Backup Settings
2. Wipe the app's data or reinstall
3. Advanced->Restore Settings

### Expected behaviour

Comment filters restored correctly.

### Current behaviour

Comment filters not restored.

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/e666e6774e87fcaeb0405ee5bca941928af7dee6
