### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by tempneq2000** [Docile-Alligator/Infinity-For-Reddit#1645]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

6.3.1

### Where did you get the app from

F-Droid

### Android version

14 (LineageOS 21)

### Device model

Moto Edge 40 Pro

### First occurred

Today

### Steps to reproduce

Originally no account was saved, then I logged in a new account. Additional info: the account was newly created, not sure if it's any related to this.

### Expected behaviour

Successful login and redirection

### Current behaviour

Stuck in this page and no redirection occured. When swiped back, the account was not logged in.
![Screenshot_20240515-192357_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/169739874/43e28a7c-8da9-4046-858e-9ef99c335ef9)

**Comment by edgan** [comment]
https://old.reddit.com/r/revancedapp/comments/1d4d4ea/did_reddit_break_third_party_apps_dev_token_patch/l6divr5/
