### ISSUE TITLE
Proprietary components added with v0.4.0

### ISSUE THREAD

**Issue by IzzySoft** [Docile-Alligator/Infinity-For-Reddit#1649]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

0.4.0

### Where did you get the app from

Other

### Android version

n/a

### Device model

n/a

### First occurred

with this version

### Steps to reproduce
The library scanner reports:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

4 offenders.
```

Not sure if those were added intentionally, or whether some dependency dragged them in – but they are proprietary and should not be there. Can you please take a look? Thanks in advance!

**Comment by Docile-Alligator** [comment]
There is no v0.4.0 version I think?

**Comment by IzzySoft** [comment]
Wait… what's going on there then? I usually have a complete block to post in such cases – but if there's no "simple issue" have to split up things, so parts of the block are missing. 2 weeks ago, now if I still remember… Let me check the logs here…

Oof. That day has just the `usesCleartextTraffic` for this app. Looks like the logs got messed up when cron sent them. Taking a closer look at what other apps were processed around the time, I find another one that seems to match the above, as the updater yielded the need to add the related anti-features. And yupp, that one matches with v0.4.0…

Apologies then, looks like I barked at the wrong tree :see_no_evil:
