### ISSUE TITLE
[Feature Request] Line style comment indentation

### ISSUE THREAD

**Issue by BlitW0** [Docile-Alligator/Infinity-For-Reddit#165]
I like the way comments are indented in the official reddit app. Can you add line indentation to infinity? Maybe an option in settings to choose between color coded indentation and line indentation? (Boost has this)

**Comment by Docile-Alligator** [comment]
I will try. But i will add other features first.

**Comment by Docile-Alligator** [comment]
This is now available in v4.3.0-beta1.
