### ISSUE TITLE
The app is stopped working today 

### ISSUE THREAD

**Issue by MoonWalker440** [Docile-Alligator/Infinity-For-Reddit#1654]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

1.1.1

### Where did you get the app from

Other

### Android version

A13

### Device model

Vivo Y28

### First occurred

Today 

### Example post, link, markdown...

![Screenshot_20240531_092421](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/155570047/b915c68e-ef6f-4c27-b1e3-36d9351964a4)

### Current behaviour

It giving 404 error from today. Can't see any post neither any subreddits

**Comment by candroid-man** [comment]
It's happening again

**Comment by mario-g98** [comment]
> It's happening again

Yes, nothing is loading.

**Comment by JoshuaKimsey** [comment]
Yeah, this needs to be reopened, cause it's not been working since yesterday for me. And reinstalling and repatching aren't solving it. So not sure what's up.

**Comment by candroid-man** [comment]
Still not able to access Reddit

**Comment by JoshuaKimsey** [comment]
I discovered that you need to roll back to version 7.2.1 to get it to work properly again after patching with Revanced.
