### ISSUE TITLE
Long press to collapse comment tree not working on image comments

### ISSUE THREAD

**Issue by Araxeus** [Docile-Alligator/Infinity-For-Reddit#1655]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.2.3

### Where did you get the app from

Other

### Android version

MIUI 14 (android 13)

### Device model

POCO F3

### First occurred

Since support for inline image comments was added

### Steps to reproduce

1. Find a comment that has an embedded image 
2. Long press to collapse comment tree 

### Example post, link, markdown...

https://www.reddit.com/r/interestingasfuck/comments/1d4jbs5/a_flamingo_couple_feeding_its_young/l6eydu5/

### Expected behaviour

Comment tree collapse

### Current behaviour

Nothing happens

**Comment by Docile-Alligator** [comment]
Not fixable right now. Sorry.

**Comment by Araxeus** [comment]
Kinda weird to close issues as completed without fixing them but ok. Thanks for all your work :)
