### ISSUE TITLE
[Bug] Font preview for last 3 font families not shown in settings

### ISSUE THREAD

**Issue by BlitW0** [Docile-Alligator/Infinity-For-Reddit#166]
In settings  > interface > font > font preview, font preview is not shown for all fonts after Inter Bold. Maybe you could add the font preview directly into the font family selection popup?

**Comment by Docile-Alligator** [comment]
I think I forgot to make the page scrollable so they are hidden. Showing font preview directly in the popup is very hard, if not impossible, under current implementation.

**Comment by BlitW0** [comment]
Fixed in v4.0.7.
