### ISSUE TITLE
Emojis are shown in spoiler text

### ISSUE THREAD

**Issue by engdyn** [Docile-Alligator/Infinity-For-Reddit#1669]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.2.4

### Where did you get the app from

Other

### Android version

14 (custom ROM YAAP)

### Device model

OnePlus HD1903

### First occurred

Today

### Steps to reproduce

1. Open a post with an emoji inside a spoiler
2. Look at the spoiler 

### Example post, link, markdown...

https://www.reddit.com/r/HolUp/comments/1dgn0z8/how_are_you_going_to_come_back_from_this/l8qy2sc/

### Expected behaviour

The whole text including the emojis are hidden

### Current behaviour

The emojis are shown even though the text is hidden
![Screenshot_20240615-231540_Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/48772915/48899897-3644-4949-bc91-f6303d8afbc4)

**Comment by Docile-Alligator** [comment]
Not fixable
