### ISSUE TITLE
New layout suggestion

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#167]
Hi,

I love infinity, but find the interface quite cluttered. I made some examples of a less clutered interface. Furthermore, I use reddit without account ("anonymously"), but there are many buttons (like upvote, downvote, comment) always visible. These buttons are useless to me, since I cannot use them anyway. I think most of the buttons can either be placed under a 3 dots menu or be shown using a long press.

Original post:
![Post layout](https://user-images.githubusercontent.com/50382414/88466649-c6ac8000-cece-11ea-919d-6b1d893bbc55.png)

Decluttered post:
![Post layout2](https://user-images.githubusercontent.com/50382414/88466652-cf04bb00-cece-11ea-8671-2f16f5325ce2.jpg)

Original overview:
![Overview](https://user-images.githubusercontent.com/50382414/88466657-dc21aa00-cece-11ea-9253-e3ce9cfdfa67.jpg)

Decluttered overview (without upvote counter):
![overview6](https://user-images.githubusercontent.com/50382414/88466675-1428ed00-cecf-11ea-8181-151fc3b2f51b.jpg)

Decluttered overview (with upvote counter):
![overview4](https://user-images.githubusercontent.com/50382414/88466659-e2178b00-cece-11ea-889e-246384376b79.jpg)

**Comment by Docile-Alligator** [comment]
Thank you. I will add more features before implementing customizations.

**Comment by Donkey-Doug** [comment]
I also created this list of the changes in the pictures. I don't think making a seperate issue for each is useful:

- Option to show/hide the tags
- Option to show/hide the awards
- Option to show/hide the URL
- Option to show/hide the username of the poster
- Option to show/hide the subreddit logo
- Option to move content type label inside photo/video/gif
- Option to show/hide actions (upvote, downvote, bookmark & share)
- New time format: Only date and no timestamp

**Comment by Donkey-Doug** [comment]
I also think the location of the upvote counter in the picture below is quite nice. In this way each new title is indented, just like a paragraph. This makes post divider lines unnecessary.

![afbeelding](https://user-images.githubusercontent.com/50382414/88729356-f7d9ba00-d133-11ea-928a-39ca55554c0f.png)

(this screenshot is from the reddit app "Dawn")

**Comment by Docile-Alligator** [comment]
Nice suggestions!

**Comment by Wladefant** [comment]
Almost everything is implemented, if you want the feature request with the comment count please make a separate request for it
