### ISSUE TITLE
Make post text primary

### ISSUE THREAD

**Issue by BlitW0** [Docile-Alligator/Infinity-For-Reddit#168]
Currently the text in text posts is secondary for some reason, which makes it harder to read sometimes. Making it secondary for previewing in feed makes sense but when opening the post it should be primary.

This also can't be fixed by theming, since various other parts of the app with secondary text get converted to primary if you try to make post text look like primary text by making colors same for both primary and secondary texts.

**Comment by Docile-Alligator** [comment]
The color of post text is controlled by Post Content Color, not Secondary Text Color.
