### ISSUE TITLE
Videos fail to play on feed

### ISSUE THREAD

**Issue by Generator** [Docile-Alligator/Infinity-For-Reddit#1680]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

7.2.8

### Where did you get the app from

Other

### Android version

14 (crDroid 10.5)

### First occurred

since v7.2.8

### Steps to reproduce

1. Enable video autoplay
2. Scroll feed, any video subreddit or post details

### Example post, link, markdown...

https://www.reddit.com/r/funny/comments/1dr09qm/voicemails_in_the_2000s/

### Current behaviour

When scrolling the feed or posts detail videos fail to play.  
Video play without issue on fullscreen.

https://github.com/Docile-Alligator/Infinity-For-Reddit/assets/44146/046fb353-6226-462c-a6d8-2268ddd2115a

**Comment by evanc577** [comment]
Confirming this issue with 7.2.8, reverting commit 5a1b67f599bc95b9f04d06cc7f22cc65994995f0 fixes the issue.

**Comment by zoreex** [comment]
7.2.8 - android 9 & android 12 - for me only accurs on NSFW tagged videos - using self-built with api key after following the reddit thread

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/fccf2c57851f3b3f6e3b7e67e34699d945a48234
