### ISSUE TITLE
Tab customization not working

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#169]
Hi,

Tab customization of the tabs on the main page isn't working for me. Changing the title or type has no effect at all.

**Comment by Docile-Alligator** [comment]
Have you restarted the app?

**Comment by ghastlybespoke4** [comment]
I am experiencing a similar issue when trying to make a custom tab for my multireddit.
Neither restarting nor reinstalling the app seems to fix the issue for me.
This is occurring on Version 4.0.1.
[Custom Setting for Multireddit.](https://imgur.com/gallery/PBBilsg)
[Nothing Showing up in custom tab](https://imgur.com/gallery/7cJDKNP)
[Multireddit name](https://imgur.com/gallery/5K98hXN)

From what I could see in the source code is that `ml.docilealligator.infinityforreddit.R` seems to have either been renamed or is missing.

**Comment by Docile-Alligator** [comment]
I cannot find your username. Maybe your username is wrong? Can you see the posts from Programming_Subs by going to multireddit listing page?

**Comment by ghastlybespoke4** [comment]
My username does not show up when using the Reddit search bar. This is not due to any privacy settings as "Content visibility" and "Show up in search results" is turned on. https://www.reddit.com/user/Merry_Macabre/
I have copied my username from my mobile browser and the issue persists.
I am still able to [access](https://imgur.com/gallery/MQRrjoJ) my multireddits through the multireddit listing page without any issues.

**Comment by Donkey-Doug** [comment]
> 
> 
> Have you restarted the app?

Restarting does not help. I even uninstalled the app once and it did not help. 

OS: Lineage OS 17.1 (without google play services or microg)
Infinity: Version 4.0.1

**Comment by Docile-Alligator** [comment]
Have you changed your multireddit name before? Actually you need to use your multireddit id, not name, but if you haven't changed your multireddit name, the id is the same as the name. Another possibility: your multireddit name contains _, so the id may not be the same as the name.

**Comment by ghastlybespoke4** [comment]
This seems to have fixed the issue. I just copied the string after the reddit.com/ when visiting my multireddit on desktop and the multireddit showed up in the custom tab. The issue was the underscore ( _ ) which was in the name but not the multireddit id.

Thank you.

**Comment by Docile-Alligator** [comment]
You are very welcome.
