### ISSUE TITLE
Video/Image download don't work with (local) VPN enabled

### ISSUE THREAD

**Issue by Generator** [Docile-Alligator/Infinity-For-Reddit#1690]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

v7.3.0-beta1

### Where did you get the app from

Other

### Android version

Android 14

### First occurred

v7.3.0-beta1

### Steps to reproduce

1. Install/enable any (local) VPN (Ex: Intra (DNS-over-HTTPS client) https://f-droid.org/en/packages/app.intra/)
2. Download any video or image

### Example post, link, markdown...

any video or image post

### Current behaviour

When using a (local)  VPN Infinity only shows a toast notification, but download doesn't start until any VPN is disabled or the app is excluded (if possible ) from VPN app.

Tested with Intra, Proton VPN, Tailscale.

**Comment by allentown521** [comment]
same here：
https://github.com/Docile-Alligator/Infinity-For-Reddit/issues/1699

**Comment by Corbachini33** [comment]
Same problem on 7.3.1

**Comment by Corbachini33** [comment]
Fixed on 7.3.2

**Comment by Docile-Alligator** [comment]
Fixed. https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/61f48554992ebec15add0b27aa0cf4be2dde5275
