### ISSUE TITLE
Option to hide a post without having to open it

### ISSUE THREAD

**Issue by matosjoaops** [Docile-Alligator/Infinity-For-Reddit#174]
I think it would be useful to have the ability to hide a post while scrolling through a "feed" (not sure if this is the correct term). Perhaps adding a button between the upvote/downvote buttons and the ones used for sharing, saving, etc.

**Comment by Docile-Alligator** [comment]
Do you mean hide the post using reddit api or hide the post in the app?

**Comment by MechJM** [comment]
@Docile-Alligator It would probably be better to use the Reddit API

**Comment by regaldude** [comment]
Are there any updates on this?

**Comment by Wladefant** [comment]
this function is implemented: settings>interface>post history>mark posts as read on scroll
