### ISSUE TITLE
[Bug][Minor] The 'see removed comment' feature shows up even when someone comments '[removed]' instead of just when a comment is actually removed.

### ISSUE THREAD

**Issue by PhoenixFlame101** [Docile-Alligator/Infinity-For-Reddit#178]

**Comment by OHermesJunior** [comment]
Yeah.. That's how it "detects" deleted comments. I don't know any other way of doing so.

**Comment by PhoenixFlame101** [comment]
You could use that as a primary check and then try and fetch the commenter's username (which shouldn't work if the comment was actually deleted).

**Comment by OHermesJunior** [comment]
I believe there is cases where the comment is deleted but the username stays, maybe I am mistaken. There is a lot of corner cases, all the combinations of text and username deleted, and the difference between "removed" and "deleted" which I am pretty sure is when a mod and the user themselves deletes it, respectively.
