### ISSUE TITLE
[Feature] Streamable links in app

### ISSUE THREAD

**Issue by jenabaivab** [Docile-Alligator/Infinity-For-Reddit#179]
Is there any way to make the streamable.com videos play inside the application like v.reddit videos?

Also, no. of replies written on the right when the comment is collapsed?

A lot of thanks for creating this beautiful application!

**Comment by Docile-Alligator** [comment]
Thank you. I checked the streamable.com API before and it seems I need to pay to use it. I haven't found a good place to show the no. of replies.
