### ISSUE TITLE
Infinity crashes when loading the comments of some posts

### ISSUE THREAD

**Issue by PopeRigby** [Docile-Alligator/Infinity-For-Reddit#180]

**Comment by austinhuang0131** [comment]
Same here. Stacktrace:

![Screenshot_20200826-170117](https://user-images.githubusercontent.com/16656689/91356541-d533d300-e7bd-11ea-8093-a9853d050e7c.png)

**Comment by austinhuang0131** [comment]
fixed on newest Play release
