### ISSUE TITLE
[Bug] [Minor] Markdown tables broken

### ISSUE THREAD

**Issue by BLANK-TH** [Docile-Alligator/Infinity-For-Reddit#181]
Markdowns tables show the raw text instead of an actual table.

Also if you note the bottom footer, it still shows the \^\^ from the superscript markdown (which shouldn't be there).

![Screenshot_20200830-104344.png](https://user-images.githubusercontent.com/58491821/91662022-c7c46480-eaad-11ea-9323-9962fca1c9c9.png)

**Comment by Docile-Alligator** [comment]
This app doesn't render tables in comments. I will add an option to render them on another page.

**Comment by BLANK-TH** [comment]
I see, that'll work, thanks.

**Comment by Docile-Alligator** [comment]
This will be available in the next update.
