### ISSUE TITLE
[Bug] [Minor] Single comments won't collapse.

### ISSUE THREAD

**Issue by DanHakimi** [Docile-Alligator/Infinity-For-Reddit#185]
I have the "fully collapse comment" option on, so that when I collapse a comment chain, the main comment collapses too.

However, when there are no replies to a comment -- when it's just one single comment -- that comment won't collapse. Some comments are long, so I like collapsing them. This would be nice.

**Comment by Docile-Alligator** [comment]
This will be available in the next update.
