### ISSUE TITLE
[Bug][Minor] Preview thumbnail images do not show in subreddits

### ISSUE THREAD

**Issue by dchoi87** [Docile-Alligator/Infinity-For-Reddit#186]
When viewing a subreddit, preview thumbnail images do not show for links to articles, streamables, etc. However, if you click on a post with a link, then refresh from 3 dot menu, preview loads.

Example:
![infinity-reddit-bug](https://user-images.githubusercontent.com/20117685/92335874-2199d100-f050-11ea-9f9e-bfe2d36696e4.jpg)

**Comment by Docile-Alligator** [comment]
This is because Reddit returns different post data when getting the posts in a list or fetching comments.

**Comment by Docile-Alligator** [comment]
Fixed.
