### ISSUE TITLE
Infinity has a global comment sort setting that overrides per-thread defaults. This is straight up wrong.

### ISSUE THREAD

**Issue by DanHakimi** [Docile-Alligator/Infinity-For-Reddit#188]
Every time I change the comment sort for a thread, it makes the change globally for all new threads I open. Infinity never seems to use the default sort for that thread -- this is annoying, as some threads should really be sorted by new, such as the daily simple questions megathread on /r/malefashionadvice. But if I skip between new and best, I'm frequently going to forget to switch back to the right one, and even if I develop the habit...That's annoying, I don't want to do that. Additionally, I sometimes switch to controversial for fun, but I only ever do that one thread at a time -- it would be terrible as a global default.

There shouldn't be a global sort default. Infinity should always ask reddit what the default for a given thread should be.

(As a side note: I'm loving Infinity, and I think that, after eking out a few bugs and adding a few small features, it'll just blow Sync and others out of the water).

**Comment by Docile-Alligator** [comment]
This will probably be available in the next update.

**Comment by Docile-Alligator** [comment]
4.1.0-beta now has this feature.

**Comment by DanHakimi** [comment]
Aww, did this one not make it in? =(

**Comment by Docile-Alligator** [comment]
Settings->Miscellaneous->Respect Subreddit Recommended Comment Sort Type

**Comment by DanHakimi** [comment]
Ah, thank you! I do think this should be the default functionality, but I'll leave that to your discretion.

Now, the only odd note that remains... The title at the top is bugged to still display the last sort manually selected, and not the sort type actually in use.

**Comment by DanHakimi** [comment]
Sorry, it appears this feature is not working. I'm not sure why it broke, but I have this feature on and it still isn't working for me.
