### ISSUE TITLE
[Feature Request] Show only NSFW

### ISSUE THREAD

**Issue by PinkDev1** [Docile-Alligator/Infinity-For-Reddit#189]
Since "disable NSFW" is already a thing, this feature should not be hard to implement at all.
Would really apreciate this ♥

**Comment by PinkDev1** [comment]
For future readers: TIL you can tap on the NSFW tag and it'll show you only NSFW post of the subreddit the post was in.

You can also write "NSFW:yes" on the search bar and only see NSFW posts on whichever subreddit/profile you searched for.

But filtering only NSFW on the main tab or multireddits with a quick settings option would still be nice ^^

**Comment by Docile-Alligator** [comment]
This will be available in v4.2.0.
