### ISSUE TITLE
[BUG]Blinking images while swiping up/down to dismiss.

### ISSUE THREAD

**Issue by ostsage** [Docile-Alligator/Infinity-For-Reddit#190]
Just like in the title. I'm running android 9 stock device, with 3rd party app to gestures navigation and hidden 3 button default navigation bottom bar (if that's the case).
[Video of described issue.](https://streamable.com/yxafe7) 
Edit: I checked if restoration of original navigation changes anything, and turns out that shutter stayes the same.

**Comment by Docile-Alligator** [comment]
This happens to my chromebook too. Not sure why but I will look into it.

**Comment by Docile-Alligator** [comment]
This is related to the swipe-to-dismiss library.
