### ISSUE TITLE
Allow adding the current sub to an existing multi 

### ISSUE THREAD

**Issue by daraul** [Docile-Alligator/Infinity-For-Reddit#192]
Sometimes I'll stumble on a sub, and want to add it to some multi. Being able to long press the subscribe button make sense to me for this. It would open up a menu with options to add/remove the sub from some multi. This might be in the form of a list of toggles for each multi, perhaps.

**Comment by Docile-Alligator** [comment]
Oh that's a good idea.

**Comment by Docile-Alligator** [comment]
Will be available in v4.2.0-beta2.
