### ISSUE TITLE
Bug? Polls don't open

### ISSUE THREAD

**Issue by s-goryan** [Docile-Alligator/Infinity-For-Reddit#195]
When I click on a poll, it says “No browser found” but I have browsers installed. :-/
 ![Screenshot_20201001-184047_Infinity.jpg](https://user-images.githubusercontent.com/53832230/94831824-d8059180-0415-11eb-8641-1f3f66c193fb.jpg)

**Comment by Docile-Alligator** [comment]
Do you have Chrome or Firefox installed?

**Comment by s-goryan** [comment]
> Do you have Chrome or Firefox installed?

I have Chrome, but it's disabled because I don't like it. I use Naked Browser and I also have default samsung browser (not sure how it's called).

**Comment by Docile-Alligator** [comment]
This app uses Chrome or Firefox to open Chrome Custom Tabs. I will add an option to open links in a webview in the future though.

**Comment by StorageB** [comment]
I have enabled chrome, reset Infinity for Reddit (cleared storage and cache), and restarted phone but I still get the no browser found message when clicking on a poll.

Example post:

https://www.reddit.com/r/test/comments/jnz5ty/test_poll/

**Comment by Docile-Alligator** [comment]
Fixed in 4.1.0-beta. @StorageB
