### ISSUE TITLE
[Suggestion] Color Comment vote totals when comment toolbar is hidden

### ISSUE THREAD

**Issue by DanHakimi** [Docile-Alligator/Infinity-For-Reddit#196]
When you vote on a thread or expanded comment, the color of the vote total changes to indicate which way you voted. When the toolbar is hidden, the point total is visible at the top of the comment, but it's always gray, no matter how you've voted. I know this seems mall, but since I have the toolbar hidden by default, it would improve my experience.

**Comment by Docile-Alligator** [comment]
oh. Nice suggestion.

**Comment by Docile-Alligator** [comment]
Done.
