### ISSUE TITLE
[Suggestion] Implement Chat feature

### ISSUE THREAD

**Issue by SOI7** [Docile-Alligator/Infinity-For-Reddit#198]
Loving the app so far, it's a huge step ahead the official app, but there is a feature that keeps me going back and forth between it and Infinity, which is the Chat function. I know Infinity relies on the mobile site, which doesn't support Chat, but you can actually access the Chat section from mobile as well using https://old.reddit.com/chat/
Not sure if you can switch agent and make the Chat available in a dedicated section using old.reddit, but I'm sharing this here just in case

**Comment by Docile-Alligator** [comment]
Thank you. I need to check how to save cookies in-app first so that users don't need to log in every time.

**Comment by KaKi87** [comment]
Hello, where has this feature been implemented ? Thanks
