### ISSUE TITLE
Feature Request: F-Droid Listing

### ISSUE THREAD

**Issue by sturmen** [Docile-Alligator/Infinity-For-Reddit#2]
Hi there, so glad to see another open source Reddit client! I would like to humbly request that you add your app to the libre app store F-Droid. A quick start guide on how to submit can be found [here in the F-Droid documentation](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide). Thanks again and keep up the great work!

**Comment by Docile-Alligator** [comment]
Thank you! I will.

**Comment by Docile-Alligator** [comment]
https://github.com/Docile-Alligator/Infinity-For-Reddit/issues/21#issuecomment-585065554

IzzySoft has already included this app in the F-Droid repo.
