### ISSUE TITLE
images in image view are very smol

### ISSUE THREAD

**Issue by mintyleaf** [Docile-Alligator/Infinity-For-Reddit#201]
![Screenshot_20201015-004650_Infinity](https://user-images.githubusercontent.com/17470408/96049542-d958a480-0e80-11eb-956b-60a3e1664293.png)
![Screenshot_20201015-004658_Infinity](https://user-images.githubusercontent.com/17470408/96049563-deb5ef00-0e80-11eb-87e2-e81f4b15c241.png)
as u can see, the image opens very very smol
I encountrred this on official app and here too

(on boost client images opens up properly)

**Comment by tegutistgut** [comment]
This is because it's a link.
You are viewing the image from the link (I guess the preview image from that website.)

It shouldn't be a big problem, but it should be fixed with a low priority IMO

**Comment by mintyleaf** [comment]
> This is because it's a link.
> You are viewing the image from the link (I guess the preview image from that website.)
> 
> It shouldn't be a big problem, but it should be fixed with a low priority IMO

no, this is happens with literally all images

**Comment by tegutistgut** [comment]
Then idk. Sorry
You should maybe send a log file and we have to wait for the dev to fix it.

**Comment by Docile-Alligator** [comment]
You can try installing 4.1.0 beta from Google Play after you join the beta program to see if it fixes this problem.

**Comment by Docile-Alligator** [comment]
Fixed.
