### ISSUE TITLE
Same Contents after Reloading

### ISSUE THREAD

**Issue by golfben** [Docile-Alligator/Infinity-For-Reddit#204]
Love this app. There's one big issue that keeps me away from using this as replacement for my current app:
Every time I reload the "Home > Best"-Tab, I get the same contents again and again. I don't have this behaviour in the official app: already read post do not appear here after reloading.

**Comment by tegutistgut** [comment]
You have to activate a setting. Idk what it's called, but when you activate it, the posts will refresh

**Comment by golfben** [comment]
> You have to activate a setting. Idk what it's called, but when you activate it, the posts will refresh

Thanks for your answer. I was looking for this feature in the app settings - couldn't find it though

**Comment by tegutistgut** [comment]
When I'm back home, I will look for it. (If I don't forget it)

**Comment by Docile-Alligator** [comment]
Just enable Save Scrolled Position in HOME in settings or settings->Miscellaneous.
