### ISSUE TITLE
Inbox notifications ?

### ISSUE THREAD

**Issue by KaKi87** [Docile-Alligator/Infinity-For-Reddit#205]
Hello,

Infinity settings indicate that notifications are enabled, but I never received any, yet inbox is working but I have to check it manually ?

Thanks

**Comment by Docile-Alligator** [comment]
You can join in the beta program and install the latest beta which fixes notification.

**Comment by KaKi87** [comment]
Thanks, I actually did tried to join the beta program, Google Play says it's a matter for minutes, and it usually does, but it's been stuck for days now... :/

**Comment by KaKi87** [comment]
Hello, I got beta access by then, however still no inbox notifications.
