### ISSUE TITLE
[Bug][Minor] Time Format doesn't apply to some dates

### ISSUE THREAD

**Issue by Hirame1** [Docile-Alligator/Infinity-For-Reddit#206]
I found Time Format doesn't apply to some dates in the Infinity (version 4.0.7).

1. "Since:" in subreddit header.
2. "Cake day:" in Profile header.

![Screenshot_20201024-104623_Infinity~2](https://user-images.githubusercontent.com/56225774/97067390-117d8700-15e7-11eb-8631-2207eef01dea.png)

**Comment by Docile-Alligator** [comment]
Thanks for reporting this.
