### ISSUE TITLE
button placement in 4.1.0 beta2

### ISSUE THREAD

**Issue by sav1tarr** [Docile-Alligator/Infinity-For-Reddit#207]
in parent comment, there are no three dots to copy, see deleted comment
in child comment, the three dots are placed way too close to the save comment ton and caused accidental presses

**Comment by Docile-Alligator** [comment]
Someone has posted this issue in the subreddit. Thanks for reporting it.

**Comment by Docile-Alligator** [comment]
Fixed on 4.1.0-beta5.
