### ISSUE TITLE
Extremely tall notch offset

### ISSUE THREAD

**Issue by byhemechi** [Docile-Alligator/Infinity-For-Reddit#208]
As far as I can tell it's exactly 2* as tall as it should be.

![overcompensating for something?](https://user-images.githubusercontent.com/25940563/97250504-375e9200-185a-11eb-9b91-8b48a2f56341.png)

**Comment by Docile-Alligator** [comment]
You can join in the beta program and install the latest beta which fixes immersive interface on Android 11.
