### ISSUE TITLE
Top bar spacing is extra in android 11

### ISSUE THREAD

**Issue by muthu-25** [Docile-Alligator/Infinity-For-Reddit#209]
Top bar spacing is too much on Android 11
![Screenshot_20201031-130714_Infinity](https://user-images.githubusercontent.com/68727855/97774004-54f16b80-1b7a-11eb-83a6-0dae58bd9b28.png)

**Comment by Docile-Alligator** [comment]
You can join in the beta program and install the latest beta which fixes immersive interface on Android 11.
