### ISSUE TITLE
Deep comments don't show

### ISSUE THREAD

**Issue by iTrooz** [Docile-Alligator/Infinity-For-Reddit#210]
Deep comments (reponses of reponses of responses....) don't show in app.
See https://www.reddit.com/r/Minecraft/comments/jm8mc3/mobs_do_not_spawn/ (compare in website and Infinity)

**Comment by Docile-Alligator** [comment]
Thank you for reporting. I will look into it.

**Comment by NomarCub** [comment]
The link loads fine for me with the latest version. Can this be closed?

**Comment by iTrooz** [comment]
It is indeed. Thanks !
