### ISSUE TITLE
Some videos won't play when opened from the posts view

### ISSUE THREAD

**Issue by stokholm** [Docile-Alligator/Infinity-For-Reddit#211]
Some videos won't play when opened from the posts view, but plays fine when opened from the comments view.

[Video of the bug](https://photos.app.goo.gl/XayMAqZaMBi8UsvR6) 

[Problematic post](https://www.reddit.com/r/GifRecipes/comments/jnakf4/stir_fried_beef_in_black_pepper_sauce_any/) 

Version 4.1.0-beta4

OnePlus 7 Android 10

**Comment by Docile-Alligator** [comment]
Thank you for reporting. I will look into it.

**Comment by Docile-Alligator** [comment]
Fixed. Just wait for beta5.
