### ISSUE TITLE
Markdown in comments, messages, sidebars.

### ISSUE THREAD

**Issue by Alterae** [Docile-Alligator/Infinity-For-Reddit#214]
While markdown in posts seems to work mostly fine, markdown in comments and messages (especially tables) and in subreddit sidebars (notably various heading levels) often does not render.  This hurts consistency and polish, and makes navigating and reading these sections more difficult.

**Comment by Docile-Alligator** [comment]
This is because these markdown have wrong syntax.

**Comment by Alterae** [comment]
> This is because these markdown have wrong syntax.

Here's an example of a comment which doesn't render correctly:

```md
[Click here](https://www.reddit.com/message/compose/?to=UpdateMeBot&subject=Subscribe&message=SubscribeMe%20u%2Farclightmagus%20r%2FHFY) to subscribe to u/arclightmagus and receive a message every time they post.

*****

|[^(Info)](https://www.reddit.com/r/UpdateMeBot/comments/ggotgx/updatemebot_info_v20/)|[^(Request Update)](https://www.reddit.com/message/compose/?to=UpdateMeBot&subject=Update&message=SubscribeMe%21%20u%2Fusername%20r%2Fsubreddit)|[^(Your Updates)](https://www.reddit.com/message/compose/?to=UpdateMeBot&subject=List%20Of%20Updates&message=MyUpdates)|[^(Feedback)](https://www.reddit.com/message/compose/?to=Watchful1&subject=UpdateMeBot%20Feedback)|[*^(New!)*](https://www.reddit.com/r/UpdateMeBot/comments/juh0f8/new_features_title_in_message_subject_and_recent/)|
|-|-|-|-|-|
```

On GitHub, this markdown renders as such:

> [Click here](https://www.reddit.com/message/compose/?to=UpdateMeBot&subject=Subscribe&message=SubscribeMe%20u%2Farclightmagus%20r%2FHFY) to subscribe to u/arclightmagus and receive a message every time they post.
> 
> *****
> 
> |[^(Info)](https://www.reddit.com/r/UpdateMeBot/comments/ggotgx/updatemebot_info_v20/)|[^(Request Update)](https://www.reddit.com/message/compose/?to=UpdateMeBot&subject=Update&message=SubscribeMe%21%20u%2Fusername%20r%2Fsubreddit)|[^(Your Updates)](https://www.reddit.com/message/compose/?to=UpdateMeBot&subject=List%20Of%20Updates&message=MyUpdates)|[^(Feedback)](https://www.reddit.com/message/compose/?to=Watchful1&subject=UpdateMeBot%20Feedback)|[*^(New!)*](https://www.reddit.com/r/UpdateMeBot/comments/juh0f8/new_features_title_in_message_subject_and_recent/)|
> |-|-|-|-|-|

On the official Reddit mobile app, as well as the desktop website, the table at the end of this comment renders correctly.  Additionally, selecting the `view full markdown` option for the comment in Infinity properly displays the table.  Only in the normal comment view does this table not render.  I don't think this is a case of the syntax being wrong.

**Comment by potatoleek** [comment]
I've also noticed that tables do not display correctly in the comment view.
Here's another example: https://www.reddit.com/r/millionairemakers/comments/mu0jzl/first_of_allholy_crap_second_of_allholy_crap/gv32w59?utm_source=share&utm_medium=web2x&context=3

**Comment by Docile-Alligator** [comment]
This is intended. Comments may have a smaller width so tables may not look good.
