### ISSUE TITLE
[Amoled dark] Spoiler text is different color making contents visible.

### ISSUE THREAD

**Issue by quentincaffeino** [Docile-Alligator/Infinity-For-Reddit#215]
Title says it all. Github for android for some reason wouldn't let me upload screenshots, so I've posted them on here:
[https://imgur.com/a/JBaXPqv](https://imgur.com/a/JBaXPqv)

**Comment by Docile-Alligator** [comment]
Join the beta program an install the latest beta which fixes this issue.
