### ISSUE TITLE
Double tap on photo to zoom gone

### ISSUE THREAD

**Issue by Diarrhio** [Docile-Alligator/Infinity-For-Reddit#218]
Latest build loses "double tap to zoom in on photo" functionality when viewing a post's photo. This is a pretty handy feature

**Comment by Diarrhio** [comment]
Never mind. Issue has disappeared after first launch

**Comment by Docile-Alligator** [comment]
Actually this is caused by limiting the zoom level when double tap. If an image is in high resolution, then double tap will be available, otherwise, double tap will be disabled because the image itself is too small to zoom in. This behavior is controlled by the image viewing library this app uses.

**Comment by Diarrhio** [comment]
I've been experimenting with this for a while. Is it possible to control the double click behavior in the library your using? I def prefer the old behavior. Even if the res is too low, it's still nice to be able to zoom in by double clicking. I find myself fighting this all the time

**Comment by Docile-Alligator** [comment]
Hi I haven't found a way to control the behavior.
