### ISSUE TITLE
Feature Request: Autoplay gifs in feed

### ISSUE THREAD

**Issue by Gagnef03** [Docile-Alligator/Infinity-For-Reddit#22]

**Comment by Docile-Alligator** [comment]
Ok! I will add it. But it takes some time.

**Comment by Wilker-a** [comment]
a button to manually play or pause the gif would be useful too, along with an option in the setting to have it paused by default to save data too (see #28) \^w\^

**Comment by Docile-Alligator** [comment]
Done
