### ISSUE TITLE
Support auto-dark mode.

### ISSUE THREAD

**Issue by xmha97** [Docile-Alligator/Infinity-For-Reddit#221]
Hello,
Please please support auto-dark mode. (like Aurora Droid):
![Screenshot_2020-11-26-21-14-32-077_com aurora adroid](https://user-images.githubusercontent.com/23485114/100380618-6bc99780-302c-11eb-8dbe-527467a5383d.jpg)

**Comment by xeals** [comment]
Infinity supports following the system theme on Android 10 and above. Select it under Settings -> Theme -> Theme -> Device Default.

**Comment by xmha97** [comment]
My phone is Android 9.0 and fully supported dark theme.
Please show this option.

**Comment by Nova-Aurora** [comment]
AOSP has only supported system-wide dark mode since Android 10. What is your phones Android skin, since it probably implements it's own version of this?

**Comment by xmha97** [comment]
> 
> 
> AOSP has only supported system-wide dark mode since Android 10. What is your phones Android skin, since it probably implements it's own version of this?

I'm using Xiaomi Mi 6.
On my phone, many apps support system-wide dark mode.
# For example
Microsoft To-Do
Google Photos
Google Translate
Microsoft SwiftKey
Aptoide
Samsung Health
Adobe Acrobat Reader
GitHub

**Comment by tudos4** [comment]
@xmha97 you can use a custom rom there are android 11 roms too on xda
