### ISSUE TITLE
Can't switch back to card layout

### ISSUE THREAD

**Issue by jeremiah-miller** [Docile-Alligator/Infinity-For-Reddit#224]
I was messing around with the settings and switched to post layout to compact, but now I want to switch back to card layout and I'm able to select card layout, but nothing changes and it's still in compact layout. I've tried killing the app and relaunching but it's still in compact layout. 

Otherwise the app looks amazing!

**Comment by Docile-Alligator** [comment]
You need to change the post layout in 3-dot menu, not settings.

**Comment by jeremiah-miller** [comment]
Ohhh I see. So then what's the option in settings for?

**Comment by Docile-Alligator** [comment]
This option is for changing the default post layout which applies to all the post feeds whose layouts were not set before.
