### ISSUE TITLE
Various Settings menu things

### ISSUE THREAD

**Issue by Nova-Aurora** [Docile-Alligator/Infinity-For-Reddit#226]
In Settings > About > F-Droid, you have a link to https://www.reddit.com/r/Infinity_For_Reddit/comments/f23o0y/for_anyone_who_wants_to_use_fdroid/, despite it being superceded by https://www.reddit.com/r/Infinity_For_Reddit/comments/jvh8a2/infinity_is_now_on_the_real_fdroid/
![Screenshot_2020-12-07-12-14-31](https://user-images.githubusercontent.com/62871042/101389535-31ab9180-3887-11eb-9fad-6deef9f5e990.jpg)

Furthermore, when using the theme Amoled White at least a few settings descriptors can be hard to read by default due to being a darker grey.

Settings > Data Saving Mode
![Screenshot_2020-12-07-12-19-53](https://user-images.githubusercontent.com/62871042/101389314-dd081680-3886-11eb-9b86-cfb0ddfce75b.jpg)
Settings > Theme
![Screenshot_2020-12-07-12-18-00](https://user-images.githubusercontent.com/62871042/101389374-f3ae6d80-3886-11eb-9021-aa58c1993f42.jpg)

**Comment by AndhikaWB** [comment]
I don't think the second one is an issue though, what color do you expect? Making it as white would be weird for me since it's an info, not actual settings (different color to differentiate between them).

**Comment by Nova-Aurora** [comment]
My issue wasn't that it is a different color, it's that in the current colors in the amoled themes are difficult to read.
