### ISSUE TITLE
[Bug] Some videos will autoplay even if autoplay is disabled

### ISSUE THREAD

**Issue by AndhikaWB** [Docile-Alligator/Infinity-For-Reddit#227]
For example this one that appear on my home: https://www.reddit.com/r/educationalgifs/comments/k9242n/how_a_punch_card_weaving_machine_invented_by/

EDIT: Tested on Infinity v4.1.0 and v4.1.1, LineageOS 17.1

**Comment by AndhikaWB** [comment]
Another one that I found: https://www.reddit.com/r/gifs/comments/ka8ljx/the_way_these_egg_dumplings_are_made/

**Comment by PinkDev1** [comment]
I can confirm the first one, but the 2nd one doesn't autoplay for me.

Infinity: 4.1.0
Android: 9

**Comment by Docile-Alligator** [comment]
This is because the preview of the post is a gif, not an image.

**Comment by AndhikaWB** [comment]
When I click the gif Infinity let me pause and fast forward it though, but since the quality is the same I think it is still the same gif as the preview one (not a video)? If Infinity is able to control the gif (when I click it) then I think preventing the gif from autoplaying should be possible. But I will let @Docile-Alligator to decide whether to close this issue or not, since this is not a big deal for me.

**Comment by Docile-Alligator** [comment]
> When I click the gif Infinity let me pause and fast forward it though, but since the quality is the same I think it is still the same gif as the preview one (not a video)?
It is a video, not a gif. Unfortunately, the gif library does not support stopping animation in the GifImageView, so there is no way to stop the gif animation.
