### ISSUE TITLE
Only SFW search results

### ISSUE THREAD

**Issue by DatAres37** [Docile-Alligator/Infinity-For-Reddit#228]
Hi and thanks for this great app in advance.

I'm not sure when it started, but I'm only getting SFW search results for subreddits etc. I already checked my settings about 3 times, reinstalled the app and resetted all settings in the menu. NSFW is definitely activated. Is there any special button I'm missing?

**Comment by Mafuyu123** [comment]
To do so, you have to enable NSFW for your account on the official reddit app or website.

**Comment by bumjrah** [comment]
> To do so, you have to enable NSFW for your account on the official reddit app or website.

Enabling nsfw doesn't return nsfw search results for me too. Funny enough, it works when you go to anonymous mode. I don't know if this is by design or not. 

The update to 4.1.1 is what brought this change. Previous version worked normally.

**Comment by AndhikaWB** [comment]
If I remember correctly there are 2 settings related to NSFW on your Reddit account preferences (you can access it from the web, no need to install official Reddit app), one is general NSFW (gore, etc. on SFW subreddit) and the other one is consent for adult content (NSFW subreddit). The second one must be checked on your account so NSFW subreddits will appear on search.

**Comment by DatAres37** [comment]
Alright, thanks. Enabling "include not safe for work (NSFW) search results in searches" in the settings worked for me. Must be a new option or something, since I didn't change anything.
