### ISSUE TITLE
Bug: Failed to load, tap to retry on "All" and "Best" menu

### ISSUE THREAD

**Issue by jnthnz** [Docile-Alligator/Infinity-For-Reddit#23]
Hello,

I'm pretty sure this is an app issue and not my internet because every other app works fine. The app keeps on prompting me to retry and refresh feed. I've tried restarting my phone and clearing the cache on the app. Hopefully you can fix this with the next version of this great app.

Video: https://drive.google.com/file/d/110bzl2VPrWZLHaFPEoxd47h7isO59hJh/view?usp=drivesdk

**Comment by Docile-Alligator** [comment]
Hey could you try loading All and Best posts in official Reddit website or app? I cannot replicate this behavior.

**Comment by jonathanjosephzero** [comment]
https://drive.google.com/file/d/11cbA-alVVwv_0-czwdr0fuDwoda0pgso/view?usp=drivesdk

**Comment by Docile-Alligator** [comment]
Thank you! In the next update I will display a more precise error message when encountering this error. Could you send the message back after you update the app?

**Comment by jonathanjosephzero** [comment]
Sure! Thanks for helping!

**Comment by Docile-Alligator** [comment]
Thank you very much!

**Comment by Docile-Alligator** [comment]
Hi could you open this link: https://www.reddit.com/best.json?raw_json=1
And send the response to me? So that I can see if it is related to parsing json.
