### ISSUE TITLE
Bottom bar height is different when viewing the home page vs viewing a subreddit

### ISSUE THREAD

**Issue by Jnss98b** [Docile-Alligator/Infinity-For-Reddit#231]
![Screenshot_20201223-022328.png](https://user-images.githubusercontent.com/24306400/102971063-a9ec9680-44c6-11eb-9a00-b6b07c0442b8.png)![Screenshot_20201223-022335.png](https://user-images.githubusercontent.com/24306400/102971069-abb65a00-44c6-11eb-8682-fbb1be3ea66e.png)

**Comment by Docile-Alligator** [comment]
Does this still occur in v4.2.4?

**Comment by Jnss98b** [comment]
Nope I think it's fixed
