### ISSUE TITLE
Deep links don't open in-app

### ISSUE THREAD

**Issue by rolivav** [Docile-Alligator/Infinity-For-Reddit#234]
Happens every now and then in r/bestof when you want to go to the original thread. See for example:
https://www.reddit.com/r/bestof/comments/kokmsg/ucascadeon_describes_what_gender_dysphoria_feels/

This is what it links to:
https://www.reddit.com/r/TooAfraidToAsk/comments/koaab4/comment/ghpyut5

It will open with the webview inside of Infinity.

**Comment by rolivav** [comment]
The problem seems to only happen if you go from the original bestof thread from inside the app, it works fine if you click the link and open it directly in Infinity.

**Comment by PinkDev1** [comment]
Also verified on v4.2.0-beta1

**Comment by tasmo** [comment]
Still a problem in 4.2.5.

**Comment by NomarCub** [comment]
In 4.3.3 it opens the thread and highlights the right comment for me. Is this fixed for everyone?

**Comment by tasmo** [comment]
Yes, it opens the links now in-app. What I would suggest is that Infinity also scrolls to the linked comment's top instead the Reddit entry's top.
