### ISSUE TITLE
Crash - "Too large(176407360bytes) bitmap"

### ISSUE THREAD

**Issue by Kuuchuu** [Docile-Alligator/Infinity-For-Reddit#235]
`Infinity App crashed in main Version code: 52 Version name: 4.1.1 Stack Trace: java.lang.RuntimeException: Canvas: trying to draw too large(176407360bytes) bitmap. at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:281) at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:91) at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548) at android.widget.ImageView.onDraw(ImageView.java:1434) at android.view.View.draw(View.java:23187) at android.view.View.updateDisplayListIfDirty(View.java:22062) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.draw(View.java:23190) at android.view.View.updateDisplayListIfDirty(View.java:22062) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.draw(View.java:23190) at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429) at android.view.View.updateDisplayListIfDirty(View.java:22062) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.draw(View.java:23190) at android.view.View.updateDisplayListIfDirty(View.java:22062) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.draw(View.java:23190) at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429) at android.view.View.updateDisplayListIfDirty(View.java:22062) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.draw(View.java:23190) at android.view.View.updateDisplayListIfDirty(View.java:22062) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.updateDisplayListIfDirty(View.java:22048) at android.view.View.draw(View.java:22917) at android.view.ViewGroup.drawChild(ViewGroup.java:5230) at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987) at android.view.View.draw(View.java:23190) at com.android.internal.policy.DecorView.draw(DecorView.java:1154) at android.view.View.updateDisplayListIfDirty(View.java:22062) at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588) at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594) at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667) at android.view.ViewRootImpl.draw(ViewRootImpl.java:4296) at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4080) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3348) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999) at android.view.Choreographer.doCallbacks(Choreographer.java:797) at android.view.Choreographer.doFrame(Choreographer.java:732) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

**Comment by Docile-Alligator** [comment]
This is because an image is too large to load. I will further decrease the limit though.

**Comment by Docile-Alligator** [comment]
Fixed
