### ISSUE TITLE
[Bug] "i" modifier support on regexp in posts filter

### ISSUE THREAD

**Issue by PinkDev1** [Docile-Alligator/Infinity-For-Reddit#237]
I've been testing the v4.2.0-beta1, and I'm trying to use a regexp to filter out some words. But I think the `i` modifier (ignore case) is broken.

I've tried the following:
`/(?i)dog/
/dog/i`
Then I went to r/dogs and on both cases they made infinity crash. Yes, there are posts there that dont have the word dog in them. It shouldn't have crashed, but instead it should've kept searching :p

Good job by the way! u da MVP

**Comment by Docile-Alligator** [comment]
Thank you for reporting. I will fix this.

**Comment by Docile-Alligator** [comment]
I have tried using this regex, but it did not crash. Could you show me a recording of this?

**Comment by PinkDev1** [comment]
Well this is awkward.. I can't reproduce the crash. I thought they happened because of the regexp, but it seems that's not the case. I wonder what caused those crashes back then.

But still, the `i` modifier still has no effect, so that'll need some work :p
Sorry for the late response btw, I've been busy

**Comment by Docile-Alligator** [comment]
(?i)dog(?-i) is the correct regex. (?-i) turns off case-insensitive mode.
