### ISSUE TITLE
[Feature] Ignore case in word match in posts filter

### ISSUE THREAD

**Issue by PinkDev1** [Docile-Alligator/Infinity-For-Reddit#238]
v4.2.0-beta1

When filtering posts with the word list, only exact case matches will be detected and hidden; other cases will be ignored.

Yes, the user could technically make a list of every possible case combination for their "banned words" list, but that'd be long and inefficient. I recommend putting all the titles in lowercase before matching them with the "banned words" list.

**Comment by Docile-Alligator** [comment]
Will do that. Beta1 was just for testing the filtering ability. More changes will be available in subsequent beta versions.

**Comment by Docile-Alligator** [comment]
Done
