### ISSUE TITLE
[Feature] Tap to collapse comments

### ISSUE THREAD

**Issue by StefanTraistaru** [Docile-Alligator/Infinity-For-Reddit#239]
Could there be an option to enable tap to collapse a comment?

The current functionality is to hold, which I think is the way the official reddit app is doing this.
But I really find it frustrating to wait for a comment to collapse. And as I never use the option to show/hide the comment toolbar, a tap on a comment does nothing for me currently.

Also, as there is a feature that the user can enable when taping a comment (show/hide the comment toolbar), I think they could be interchanged by the user. This way if the "tap to collapse comment" is enabled, a user will still be able to show/hide the comment toolbar if he wants, instead of disabling that feature completely.

For example:
- If **hold** to collapse comment is enabled, the user can only enable show/hide comment toolbar as a **tap** action
- If **tap** to collapse comment is enabled, the user can only enable show/hide comment toolbar as a **hold** action

**Comment by Docile-Alligator** [comment]
Settings->Gestures & Buttons->Swap Tap and Long Press in Coments.
