### ISSUE TITLE
Feature request: Show multi's

### ISSUE THREAD

**Issue by tbrasser** [Docile-Alligator/Infinity-For-Reddit#24]
I have a few multireddits that I use to categorize my subscribed subreddits, but I can't find them in the app.

**Comment by Docile-Alligator** [comment]
Hi! I will add this feature in the future.

**Comment by tbrasser** [comment]
While I'm at it, an option to open links outside of the app? Instead of webview / in-app-browser.

**Comment by Docile-Alligator** [comment]
OK! That's good advice.

**Comment by Docile-Alligator** [comment]
Thank you. Multireddit has been implemented. Links are opened outside the app.
