### ISSUE TITLE
[Feature] Comment dividers only between top comments

### ISSUE THREAD

**Issue by StefanTraistaru** [Docile-Alligator/Infinity-For-Reddit#240]
Could there be an option to display comment dividers only between top comments?

In my case it makes it better to navigate the comment section as it provides a better overview of a thread.
It could be a choice for the user:
- Off
- Between top comments
- Between all comments

Note: I disabled the comment toolbar to get more comments in the screenshot.

Dividers between all comments (as it is now):
![Screenshot_20210108-161523_resized](https://user-images.githubusercontent.com/23136219/104032019-393bbe80-51d6-11eb-829b-baadc6d66c4e.jpg)

Just between top comments:
![Screenshot_20210108-161523_resized](https://user-images.githubusercontent.com/23136219/104032104-57a1ba00-51d6-11eb-8040-f1de5f685a69.png)

**Comment by Docile-Alligator** [comment]
Nice idea!
