### ISSUE TITLE
Data Saving option doesn't have a function to Preset the video quality. 

### ISSUE THREAD

**Issue by Cyborg002** [Docile-Alligator/Infinity-For-Reddit#246]
I recently found that, Infinity consumed more data even when Data saving is ON.
There's no option where I can Preset the quality of video.
Although, It has a option to change quality of video, but this option appear when you already click on the video. Until then the video is automatically loaded in the highest quality. Then, changing video quality is useless and stupid move.
Actually, I've a Limited data plan.

**Comment by Docile-Alligator** [comment]
Added.
