### ISSUE TITLE
[Feature request] Auto-login on embedded tab open

### ISSUE THREAD

**Issue by KaKi87** [Docile-Alligator/Infinity-For-Reddit#251]
e.g. polls

---

Thanks

**Comment by Docile-Alligator** [comment]
Chrome custom tabs share the same data with Chrome so once you have logged in in Chrome (or even Chrome custom tabs), there is no need to login again.

**Comment by KaKi87** [comment]
Yes, but :
1. It still means that I have to login twice
2. Browser sessions still have expiry dates.

**Comment by Docile-Alligator** [comment]
It's impossible to automatically login for you on a chrome custom tab.

**Comment by KaKi87** [comment]
How about embedding a webview and injecting JS into it ?
