### ISSUE TITLE
Redgifs throwing JSONException

### ISSUE THREAD

**Issue by anonymous-developer-12** [Docile-Alligator/Infinity-For-Reddit#252]
Hey there,

Over the last few days I've noticed that some videos (notably redgifs) are throwing the following:

```
01-22 12:24:33.333 25081 25175 W System.err: org.json.JSONException: No value for webmUrl
01-22 12:24:33.334 25081 25175 W System.err:    at org.json.JSONObject.get(JSONObject.java:400)
01-22 12:24:33.334 25081 25175 W System.err:    at org.json.JSONObject.getString(JSONObject.java:561)
01-22 12:24:33.334 25081 25175 W System.err:    at ml.docilealligator.infinityforreddit.FetchGfycatOrRedgifsVideoLinks$ParseGfycatVideoLinksAsyncTask.doInBackground(FetchGfycatOrRedgifsVideoLinks.java:103)
01-22 12:24:33.334 25081 25175 W System.err:    at ml.docilealligator.infinityforreddit.FetchGfycatOrRedgifsVideoLinks$ParseGfycatVideoLinksAsyncTask.doInBackground(FetchGfycatOrRedgifsVideoLinks.java:86)
01-22 12:24:33.334 25081 25175 W System.err:    at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-22 12:24:33.334 25081 25175 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-22 12:24:33.334 25081 25175 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
01-22 12:24:33.334 25081 25175 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-22 12:24:33.334 25081 25175 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-22 12:24:33.334 25081 25175 W System.err:    at java.lang.Thread.run(Thread.java:923)
```

Reddit link to example crash: https://www.reddit.com/r/JustFriendsHavingFun/comments/l1wmqz/having_her_guess_whos_doing_what_original_content/

Oddly enough, when selecting the `share button` and then `Copy Video Link` it provides this link which seems to work in the browser - https://v.redd.it/jwzkglh67oc61/DASH_360.mp4. This is even when the original link isn't even a `v.redd.it` domain (https://redgifs.com/watch/sociablefabulouscollie).

The app shows this when trying to load the video:
![photo_2021-01-22_12-46-32](https://user-images.githubusercontent.com/77816948/105434560-ea028d00-5caf-11eb-97ca-5c555b671f48.jpg)

Many thanks!

Edit: Tried app version 4.1.1 and 4.2.0-beta2

**Comment by theoasispc** [comment]
same issue on both versions :(

**Comment by anonymous-developer-12** [comment]
I've been able to fix it locally and create a demo build that works on my phone.
PR - https://github.com/Docile-Alligator/Infinity-For-Reddit/pull/253

**Comment by Docile-Alligator** [comment]
Thank you very much for your help!
