### ISSUE TITLE
[Bug] Minor black on black (text) issue

### ISSUE THREAD

**Issue by AndhikaWB** [Docile-Alligator/Infinity-For-Reddit#254]
Occurs when selecting video quality using dark theme (probably on amoled too), see image below.
![photo_2021-01-22_23-16-10](https://user-images.githubusercontent.com/17119394/105516509-8bb5c880-5d08-11eb-9150-6aac49686380.jpg)

Using Infinity v4.1.1 on LineageOS 17.1 (Android 10).

**Comment by Docile-Alligator** [comment]
OK. I will try fixing it.

**Comment by Docile-Alligator** [comment]
Fixed.
