### ISSUE TITLE
Option to disable auto-repeat for videos

### ISSUE THREAD

**Issue by trenchbear** [Docile-Alligator/Infinity-For-Reddit#255]
What I am missing is an option to disable auto replay of videos. 
Is it possible to add this feature to the videos settings section?

**Comment by Docile-Alligator** [comment]
I think I can. I need to check the video autoplay library's API first.

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by Docile-Alligator** [comment]
@KaKi87 Done.
