### ISSUE TITLE
Spoiler and NSFW filters not working

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#257]
UPDATE: I thought the NSFW filter was not working, because it kept loading and never showed any results. However, I deleted and reinstalled the app and therefore NSFW posts were disabled. The user should be notified that NSFW posts are disabled instead of waiting an infinite amount of time on results that will never appear.

**Comment by Docile-Alligator** [comment]
Nice suggestion!
