### ISSUE TITLE
Anonymous subscriptions

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#259]
Make it possible to subscribe to subreddits anonymously. That is, just keep track of which subreddits the user subscribes to offline, without the need of a reddit account. It would be even nicer if the user could export his or her subscriptions to a csv file and import them again.

**Comment by Docile-Alligator** [comment]
This will probably be available in v4.3.0.

**Comment by mabuckman** [comment]
It would be nice if you could save posts/comments offline too.

**Comment by Docile-Alligator** [comment]
Done.

**Comment by canDry** [comment]
Sweet!!  
  
Could you please plz add a '+' to the subscriptions screen to manually add (/r) subreddit names, so that we can populate without having to find them in the all feed?
