### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by neekless** [Docile-Alligator/Infinity-For-Reddit#26]
Hi I have several feature requests but I don't know if I should create separate issues for them but I think I'll put them all in one. There's no rush to implement any of these but I'm coming as a Slide user and there are some things I would like to see in Infinity eventually.

1. Compact/List layout view: Instead of showing the full size media in the main page/subreddits, show a thumbnail instead.
2. Option to open the app in r/popular or r/all by default instead of Best.
3. Data saving: Load lower quality media when on mobile data.
4. Show poster's username in the main page/subreddits: Currently posts don't show usernames until the post is opened.
5. Option to hide post in the main page/subreddits: Currently the hide post option is only available when the post is opened.
6. Read indicators: Differentiate between read (opened) posts vs unread ones. Most reddit clients dim the post.
7. Option to quickly hide all read posts in the main page/subreddits.
8. Subreddit sidebar: Currently there is no way (or maybe I'm an idiot and cannot find it) to open the subreddit sidebar, where information such as subreddit rules, subreddit moderator lists, etc. are. 

Sorry if this is long and thanks for taking the time to read through it.

**Comment by Docile-Alligator** [comment]
The compact layout has been implemented.

**Comment by Docile-Alligator** [comment]
Now the username is shown in main pages. Subreddit sidebar can now be opened.

**Comment by neekless** [comment]
> Now the username is shown in main pages.

Just realized that it only shows on card layout and not compact layout. Hope it can be added for compact too!

**Comment by Docile-Alligator** [comment]
Yes. I will find a way to show the username in the compact layout without looking too ugly.

**Comment by soorajsr97** [comment]
Pls add this too (Data saving: Load lower quality media when on mobile data.)

**Comment by Docile-Alligator** [comment]
Done: Option to open the app in r/popular or r/all by default instead of Best.

**Comment by Docile-Alligator** [comment]
Done: Subreddit sidebar

**Comment by Docile-Alligator** [comment]
Hiding read posts will be available in v4.2.0.
