### ISSUE TITLE
Filter's doesn't work for me

### ISSUE THREAD

**Issue by pr4bh4sh** [Docile-Alligator/Infinity-For-Reddit#260]
I'm trying to filter out anything related to Trump. I tried keywords `Trump,trump` and regex `\trump|Trump\` and still see posts with the title.

What am I missing? Is there an example of how to use filter properly?

App version: 4.2.0-beta2

Thanks for creating the awesome app.

**Comment by Docile-Alligator** [comment]
You need to click the post filter name and select Apply to. On the next page, you need to select which place you want to use this post filter.

**Comment by pr4bh4sh** [comment]
Thanks, it worked
