### ISSUE TITLE
Make a Discord Server(Like Support Server)

### ISSUE THREAD

**Issue by udaymehta** [Docile-Alligator/Infinity-For-Reddit#267]
Hi @Docile-Alligator ,

It would be nice if you make a discord.

**Why?**
  - Conversations will be quick, we can help each other, you can make a bugs/feature/announcement channels for quick announcements or something else.

**Comment by Docile-Alligator** [comment]
I currently don't have enough time to respond to new messages immediately so I think it is OK to just use r/Infinity_For_Reddit.

**Comment by Wladefant** [comment]
At the moment we don't have plans to open a discord server, because everything you mentioned is possible in github and reddit and should be done there because then we have an overview an can react fast
