### ISSUE TITLE
[Feature Request] Swipe mode for viewing posts

### ISSUE THREAD

**Issue by nadiration** [Docile-Alligator/Infinity-For-Reddit#269]
Just like Sync does, swipe view mode will be really a great addition to this beautiful app. Think of it this way, you are browsing r/memes and you don't have to scroll to the next post or click the image to fully view the meme/photo just swipe and jump to the next meme! Seamless and focused.

**Comment by Docile-Alligator** [comment]
Will be available in v4.3.0.

**Comment by Docile-Alligator** [comment]
Done.

**Comment by nadiration** [comment]
@Docile-Alligator ♥️ thank you a million times. Your app changed my world it's now my default Reddit app. Beautiful and feature rich. I even sacrificed inbox (messages) for this app because Reddit doesn't like third party apps so they don't provide such APIs anyway I find that benefits I get from this app outweighs features Reddit limited to their app.

**Comment by Docile-Alligator** [comment]
@nadiration Thank you very much!
