### ISSUE TITLE
Bug: r/ links within comments not shown as links

### ISSUE THREAD

**Issue by austinhuang0131** [Docile-Alligator/Infinity-For-Reddit#27]
If a comment only has r/something it shows the link, but if a comment has done other text plus r/something it doesn't show. Proof below, usernames/timestamps censored:

![sketch-1571284765525](https://user-images.githubusercontent.com/16656689/66976890-97c8ca00-f071-11e9-8465-751c0c17e6d3.png)

**Comment by austinhuang0131** [comment]
Also this

![_20191017_000843](https://user-images.githubusercontent.com/16656689/66977077-61d81580-f072-11e9-937f-16935f5f5094.JPG)

**Comment by Docile-Alligator** [comment]
Yes, I noticed it too. I will try to solve it.

**Comment by Docile-Alligator** [comment]
Hi, the problem is now fixed and it will be released in the next update.

**Comment by Wilker-a** [comment]
aditionally, the initial slash ('/') before 'r/' or 'u/' are not counted whenever the links are recognized. was that fixed too? :3

**Comment by Docile-Alligator** [comment]
@Wilker-a Yes it is fixed too.

**Comment by Wilker-a** [comment]
cool, thank you =\^-\^=

**Comment by Docile-Alligator** [comment]
You are welcome~
