### ISSUE TITLE
[Feature Requset] Feature to backup and restore user settings/preferences

### ISSUE THREAD

**Issue by PhoenixFlame101** [Docile-Alligator/Infinity-For-Reddit#270]
Just bringing up a feature request that I saw on the subreddit a while ago. There is also an open issue (#163) asking for the same feature, but the thread is long dead.

A simple way to export our settings into a JSON or something and then restore from the file. It'll really help if you need to reinstall the app for whatever reason or if you're switching phones.

Cheers.

**Comment by Docile-Alligator** [comment]
Yes. I am planning to add this in v4.3.0.

**Comment by Docile-Alligator** [comment]
Done.

**Comment by PinkDev1** [comment]
Sorry, but where is this option? I can't seem to find it in the Settings section

**Comment by PinkDev1** [comment]
nvm found it in "Advanced"
