### ISSUE TITLE
[Feature Request]Suggest title when sharing a link

### ISSUE THREAD

**Issue by nikhilCad** [Docile-Alligator/Infinity-For-Reddit#271]
In Rif for reddit when I am posting a link there is a little Suggest Title button which automatically fills in the title of the post based on the content of the link.
Please consider adding this feature. And thanks for this app.

**Comment by Docile-Alligator** [comment]
Good idea. I need to learn how to do this first.

**Comment by nikhilCad** [comment]
On old.reddit.com the website shows this option itself when submitting

**Comment by nikhilCad** [comment]
Okay I found there is an app called Slide for Reddit which can suggest title. I found this script by search Suggest Title in its Github repo.

https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/util/TitleExtractor.java

**Comment by Docile-Alligator** [comment]
Hi thank you. This feature is already available in v4.3.0-beta1. Please join the beta program on google play and get the update.
