### ISSUE TITLE
[Feature request] add support for Lemmy

### ISSUE THREAD

**Issue by TheSilencedOne** [Docile-Alligator/Infinity-For-Reddit#277]
This is a strange request but I would like support for https://lemmy.ml/  Lemmy is a open source alternative to Reddit and it is very similar.

**Comment by Docile-Alligator** [comment]
Hi supporting Lemmy is not easy as it seems. I would like to focus on Infinity for Reddit now.

**Comment by olwe1** [comment]
I'd love to have this feature also. I'd be glad to help 🙂
