### ISSUE TITLE
Pinned posts not showing in subreddit?

### ISSUE THREAD

**Issue by EmVeddii** [Docile-Alligator/Infinity-For-Reddit#284]
Not sure if this is a bug or simply not implemented. The pinned posts of a subreddit don't seem to be showing. Mildly annoying considering I frequent a weekly pinned subreddit Mega-Hub and can no longer easily access this in app due to switching to Infinity. (I won't be leaving yet though. App is amazing otherwise!)

**Comment by EmVeddii** [comment]
Seems to work in certain subs but not others. In r/memes the pinned posts showed up. In r/unpopularopinions they didn't. Must be a bug.

**Comment by Docile-Alligator** [comment]
I think you might have enabled Hide Read Posts Automatically in settings->Post History.

**Comment by EmVeddii** [comment]
Huh. That would make sense. But it doesn't seem to hide posts in other places where I've read them... Separate issue i guess. I'll try turning it off, Thanks!

**Comment by EmVeddii** [comment]
Update: It worked! Thank you!

**Comment by Wladefant** [comment]
The Problem here is that l, normally pinned are pinned for a reason (for example megathreads, tutorials, rules). Do normally they aren't normal posts and therefore should not be treated like them.

So mich solution is to exclude from the toggle feature mentioned above

**Comment by owzim** [comment]
I had the problem that no pinned posts showed up at all anywhere and I did not enable the aforementioned setting. `Settings > Advanced > Reset All Settings` fixed the issue. Still don't know what the responsible setting was though.
