### ISSUE TITLE
Marked as Read not working.

### ISSUE THREAD

**Issue by EmVeddii** [Docile-Alligator/Infinity-For-Reddit#285]
Marking Subreddits as read (with auto-hide enabled) doesn't hide them. They mark as read at first and then eventually seem to un-mark and reappear regardless.

**Comment by Docile-Alligator** [comment]
Yes. It only saves no more than 500 posts.

**Comment by EmVeddii** [comment]
I... didn't have 500 posts read. Barely used reddit during that time. But doesn't matter now not even using Infinity. Joey is better
