### ISSUE TITLE
[Feature request] Local Subscriptions, Saving Posts & Multireddits

### ISSUE THREAD

**Issue by ghost** [Docile-Alligator/Infinity-For-Reddit#287]
Allow anonymous accounts to subscribe to Subreddits/Users, Save posts and  create MultiReddits and have this all done locally on the device similar to what Newpipe (https://newpipe.net/) does

**Comment by Docile-Alligator** [comment]
Allowing anonymous subscriptions will be available in v4.3.0.

**Comment by Wladefant** [comment]
Please add each not already implemented feature request to its own post
