### ISSUE TITLE
[UI] Subreddit description interactions

### ISSUE THREAD

**Issue by KaKi87** [Docile-Alligator/Infinity-For-Reddit#289]
Hello,

It would be nice to be able to click links and partially or fully copy text in subreddit description !

Thanks

**Comment by Docile-Alligator** [comment]
Will try. Thank you.

**Comment by Docile-Alligator** [comment]
Done.

**Comment by KaKi87** [comment]
Thanks, waiting for Google Play (beta ?) release :)
