### ISSUE TITLE
When it is set to collapse a comment on tap into of hold, revealing a spoiler collapses the comment

### ISSUE THREAD

**Issue by JustAnotherStrange** [Docile-Alligator/Infinity-For-Reddit#292]
Title. When I tap to reveal a spoiler it collapses so I cannot read the text under the spoiler. When I uncollapse it conceals the spoiler again.

**Comment by Docile-Alligator** [comment]
Yes. I am aware of this. I will try fixing it.

**Comment by Sygmus-1897** [comment]
@JustAnotherStrange I found that you can view spoiler content by "tap and hold" on spoiler. It will show reddit link along with the spoiler on a bottom slide(?) menu. This can be a work around until it gets fixed.
@Docile-Alligator  Another side note is sometimes tapping the comment doesn't collapse the comment tree unless the I scroll the screen/page

**Comment by Docile-Alligator** [comment]
Fixed.
