### ISSUE TITLE
Multireddits in Tab doesn't work.

### ISSUE THREAD

**Issue by Celtyrish** [Docile-Alligator/Infinity-For-Reddit#295]
When using a multireddit in tab. It shows an error message: "error loading tap to try again".

**Comment by chrisgix** [comment]
I am having the same issue. [I saw this post on the subreddit](https://www.reddit.com/r/Infinity_For_Reddit/comments/m2stm7/error_loading_posts_multireddit_issue/) and triple checked everything to make sure it was correct but it still refuses to load

**Comment by Celtyrish** [comment]
Thanks for your reply. I tried the steps from the post you've send me. It worked for me. 
I first tried it with the whole adres (adding the www. ...) but the then i tried from /users/... and that did it for me.

**Comment by chrisgix** [comment]
I tried one more time and still couldn't get it to work :/. I don't know what's wrong with mine

**Comment by Docile-Alligator** [comment]
Could you share your multipath? @chrisgix

**Comment by chrisgix** [comment]
Absolutely. 

This is the link to my multi

https://www.reddit.com/user/joeker9787/m/games/

And this is what I have entered in infinity

games (/user/joeker9787/m/games/)

**Comment by Docile-Alligator** [comment]
@chrisgix I can add your multireddit to my home page with no issue.

**Comment by chrisgix** [comment]
@Docile-Alligator is there any way to enable or see logs? I have tried everything I can think of to get it to work including trying to get the app to forget it is one of the views by switching it to something else and clearing the cache.

**Comment by Docile-Alligator** [comment]
Hi @chrisgix currently there is no way to see logs. But if you know how to use adb, you can execute `adb logcat`. Could you show a screenshot of tab settings that contain your multireddit option?

**Comment by chrisgix** [comment]
Hey @Docile-Alligator 

[Here is a video of my settings and the posts not loading](https://streamable.com/97el24)

**Comment by Docile-Alligator** [comment]
Hi! @chrisgix You need to input the multireddit name as: `/user/joeker9787/m/games`

Not `games (/user/joeker9787/m/games)`

I think I should elaborate more clearly in the settings.

**Comment by chrisgix** [comment]
@Docile-Alligator that did it! Thank you so much!
