### ISSUE TITLE
Hidden scores showing 1 as number of votes

### ISSUE THREAD

**Issue by TheNesze** [Docile-Alligator/Infinity-For-Reddit#296]
Posts and comments that have their scores hidden, show that they have 1 upvote.

In case of comments, this might be because the scoreHidden property of the Comment class is unused in the CommentsListingRecyclerViewAdapter. In row 283 the scoreTextView's text should be set to "Vote" instead of the score if the scoreHidden is true.

For posts it seems like there is no scoreHidden property in the Post class, I'm not sure how it's indicated in a response from the Reddit API.

**Comment by Docile-Alligator** [comment]
Ok! Thank you for this info.

**Comment by Wladefant** [comment]
Hey, can you share an example?
