### ISSUE TITLE
Flip the search and sort buttons at the top of the subreddit view

### ISSUE THREAD

**Issue by j-james** [Docile-Alligator/Infinity-For-Reddit#298]
The "search" and "sort" buttons at the top of the app are flip-flopped depending on whether you're in the main feed or an individual subreddit. 

![Screenshot from 2021-03-18 21-02-35](https://user-images.githubusercontent.com/35242550/111729884-57084e00-882d-11eb-9afb-b05d33bdf2f8.png)
![Screenshot from 2021-03-18 21-02-46](https://user-images.githubusercontent.com/35242550/111729883-566fb780-882d-11eb-9330-a5216f4e01b1.png)

**Comment by Docile-Alligator** [comment]
Haha Ok!

**Comment by Docile-Alligator** [comment]
Done
