### ISSUE TITLE
Bug: Logging in with 2FA doesn't work

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#3]
If I try to log into an account with 2FA enabled, it just seems to refresh the page. 

(You can work around this by putting `[password]:[code]` in for the password but it would be nice to not have to do so, especially since it doesn't tell you that you have to do this.)

**Comment by Docile-Alligator** [comment]
Hey, thanks for the feedback! This issue is fixed in version 1.0.8 which will be released very soon!
