### ISSUE TITLE
See removed comments not working

### ISSUE THREAD

**Issue by 0doru0** [Docile-Alligator/Infinity-For-Reddit#301]
The feature to see removed comments isn't working, I double-checked on reveddit and the comments can be restored there, so it isn't that the comment wasn't up long enough I think. I just get a popup that says the comment couldn't be found.
Thank you for your time!

**Comment by Docile-Alligator** [comment]
Ok. I will look into this.

**Comment by Blanktank** [comment]
This is still not working.
