### ISSUE TITLE
Share image for Text posts with PixelFed/Imgur

### ISSUE THREAD

**Issue by mizzunet** [Docile-Alligator/Infinity-For-Reddit#302]
Boost has this feature, can share image URL, when a image is chosen, it's url would be returned.
Likewise, any chance for that feature to Infinity by PixelFed, https://github.com/pixelfed, Imgur or anything?

**Comment by tegutistgut** [comment]
> Boost has this feature, can share image URL, when a image is chosen, it's url would be returned.


> it's url would be returned

What do you mean by that? Infinity can copy the video and image URL of any post.
