### ISSUE TITLE
Share Video Link Drops Audio

### ISSUE THREAD

**Issue by locuturus** [Docile-Alligator/Infinity-For-Reddit#305]
If I tap the share icon (without or without opening the post) I get several options. One is to share the video link, for example to an app like VLC. This works, except that the video VLC loads hasn't got any audio. I've tried this with a couple of apps just in case VLC is behaving weirdly. Specifically I've noticed this with v.redd.it links.

**Comment by Docile-Alligator** [comment]
Yes, this is because Reddit separates video and audio tracks on the server.
