### ISSUE TITLE
Autoplays videos that shouldn't be there

### ISSUE THREAD

**Issue by Jackretto** [Docile-Alligator/Infinity-For-Reddit#310]
Enable autoplay and disabling "mute autoplay";

Then, find a video and tap on the subreddit's name, it will take you there;

At that point, locking and unlocking the phone will make the audio of the original video (the one trough which we entered the subreddit) play over the audios of the videos you have on screen

**Comment by Doctor-blob** [comment]
Same problem here is an example and a way to replicate it:  
1. let a video autoplay on the homescreen
2. Pause the video and go to a different subreddit
3. Go to your android home screen without closing the app
4. Open the app again and the video will autoplay
