### ISSUE TITLE
Spoilers in comments are impossible to read with certain settings

### ISSUE THREAD

**Issue by Izofeu** [Docile-Alligator/Infinity-For-Reddit#311]
I use an option Swap Tap and Long press in comments and Fully collapse comments option. It works fine but if a comment contains a spoiler, then I cannot read it. Tapping on a spoiler reveals it for a split second and then collapses the comment, making it impossible to read. Long pressing opens up a context menu so it doesn't work either.

**Comment by JustAnotherStrange** [comment]
Duplicate of #292, I think.

**Comment by Izofeu** [comment]
Oh my bad, I didn't notice it.
