### ISSUE TITLE
Random comments have highlighted scores

### ISSUE THREAD

**Issue by rharish101** [Docile-Alligator/Infinity-For-Reddit#312]
Some comments have their score highlighted as if I upvoted them. If I upvote/downvote them, then the behavior is reset.

Here's a video showing the behavior:

https://user-images.githubusercontent.com/25344287/114545276-0d5c2900-9c5c-11eb-9151-82a9d97558f6.mp4

I'm using the default Indigo Dark theme, with only the background colour of a collapsed comment changed.

Info:
* Phone: Stock POCO F1
* Android version: 10
* MIUI version: 12.0.3
* Infinity version: 4.2.5 from F-Droid

**Comment by Docile-Alligator** [comment]
Fixed in 4.3.0-beta3.
