### ISSUE TITLE
An option for seeing only nsfw

### ISSUE THREAD

**Issue by sav1tarr** [Docile-Alligator/Infinity-For-Reddit#313]
just like we have a disable nsfw option, can we have a nsfw only posts option? 
for people like me who have 1 account for both 👀

**Comment by benkorpella** [comment]
This functionality is already implemented. 

Under settings, go to Post Filters, press the floating plus to make a new filter, check the "Only NSFW" toggle, add any other params you would like and bam, only NSFW.

**Comment by Docile-Alligator** [comment]
Yes. @benkorpella is right.
