### ISSUE TITLE
Lemmy support

### ISSUE THREAD

**Issue by PopeRigby** [Docile-Alligator/Infinity-For-Reddit#32]
Lemmy is an open source, federated link-aggregator (like Reddit). The API is quite similar to Reddit, so it shouldn't be too difficult to support it. For using a Lemmy account, you can do something where you can just click "Add account" and add one. @dessalines is the creator, and he can help you out with it.

**Comment by Docile-Alligator** [comment]
Well I have to focus on Reddit for now🤔

**Comment by Docile-Alligator** [comment]
Well I have to focus on Reddit for now🤔

**Comment by PopeRigby** [comment]
Of course, but it would probably be a good idea to future-proof Infinity, so it's possible to do it later.

**Comment by Jnss98b** [comment]
This is a Reddit client 🤦‍♂️

**Comment by PopeRigby** [comment]
Yes, but Lemmy is very similar to Reddit, making it easy to add support.

**Comment by Jnss98b** [comment]
Yeah but I feel like a separate app for it would be better tbh

**Comment by PopeRigby** [comment]
There are lot's of apps that support accounts on different services. Off the top of my head
* Twidere - Supports Mastodon and Twitter
* NewPipe - Supports YouTube, SoundCloud and PeerTube

**Comment by Jnss98b** [comment]
Doesn't mean they should be combined. Again, I'm not against this but I think it would be better served by a separate app instead

**Comment by PopeRigby** [comment]
Why have another app when you can have one that supports two similar services?
