### ISSUE TITLE
Videos start playing in the background.

### ISSUE THREAD

**Issue by mineappIe** [Docile-Alligator/Infinity-For-Reddit#320]
Hi Docile-Alligator,
first of all, thank you for your work with Infinity!
I have a very reproducible problem:
When I am on "another layer" e.g. the comments or the multireddit and accidentally putting it in landscape mode and I have a video in my main feed, it starts playing in the background every time. Once it plays, it doesn't even stop when I turn off my screen. 
It's especially ridiculous when you browse through the comments of a video. If you tilt your phone there, it will start to play the video from the main feed and from the post with a bit of a delay, which I cannot stop until I go back to the main site and pausing the video manually.
The problem also occurs, if I open a post through the notifications of my phone.

I can give you a video that shows the problem if you want to.

Thanks again for your work and have a nice day.

Sincerely,
mineapple

**Comment by Docile-Alligator** [comment]
Yes, I am aware of this. It is because the background of each layer (page) is set to transparent so technically the background page is not paused when you open a new page. Thus the video starts playing in the background.

**Comment by esnar11** [comment]
I still have this issue on version 5.2.1
