### ISSUE TITLE
[BUG] RedGifs videos not loading

### ISSUE THREAD

**Issue by PinkDev1** [Docile-Alligator/Infinity-For-Reddit#322]
App version: 4.3.0-beta2

Infinity will just say "Error fetching redgifs video". But when I open it on the official reddit app, it loads correctly.

Example (Obviously NSFW): https://www.reddit.com/r/redgifs/comments/gfvw9v/redgifs_links_on_reddit_see_comment/

**Comment by Docile-Alligator** [comment]
Oh it's working for me on v4.3.0-beta3. Could you try it again?

**Comment by PinkDev1** [comment]
It's working now. good job!
