### ISSUE TITLE
[BUG] When opening a picture gallery, going back hangs the picture loading.

### ISSUE THREAD

**Issue by gabmiral** [Docile-Alligator/Infinity-For-Reddit#326]
Infinity for Android v4.2.5 stable

(The bug only applies to redd.it galleries, Imgur galleries are not impacted).

When opening a gallery, going back 2 pictures makes all previous pictures ""load"" for ever, without displaying.

A current workaround is to leave the gallery display and open it back.

**Comment by gabmiral** [comment]
Even weirder, this only happens if the galery contains 4 pictures or more, it doesn't happen if it is 3 pictures

**Comment by Docile-Alligator** [comment]
This is fixed in v5.0.0 beta.
