### ISSUE TITLE
Spoiler markdown tags confuses themselves

### ISSUE THREAD

**Issue by gabmiral** [Docile-Alligator/Infinity-For-Reddit#327]
Infinity Android v4.2.5 stable

When a comment contains spoiler tags between letters, the render gets confused, hides most of the text between the first beginning tag and the last ending tag, and adds `>!` in between.

For example, `He>!l!<l>!o!<world` will display like so : https://www.reddit.com/r/u_Gabmiral/comments/myddh8/test/

On an unrelated note, text in spoilers is displayed unhidden when browsing a subreddit/user and quite possibly in the homepage too (and there, the tags dont appear at all - even the ones that get messed up)

**Comment by Docile-Alligator** [comment]
Thank you for reporting this. I will look into it.
