### ISSUE TITLE
[bug][minor] Nummer of comments sometimes wrong 

### ISSUE THREAD

**Issue by adiOdi** [Docile-Alligator/Infinity-For-Reddit#328]
Sometimes the number of comments shown before clicking on a post is not correct, in both directions: sometimes more than there actually are, sometimes less. (No negative numbers) 

This is not a result of some weird counting, like it only counting top/child/... comments, as sometimes "0" is shown as number of comments as well.

This seems random, and only affects approximately 1/10 posts.

This is most likely not because the comments are getting deleted/created at exactly this time or something, as I've had cases of more than 10 showing up as "0", and vice versa(and dates are from before)

**Comment by Docile-Alligator** [comment]
Hi the comment count is fetched from reddit server. So i think Reddit doesn't update the comment count that often.

**Comment by tegutistgut** [comment]
Yes. This issue is normal. Go to the subreddit r/watchredditdie and you'll see that ever, post has less comments than displayed.
