### ISSUE TITLE
Long comment chains don't display all the messages

### ISSUE THREAD

**Issue by gabmiral** [Docile-Alligator/Infinity-For-Reddit#330]
On some subs (like r/AskOuija) it is not rare to find a comment thread where there are more comments in a chain that reddit will display in one page.

On Reddit Web, the official client and most 3rd party clients, a "Continue this thread" button will appear. However, in Infinity, there is none, which makes reading threads like these impossible

**Comment by Docile-Alligator** [comment]
This will be fixed in v4.3.0-beta4.
