### ISSUE TITLE
"Copy Video Link" copies a link to the video without audio

### ISSUE THREAD

**Issue by sharunkumar** [Docile-Alligator/Infinity-For-Reddit#332]
Pressing the share button on a post and clicking "copy video link" copies a link to the video without audio

![Screenshot_20210428-205318](https://user-images.githubusercontent.com/715417/116429984-09d3bf00-a864-11eb-8bd4-a445b3ed4932.jpg)

Post used as example: https://www.reddit.com/r/ForzaHorizon/comments/n0be95/forza_in_a_nutshell/

**Comment by tegutistgut** [comment]
Yes, i can replicate this.

**Comment by DleanJeans** [comment]
That's how v.redd.it videos work.
I suggest using something like ([savemp4.red](https://savemp4.red/) - the only website that saves Reddit videos with audio that exposes direct mp4 URL):
https://savemp4.red/?url=https://www.reddit.com/r/ForzaHorizon/comments/n0be95/forza_in_a_nutshell/

Or ask the [reddit.tube](https://www.reddit.tube/) dev for the API access cuz it also optimizes the mp4 file.

**Comment by Docile-Alligator** [comment]
This is because the reddit separates video and audio on its server.

**Comment by yephny** [comment]
@Docile-Alligator Is this why Infinity downloads some videos without audio?
