### ISSUE TITLE
[BUG] Cannot modify favourite subreddits in subscriptions

### ISSUE THREAD

**Issue by austinhuang0131** [Docile-Alligator/Infinity-For-Reddit#333]
Favourited subreddits revert to original on refresh after modifications (add/remove) which does not come back even after relaunch. So it probably didn't save.

4.3.0-beta3, Android 9.

**Comment by Docile-Alligator** [comment]
Will be fixed in 4.3.0-beta4. Thank you.

**Comment by austinhuang0131** [comment]
Seems like it's indeed fixed.
