### ISSUE TITLE
[Feature][Privacy] Remove WRITE_EXTERNAL_STORAGE permission for Android 10+(sdk29+)

### ISSUE THREAD

**Issue by Blocked** [Docile-Alligator/Infinity-For-Reddit#336]
In Android 10 and 11, It seems  that the app is requesting storage permission to download videos and images using the download button on the top right. If denied, a popup displays "No storage permission to save file". However, the [documentation](https://developer.android.com/training/data-storage/shared/media#request-permissions) says

>Don't unnecessarily request storage-related permissions for devices that run Android 10 or higher. Your app can contribute to well-defined media collections, including the MediaStore.Downloads collection, without requesting any storage-related permissions. If you're developing a camera app, for example, you don't need to request storage-related permissions because your app owns the images that you're writing to the media store.

So, the permission is not needed, if you use Mediastore, which I believe the app already uses.

**Comment by Blocked** [comment]
Maybe there's a simple fix?

https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/ee4c25a465e2568ab3ed784e60cba8d2e3caa40b/app/src/main/AndroidManifest.xml#L21

To

    <uses-permission-sdk-23 android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28"/>

**Comment by Docile-Alligator** [comment]
Thank you. Done.
