### ISSUE TITLE
[BUG] Pressing the upvote/downvote buttons in quick succession throws a 429 error.

### ISSUE THREAD

**Issue by YuvalAmir1** [Docile-Alligator/Infinity-For-Reddit#339]
When I press the upvote/downvote buttons in quick succession I get two small pop ups at the bottom of my screen:
1. Vote failed
2. Code 429 Body: null

**Comment by tegutistgut** [comment]
Yes. I can reproduce this and im getting this error since a long time.

And i cant reproduce this on boost for reddit
