### ISSUE TITLE
Feature request: Imgur and external images view support

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#34]
for image visualization, some posts often directs you to Imgur for viewing the image, but i think it would be better if these images and other direct links for images could be viewed directly from the app.

what do you think? :3

**Comment by Docile-Alligator** [comment]
I think it's very good!

**Comment by goodevilgenius** [comment]
I switched to this app from BaconReader mainly because I wanted a FOSS app, and displaying images inline seems like a basic feature. It definitely seems needed to me.

**Comment by Docile-Alligator** [comment]
I know. I will add this feature but I have to implement other customizations and features first.

**Comment by Docile-Alligator** [comment]
Done. This feature will be released in the next update.
