### ISSUE TITLE
anti-gif-bot videos don't play

### ISSUE THREAD

**Issue by rharish101** [Docile-Alligator/Infinity-For-Reddit#343]
I'm guessing this is related to the way the bot formats it's links. Here's an example: https://www.reddit.com/r/HydroHomies/comments/nak0nd/me_at_3_am/gxtzdvq/. However, I can download the video and play it locally.

Infinity version: 4.2.5 F-Droid

**Comment by Wladefant** [comment]
Antigifbot is not on reddit anymore
