### ISSUE TITLE
[BUG] Video doesn't stop playing even after I've exited it

### ISSUE THREAD

**Issue by shivangc22** [Docile-Alligator/Infinity-For-Reddit#346]
The video continues to play even after I've exited the video screen and am back to browsing my feed.

**Comment by guillemglez** [comment]
Happens to me since updating to 4.3.0.

**Comment by rharish101** [comment]
The only workaround I've found is to open the Recents menu and go back to Infinity. This stops the video. Otherwise, this is really annoying.

**Comment by Docile-Alligator** [comment]
Fixed in v4.3.2.
