### ISSUE TITLE
[Feature] Display Comment Gifs Automatically

### ISSUE THREAD

**Issue by 0rdinant** [Docile-Alligator/Infinity-For-Reddit#347]
Currently gifs in comments [such as these](https://www.reddit.com/r/sbubby/comments/myz4f9/based_on_the_hit_video_game/gvyyqql/) appear as links instead of appearing in the comments themselves. Would there be a way to do this without using excessive resources?

**Comment by Docile-Alligator** [comment]
Currently I don't know how to implement this. But I will try.

**Comment by Wladefant** [comment]
Duplicate of #935
