### ISSUE TITLE
Infinity doesn't shows my posts.

### ISSUE THREAD

**Issue by tegutistgut** [Docile-Alligator/Infinity-For-Reddit#348]
_deleted_

**Comment by Docile-Alligator** [comment]
Did you enable NSFW? Could you go to reddit.com and see if your posts are all there?

**Comment by tegutistgut** [comment]
> Did you enable NSFW? Could you go to reddit.com and see if your posts are all there?

Yes NSFW is enabled and i can see my posts on reddit.com (also on old.reddit.com and i.reddit.com, both mobile and Desktop version)
