### ISSUE TITLE
[BUG] Bottom navigation bar is glitched for me

### ISSUE THREAD

**Issue by AlmightyWings232** [Docile-Alligator/Infinity-For-Reddit#349]
The bottom navigation bar seems to be glitched, because it isn't shown properly. I've attached a video showing the glitch
### Environment

- Device: Honor Play (COR-L29)
- Android version: 9 (EMUI Version 9.1.0)
- App version: 4.3.0
- (Might want to note that my phone has a notch, but I've chosen to hide the notch in the settings. That may be interfering with it somehow, but not too sure)

https://user-images.githubusercontent.com/44907494/119015110-830c9080-b990-11eb-93e8-bcc86ef55992.mp4

**Comment by AlmightyWings232** [comment]
Nvm, I can fix the normal interface by enabling the setting 'Ignore Navigation Bar in Immersive Interface' option but the issue with the + icon hovering in subreddits still exists. Also, what's Immersive Interface anyways? I don't notice a difference with it on/off

**Comment by Docile-Alligator** [comment]
Immersive Interface is to show content under nav bar and status bar.

**Comment by AlmightyWings232** [comment]
Oh, right. Thank you for informing me
