### ISSUE TITLE
Subreddits aren't being blocked from r/all or r/popular

### ISSUE THREAD

**Issue by Mhowser** [Docile-Alligator/Infinity-For-Reddit#351]
If I make a new filter rule to block r/politics for example, it still shows up when browsing all and popular. I suggest adding a feature where a user could simply long tap on a subreddit to quickly filter it from their feed.

**Comment by Docile-Alligator** [comment]
Did you apply this filter to r/all and r/popular?

**Comment by Mhowser** [comment]
Where is that option? These are all I see
![Uploading Screenshot_20210528-104326.png…]()

**Comment by Mhowser** [comment]
No I forgot to do that
