### ISSUE TITLE
[BUG] Latest update broke swipe to vote in comments

### ISSUE THREAD

**Issue by jayrfs** [Docile-Alligator/Infinity-For-Reddit#352]
latest update has swipe to switch between posts feature which conflicts with swipe to vote (in comments).

1. if swipe between posts is enabled, swipe between posts and swipe to vote (in comments) conflict each other. 

solution: make swipe between posts only work when swiped on self text/image/video of post and not on comments.

2. If swipe to vote is disabled, swiping left or right still fail to trigger votes on random (while on comments). they simply display a half transition on left or right side of the screen depending on the direction of swipe.

**Comment by selfrisingfloor** [comment]
d

**Comment by Docile-Alligator** [comment]
Ok. I will look into it.

**Comment by selfrisingfloor** [comment]
here's a video of the bug in action

https://youtube.com/shorts/QJ5ZkF-w-s4?feature=share
