### ISSUE TITLE
[Feature request] add more privacy related features

### ISSUE THREAD

**Issue by givena** [Docile-Alligator/Infinity-For-Reddit#355]
add more features that are more privacy related like backups, local multireddit other features that require an account

**Comment by Docile-Alligator** [comment]
Hi, do you mean backup settings?

**Comment by iMAOUely** [comment]
+1 for this feature.
It's a drag setting up on new devices and having to manually go and subscribe to each subreddit again.
It would make sense to implement it into the 'Backup settings' option under 'Advanced'.
Great app however, appreciate all your work on it!

**Comment by flexagoon** [comment]
I think the Stealth client might be what you want

https://f-droid.org/packages/com.cosmos.unreddit/

**Comment by Joao-Felisberto** [comment]
I would also like more privacy oriented features. 
There are several requests for these features in many issues, namely libredit (#547), tor (#638) and full offline accounts (#399).

I would love to try and implement some in prs. I've never contributed to open source before and have very litle experience with Android development, so my contributions may be scarse and slow, but if some of these issues are wanted I would gladly try my best to implement them.

**Comment by Wladefant** [comment]
Please add every request to its own post, so we can go by priority and decide what will be and what will be not implemented.
