### ISSUE TITLE
[Bug] Inbox unread count not refreshing after read

### ISSUE THREAD

**Issue by KaKi87** [Docile-Alligator/Infinity-For-Reddit#357]
Hello,

The inbox menu item features a counter.

We would assume that it counts unread messages.

But, when reading a message, the counter doesn't reset.

Actually, the counter only resets after replying.

Thanks

**Comment by Docile-Alligator** [comment]
Hi. I think it only resets after you restart the app.

**Comment by KaKi87** [comment]
Actually, the counter persists after app restart and even device restart.

**Comment by KaKi87** [comment]
I just opened Reddit on browser for the first time since a week, and realized the inbox was actually still in unread state.

So the issue isn't that Infinity counts unreplied messages, but that it doesn't mark messages as read before replying to those.

Thanks

**Comment by KaKi87** [comment]
Hello, I don't know about my original issue, but I'm definitely experiencing this now :
> it only resets after you restart the app

Therefore I renamed the issue accordingly and am looking forward to its resolution.
Thanks

**Comment by Docile-Alligator** [comment]
I think this is fixed. Could you check it again?

**Comment by Docile-Alligator** [comment]
Fixed.
