### ISSUE TITLE
When view album/gallery, third picture doesnt load

### ISSUE THREAD

**Issue by Offerel** [Docile-Alligator/Infinity-For-Reddit#360]
Currently I try to evaluate some reddit clients, which one fits better my needs. Sometimes one of the pictures didn't load. It shows only the spinner forever. However, if i save the picture, it is saved correctly to the device. 

Example post: https://www.reddit.com/r/elderscrollsonline/comments/nnjwgj/mip_load_skip_levels_texture_quality_comparison_6

the 3 image shows only the spinner. The images are displayed all correct in other clients.

**Comment by Docile-Alligator** [comment]
Yes. I am aware of this issue but still don't know why this happens.

**Comment by Docile-Alligator** [comment]
Fixed.
