### ISSUE TITLE
[Feature request] Accountless/Lurker mode

### ISSUE THREAD

**Issue by gnu1dea** [Docile-Alligator/Infinity-For-Reddit#364]
Please provide an option in the preferences **to hide all features in the interface** that require an account (Up/downvote, give Award, etc.) **+ all the preferences** that are only useful with an account.
(Maybe a more elegant solution would be to just hide it all by default unless an account is used and then unhide the additional features?)

Also related to the _accountless_ UX: Please make the preference _Customize tabs in main page_ not depend on an account.
I'd like to add/delete/reorder tabs (like the already existing _Home_, _Popular_, _All_) to use as themed tabs/multireddits.
(related issues: Local multireddit https://github.com/Docile-Alligator/Infinity-For-Reddit/issues/287 https://github.com/Docile-Alligator/Infinity-For-Reddit/issues/355)

**Comment by gnu1dea** [comment]
Related: #399

**Comment by Docile-Alligator** [comment]
I think I will let you customize tabs in anonymous mode first.

**Comment by S21ULTRA512** [comment]
> I think I will let you customize tabs in anonymous mode first.

So you still need an account? Well damn! I really want an option to customize the tabs without need of an account.

**Comment by BobIsMyManager** [comment]
> > I think I will let you customize tabs in anonymous mode first.
> 
> So you still need an account? Well damn! I really want an option to customize tabs without need of an account.

Anonymous mode is like a local account: you dont have to log into reddit

**Comment by Docile-Alligator** [comment]
@S21ULTRA512 no you don't need an account

**Comment by Docile-Alligator** [comment]
You can now customize tabs in anonymous mode in v5.1.0.
