### ISSUE TITLE
Still can't enter a Subreddit

### ISSUE THREAD

**Issue by jhoc2000** [Docile-Alligator/Infinity-For-Reddit#365]
I can't see anywhere to add a Subreddit. This app is useless without being able to do that.

**Comment by Docile-Alligator** [comment]
Add a subreddit?

**Comment by jhoc2000** [comment]
Yes. For instance slideforreddit.

**Comment by Docile-Alligator** [comment]
Just go to a subreddit and click Subscribe.

**Comment by jhoc2000** [comment]
How does one 'go to a Subreddit'?
