### ISSUE TITLE
Some images can't be displayed in zoom mode 

### ISSUE THREAD

**Issue by huupoke12** [Docile-Alligator/Infinity-For-Reddit#366]
While the image displayed fine in thumbnail, but when clicking on the image to view it, it doesn't display.
Some examples:
* https://www.reddit.com/r/EntitledBitch/comments/nqqfqp/gold_digger/
* https://www.reddit.com/r/dataisbeautiful/comments/la7p3m/oc_i_tracked_one_year_of_sex_with_my_partner/
* https://www.reddit.com/r/gaming/comments/nrbpt3/i_miss_wow/
* https://www.reddit.com/r/TIHI/comments/nrpso1/thanks_i_hate_that_patrick_can_legally_kill/

**Comment by Docile-Alligator** [comment]
Cannot reproduce this.
