### ISSUE TITLE
Refresh button doesn't send feed to start (4.3.3)

### ISSUE THREAD

**Issue by ldsreo** [Docile-Alligator/Infinity-For-Reddit#367]
As far as version 4.3.1, pressing the refresh button caused two things: feed was refreshed, and feed was automatically sent to the start again. However, on version 4.3.3, only the former happens. This kind of makes the "refresh" action useless, since the user has to scroll all the way to the top of the feed in order to see the new posts.
Issue noticed by u/mr_bigmouth_502 : [https://www.reddit.com/r/Infinity_For_Reddit/comments/nteq2q/feature_request_go_to_top_button_for_front_page/
](url)

**Comment by kgorol** [comment]
Refresh seems to work only sometimes for me, as it does not even refresh the page with new items. The only way sometimes to get the newest entries is to restart the app.

**Comment by Linecutterx** [comment]
Came here to all about refresh too, but it may be a different issue.
I've found a workaround, for multi-reddits at least: hit the filter button & chose the filter that you want (even the same one as you have already).

**Comment by Docile-Alligator** [comment]
This is because I updated the pagination library. This behaviour is controlled by this library.
