### ISSUE TITLE
A few quick feature requests and usability improvements

### ISSUE THREAD

**Issue by karan** [Docile-Alligator/Infinity-For-Reddit#371]
Coming from Slide and I like the simplicity of Infinity. I would appreciate the following if devs like it:

1. On home page (or any list of posts), add a "Hide post" button. Maybe next to the comment count or share icon.
2. Grey out read posts. As it is, it's hard to quickly skim to new posts only
3. Pin favorite multireddits to left sidebar

**Comment by karan** [comment]
I believe 1 is dupe of #174

**Comment by Wladefant** [comment]
The second feature is already implemented but not as default

Go to settings>post history and there are different toggles you could enable
