### ISSUE TITLE
Hide post from feed more dynamically

### ISSUE THREAD

**Issue by karan** [Docile-Alligator/Infinity-For-Reddit#372]
I'm in a feed (home, subreddit, or multi), and click through to a post them hide that post.

Then I go back to the feed, I expect the post to be hidden from there. Instead, it's only hidden on a refresh.

Related to #174, it would be nice to be able to quickly and more dynamically hide posts (remove the card without refresh).

**Comment by Wladefant** [comment]
This request is implemented: settings>interface>post history>hide read posts automatically

**Comment by karan** [comment]
My request is different. Basically my request is to remove the post from the UI dynamically (how Slide and native Reddit UI does it). Right now, Infinity requires a refresh of the UI to hide the post

**Comment by Wladefant** [comment]
Ok @karan understood
