### ISSUE TITLE
Show different icons for Reddit Gold/Silver/Platinum and distinguish yourself in a comment thread

### ISSUE THREAD

**Issue by rpartha** [Docile-Alligator/Infinity-For-Reddit#38]
1. Currently, there exists no way to distinguish whether person was given Gold, Silver, or Platinum. 
2. There should be an icon next to or highlight on your username to easily identify yourself in a comment thread

**Comment by Docile-Alligator** [comment]
Good ideas!

**Comment by OHermesJunior** [comment]
Done. Except in the feed it doesn't show specific awards, only "X awards". Plans to improve it?
