### ISSUE TITLE
Can't press on "Posts" and "Comments" text on your profile

### ISSUE THREAD

**Issue by lnwor** [Docile-Alligator/Infinity-For-Reddit#380]
I noticed this thing a while back but I never thought about reporting it.
It's a minor issue, but when you are on the "profile" section and you try to switch between posts and comments, pressing directly on the text that says "Posts" and "Comments" doesn't trigger the switch, while the whole area around the text does.
![image](https://user-images.githubusercontent.com/43646324/121809256-719b6900-cc5c-11eb-8316-aae901b58a05.png)

**Comment by Docile-Alligator** [comment]
Oh thank you for reporting this.

**Comment by Docile-Alligator** [comment]
Fixed.
