### ISSUE TITLE
Implemention of polls and posting multiple photos in a row

### ISSUE THREAD

**Issue by firefoxlover** [Docile-Alligator/Infinity-For-Reddit#382]
Hi, I absolutely love the app!
Its just perfect, so customizable and powerful, a good alternative to the website and the regular app is nothing in comparison.

Just those two things dont work, posting multiple photos and viewing polls, for polls I always have to go to the website itself.

Keep than cool app running please! Where can I donate?

**Comment by Docile-Alligator** [comment]
You can now submit a post with multiple images. Polls are only available in the official reddit app.
You can donate in https://www.patreon.com/docile_alligator or using bitcoin: bc1qxtkd5ap9na7uy8nr9qpt6jny6tdwaj4v43ddle Thank you.
