### ISSUE TITLE
[Feature Request] Cropped previews card layout

### ISSUE THREAD

**Issue by cantunborn** [Docile-Alligator/Infinity-For-Reddit#386]
Full image or video can be viewed by tapping.

**Comment by Docile-Alligator** [comment]
OK.

**Comment by Alvie** [comment]
Yeah... Some of the images posted (especially if it's an entire screenshot) takes up the entire view. It'd be nice if after a certain amount of vertical pixels, it gets cropped.

I really like the card layout but some images take too much space, and I don't really like the compact layout as much.

**Comment by Docile-Alligator** [comment]
Done.
