### ISSUE TITLE
[Feature request] User profile icon.

### ISSUE THREAD

**Issue by JustCauseWhyNot** [Docile-Alligator/Infinity-For-Reddit#387]
In the offical app you are able to see the users profile picture when they leave a comment. I don't believe this app has that functionality. I have looked thoroughly through the settings and haven't seen any setting related to user profile icon. I hope my request makes sense.

**Comment by Docile-Alligator** [comment]
Ok. Will try.

**Comment by JustCauseWhyNot** [comment]
Thank you.

**Comment by nathanfranke** [comment]
Was this resolved?
