### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by EchoKat** [Docile-Alligator/Infinity-For-Reddit#39]
- Alphabetical Index for Subscriptions: It is a bit of a pain to scroll through all of your subscriptions to get to the one you need - especially if you have a long list. Implementing a alphabetical index on the side of the tab would make it easier to navigate through all of your subscriptions.

- Tap comment to fully collapse them.

- Autoplay videos and gifs

**Comment by Docile-Alligator** [comment]
Thank you for these suggestions!

**Comment by Docile-Alligator** [comment]
Done.
