### ISSUE TITLE
Can't play redgifs videos.

### ISSUE THREAD

**Issue by SIA23** [Docile-Alligator/Infinity-For-Reddit#393]
Although sometime it plays, but not of the time it's broken. 

![IMG_20210625_215846](https://user-images.githubusercontent.com/86543269/123532000-11f88f80-d72b-11eb-8414-f4aaf5195f48.jpg)

**Comment by Docile-Alligator** [comment]
Hi could you send me the post link?

**Comment by SIA23** [comment]
Here's one [NSFW] (duh)
https://www.reddit.com/r/GenshinImpactHentai/comments/ns2i3d/redgifs/

**Comment by tegutistgut** [comment]
> Here's one [NSFW] (duh)
> https://www.reddit.com/r/GenshinImpactHentai/comments/ns2i3d/redgifs/

💀💀💀

**Comment by tegutistgut** [comment]
But jokes aside. Your isp or your DNS provider probably blocked adult sites.

**Comment by Docile-Alligator** [comment]
I can watch the video with no problem.

**Comment by tegutistgut** [comment]
> I can watch the video with no problem.

Same

**Comment by ishridharhegde** [comment]
I still have this issue on v5.1.5

**Comment by freesra** [comment]
Still an issue on 5.1.9. It's intermittent though. Some days it works, others it doesn't.

**Comment by sidillicitaf** [comment]
Still the same issue exists and It is totally random, also unrelated to DNS / IP

**Comment by Mac-or-Mac** [comment]
Same here, was using Express VPN both on and off, still shows "fetch redgifs video faild" only started to notice the last couple of days. But it's practically all posts now involving redgifs.

**Comment by removed0** [comment]
same problem
