### ISSUE TITLE
Wrong content showing in second tab when tab count set to 1

### ISSUE THREAD

**Issue by OliverLew** [Docile-Alligator/Infinity-For-Reddit#397]
Reproduce:
1. Go to Settings > Interface > Customize Tabs in Main Page.
2. Set "Tab Count" to 1, and turn on "Show Multireddits" at bottom. The 2nd and 3rd tab by default are "popular" and "all".
3. Reopen Infinity, you should see more than two tabs.
4. Switch to second tab, you should see not the actual multireddit, but the content of "tab 2", which by default is "popular".

Environment:
OS: LineageOS 18.1, based on Android 11
App: Infinity 4.3.4 from f-droid

**Comment by Docile-Alligator** [comment]
Thank you for reporting this.

**Comment by Docile-Alligator** [comment]
Fixed.
