### ISSUE TITLE
Feature Request: Double-Tap to Upvote

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#4]
This is a feature I liked in Joey for Reddit, the ability to double-tap comments and posts to upvote them, and triple-tap to downvote.

**Comment by Docile-Alligator** [comment]
Hi, thanks for the advice! I will add this feature but for now, I have to focus on fixing bugs.

**Comment by Docile-Alligator** [comment]
Double-tap comments to upvote will make clicking links impossible.

**Comment by BeeeWall** [comment]
Ok, thanks for checking if you could do it.

**Comment by mr-september** [comment]
Was this ever implemented?
