### ISSUE TITLE
Feature req: Render markdown tables

### ISSUE THREAD

**Issue by austinhuang0131** [Docile-Alligator/Infinity-For-Reddit#40]
Currently left as text.

**Comment by Docile-Alligator** [comment]
Yes. I have not found a way to implement it.

**Comment by Wilker-a** [comment]
on a quick lookup i found [this library](https://github.com/GrenderG/MarkdownView) under the license GNU LGPL. does it help with anything? :3

**Comment by Docile-Alligator** [comment]
Hi! I already implemented rendering markdown tables in the last update (2.1.0).
