### ISSUE TITLE
[BUG] Videos not downloading on certain devices (Xiaomi)

### ISSUE THREAD

**Issue by cantalisa** [Docile-Alligator/Infinity-For-Reddit#409]
Hi. I am transitioning devices. I have a Samsung where I can download the videos and they are instantly in the gallery, with absolutely no problem. However, I have noticed that on another device, a Xiaomi Redmi 9C, the downloaded videos cannot be played; what's even more, they are completely black and have a duration of 0 seconds.

Something strange but reproducible. At least on my device, since it does not download any video at all, while the other has no problem. Both of them have the same Infinity version, from F-Droid, they have required permissions. I have uninstalled and reinstalled. But it's a strange bug. I don't know if useful, but the Redmi is Android 10.

If I can provide more info, I'll do it with pleasure. Cheers.

**Comment by Wladefant** [comment]
@cantalisa Is this still an issue?
