### ISSUE TITLE
Blocking users always fails

### ISSUE THREAD

**Issue by deoxal** [Docile-Alligator/Infinity-For-Reddit#411]
Whenever I try to block someone, a toast appears that says "Failed to block user".

Is there any way to fix this?

**Comment by Docile-Alligator** [comment]
I will look into it.

**Comment by Docile-Alligator** [comment]
Cannot reproduce this issue.

**Comment by deoxal** [comment]
Recently got a new phone and it works fine. Just tested it again on my old one and it still doesn't work there.

My new phone is a Zenfone 6 and my old one is a Moto G5+.

So how can I create a log and send it to you?

**Comment by distinguishedrevolver** [comment]
Unable to block user. 

Pixel 6, app updated and fresh from store. Process to block- select user, land on their page, use the right hand menu to select block. Bubble notification indicates user is blocked. Return to thread, user still present. Rebooting does not solve.

**Comment by sunfiwtn** [comment]
Is there any news on this? Issue is still present as of 5.2.1

**Comment by Wladefant** [comment]
Reddit has a limit of 5000 blocked users. Is this maybe a problem?

**Comment by sunfiwtn** [comment]
> 

I only have 6 people blocked, all from desktop as well

**Comment by deoxal** [comment]
No definitely not. It's device specific, it works on my current phone with Android 11 but not my old one with Android 8.

**Comment by Wladefant** [comment]
It should not work anymore because reddit does not allow third parties to use their apis: https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/6f4e9233b8bcda7054c505fb00f780e27e794b84
