### ISSUE TITLE
app randomly crashes/ exits subreddit

### ISSUE THREAD

**Issue by random0125** [Docile-Alligator/Infinity-For-Reddit#413]
I recently downloaded the app like 2 days ago, and ever since then I've had the app randomly crash multiple times, as well as have the subreddit I'm on randomly close out. There's nothing specific that causes it. I'll be browsing and then suddenly the app crashes, or whatever post I'm on exits and takes me back to the home page.

I'm on the latest version of Android on a OnePlus 8T, if that's of any help. Also I have checked the app store for updates, and tried uninstalling but that doesn't work either.

**Comment by Docile-Alligator** [comment]
Hi could you go to Settings->Advanced->Crash Reports and send the crash log to me?
