### ISSUE TITLE
Comment divider for only top level comments

### ISSUE THREAD

**Issue by cantunborn** [Docile-Alligator/Infinity-For-Reddit#417]
Without comment dividers, top level comments are hard to differentiate from child comments. But comment dividers clutter the UI when applied on all comments and are not really necessary because of identation lines. Comment divider can have a toggle for applying only between top level comments.

**Comment by DanWlker** [comment]
Made a preliminary implementation for this, but not sure why the dividers are appearing on other levels when the logs correctly detect the level where the divider needs to be placed

**Comment by Wladefant** [comment]
Out of scope

**Comment by Docile-Alligator** [comment]
Done https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/67b6906ead02ceb7d7e46f28ae5c27a510956038
