### ISSUE TITLE
Maybe connect the new post button to the bottom bar, and make it red

### ISSUE THREAD

**Issue by PopeRigby** [Docile-Alligator/Infinity-For-Reddit#42]
The grey new post button floating a few centimeters away from the bottom bar doesn't fit the design of the rest of Infinity,  in my opinion. I think connecting it and making it that soft red color would look nicer.

**Comment by Docile-Alligator** [comment]
Thank you. This is what the default layout looks like. I may check if I can change the position of the FAB.

**Comment by Jnss98b** [comment]
A bottom app bar with an inset fab is totally fine though

**Comment by Wilker-a** [comment]
maybe a customizable secondary color with a couple of presets would be nice too :3

**Comment by Jnss98b** [comment]
Or an RGB color picker

**Comment by Docile-Alligator** [comment]
I will start implementing different themes after I finished implementing some requested customizations.

**Comment by Docile-Alligator** [comment]
Done.
