### ISSUE TITLE
Sometimes some preview or posts don't load the images correctly

### ISSUE THREAD

**Issue by ghost** [Docile-Alligator/Infinity-For-Reddit#428]
It's one of the most annoying things on existence, but atleast is a workaround wich is clicking on the share icon, pasting it to a web browser an enjoying the picture.
It's a very frecuent bug
Here is my device btw:
Android 7.0 (sdk 24)
No google services installed, Netguard (excluded because troubleshooting)
Wwbview Multiprocess (not sure if this has something to do, but increases privacy)
2D acceleration
yes, I rebooted the phone and my internet connection is fine and working flawlessly.
Here are some screenshots:

![Screenshot_20210804-233349](https://user-images.githubusercontent.com/87635958/128295471-1454de79-1178-4bfc-a47e-c930a9603c3f.png)

![Screenshot_20210805-001223](https://user-images.githubusercontent.com/87635958/128295500-5b9e817f-15ec-43b1-9e62-9a70c729d96e.png)

![Screenshot_20210805-001322](https://user-images.githubusercontent.com/87635958/128295533-8fad1262-3f4f-4f07-8128-727a275a87a6.png)

![Screenshot_20210805-001439](https://user-images.githubusercontent.com/87635958/128295618-a2a13767-f8ed-445f-ba55-5886a4313674.png)

![Screenshot_20210805-001508](https://user-images.githubusercontent.com/87635958/128295644-ba64f824-343f-4b15-a31b-4793b5777e4d.png)

![Screenshot_20210805-001523](https://user-images.githubusercontent.com/87635958/128295670-de13f2c2-6fd5-4d26-af04-56510e64282b.png)

![Screenshot_20210805-001526](https://user-images.githubusercontent.com/87635958/128295688-2808cea4-4251-4db1-8842-8cd2c3d70725.png)

this bug is pretty wild, please fix it or guide me to provide logs for more troubleshooting

**Comment by JustVictor17** [comment]
I've cleared the cache, go find the same gallery post, same issue, is very very reproducible

**Comment by JustVictor17** [comment]
The bug still happens on current latest Beta build 5.04
Please fix it...!!

**Comment by JustVictor17** [comment]
The bug persists on Beta 5.05

**Comment by JustVictor17** [comment]
Bug persists on current 5.0.2

**Comment by Diridibindy** [comment]
I also have the same issue. Sometimes Infinity throws out some java exception. Something related to it not being able to connect to the preview server. The image itself loads just fine after tapping on it. The problem is only with the preview. I also have a degoogled phone.

**Comment by Wladefant** [comment]
Please label this issue as a bug

**Comment by Wladefant** [comment]
Does it happen to all image sources or only specific?
