### ISSUE TITLE
Stuck notification after update to 5.0.0-beta2

### ISSUE THREAD

**Issue by cdysthe** [Docile-Alligator/Infinity-For-Reddit#429]
After update to 5.0.0-beta2 I have a notification from Infinity I do not know what is and which can't be removed. If I kill Infinity the notification is back as soon as I run Infinity again. See screenshot 

https://imgur.com/a/xfGN0Ur

**Comment by KaKi87** [comment]
Duplicate of #420

**Comment by bczsalba** [comment]
> Duplicate of #420

It's not.

**Comment by Docile-Alligator** [comment]
Fixed.
