### ISSUE TITLE
[Bug] The FAB doesn't return to its original position after scrolling up

### ISSUE THREAD

**Issue by Jnss98b** [Docile-Alligator/Infinity-For-Reddit#43]
It overlaps the bottom app bar after one or two hide/unhide cycle

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24306400/71452540-f9817080-2753-11ea-8d92-0c828e6abda0.gif)

**Comment by Docile-Alligator** [comment]
Hi. This may not be solvable because I declare this behavior directly in the layout file. This app hides both the plus button and the bottom bar when scrolling down. So maybe the system gives a wrong position to the plus button after it reappears. Anyway, I will add an option to disable the bottom navigation in the next release.

**Comment by Jnss98b** [comment]
Disabling the bottom bar would be the last thing I want to do since I actually do use it. Is there no better way to implement it? This is a standard material design component after all. Make the FAB bound to the bottom app bar instead of the bottom edge of the screen for example. Or maybe add a toggle to not hide the FAB at all, just the bottom bar (This is actually the recommended behavior as outlined in MD guidelines btw).

**Comment by Jnss98b** [comment]
> Or maybe add a toggle to not hide the FAB at all, just the bottom bar (This is actually the recommended behavior as outlined in MD guidelines btw).

![PFhnvAL9M0](https://user-images.githubusercontent.com/24306400/71551997-1c648c80-29c1-11ea-8ade-44a8a192b596.gif)

**Comment by Docile-Alligator** [comment]
Yes. It is the recommended behavior but it will hide some of the content if there is a network error since a error view will be shown in the bottom.

**Comment by Jnss98b** [comment]
Then just show it in front of or on top of the bottom bar. Warnings are supposed to be on top of any app interface anyways

**Comment by Docile-Alligator** [comment]
Good idea. Haven't thought of that.

**Comment by Jnss98b** [comment]
I just wanted to give an update on this issue. I recently switched to a new phone, Pixel 4 XL and I still get this bug, although only rarely now.

Also, are you only insetting the FAB and the bottom of the display area? Maybe that's the issue. You should also include the bottom app bar in calculating the margin of the FAB too

**Comment by Docile-Alligator** [comment]
I anchor the fab to the bottom navigation bar.
