### ISSUE TITLE
add Chat Feature

### ISSUE THREAD

**Issue by DraconicNEO** [Docile-Alligator/Infinity-For-Reddit#430]
It would be great if there was access to the Chat feature in Infinity. I'm sure more people would switch to Infinity if there was access to the chat feature. Currently it's the only big reason to keep using the Stock app.

Edit: Just noticed that this was mentioned in #198 although it doesn't seem like that one went anywhere.

**Comment by katacarbix** [comment]
Afaik there's no API for chat, so it can't be natively implemented. It would be possible to wrap the website inside a section of the app but at that point it would probably just be easier to use a web browser. It may be worth keeping this issue open in case it does end up being added to the API.

**Comment by Docile-Alligator** [comment]
Hi Reddit chat is only available in the official app. There is no public API for this.

**Comment by DraconicNEO** [comment]
> 
> 
> Hi Reddit chat is only available in the official app. There is no public API for this.

How is it available in the browser?
