### ISSUE TITLE
[BUG] Video Donwload Error

### ISSUE THREAD

**Issue by 123-bott** [Docile-Alligator/Infinity-For-Reddit#431]
I tried downloading a video but the saved video are empty (0.00 bytes). Just like or similar to the issue #409.

I don't know what's the problem but here are my device specification:

Brand/Model: Vivo Y53
Android Version: 6.0.1
Files Location: /SD Card/Pictures/Infinity/[Subreddit Name]/[File]

Edit: I just noticed that the audio and video are combined together after downloading both, maybe the muxer is/has a problem. Downloading pictures works.

**Comment by Docile-Alligator** [comment]
I guess it's because of the muxer too.

**Comment by Wladefant** [comment]
https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/974730db1a6769bb34db54789d7818acf85a3edc
