### ISSUE TITLE
[Bug] Mark read crashing app 

### ISSUE THREAD

**Issue by wikd** [Docile-Alligator/Infinity-For-Reddit#434]
Whenever I have a lot of read posts I click hide read and the app just crashes. If I have auto hide read on with a lot of read posts it crashes.

I am on lineage Android 11 64 bit.

**Comment by Docile-Alligator** [comment]
This will probably be fixed in v5.1.0. I have changed the implementation of hiding read posts. You can try it then.

**Comment by Docile-Alligator** [comment]
@wikd Does this problem still exist in v5.1.0?

**Comment by wikd** [comment]
Can confirm this bug no longer exists. App works fantastic now.
