### ISSUE TITLE
Emojis appear through spoiler tags

### ISSUE THREAD

**Issue by gabmiral** [Docile-Alligator/Infinity-For-Reddit#435]
Version : Infinity 5.0.0-beta5

OS Version : MIUI Global 12.1.1 (Android 11)

Theme : AMOLED Dark

In text contained inside spoiler tags, emojis won't be hidden even though the text is hidden.

Example here : https://www.reddit.com/r/u_Gabmiral/comments/p3npj5/another_issue_regarding_spoiler_tags/

**Comment by gabmiral** [comment]
Side note : replying to a message which contains spoiler text will not apply the markdown of the spoiler, revealing it's content in the comment edition field. If the spoiler tag is in start of line, the comment will appear as quoted because of the leading `>`

**Comment by Docile-Alligator** [comment]
> Side note : replying to a message which contains spoiler text will not apply the markdown of the spoiler, revealing it's content in the comment edition field. If the spoiler tag is in start of line, the comment will appear as quoted because of the leading >

This is fixed.

The emoji problem will not be fixed. This is how emoji works.
