### ISSUE TITLE
Feature Request: Synccit Support

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#44]
[Synccit](https://synccit.com/) allows syncing read posts between Reddit apps/website/etc. Could be useful to have. There's an Android library [here](https://github.com/talklittle/synccit-android), if you'd rather that to the [web API](https://github.com/drakeapps/synccit/wiki/API).

**Comment by Docile-Alligator** [comment]
Old library. It's viable but I don't think I will implement it soon.
