### ISSUE TITLE
Provide Changelogs & Provide Changelogs To F-Droid

### ISSUE THREAD

**Issue by seniorm0ment** [Docile-Alligator/Infinity-For-Reddit#448]
I notice there are no changelogs on the Github releases, I am highly suggesting adding changelogs so users know what is being changed.

Furthermore, When updates are pushed to F-Droid, it doesn't show any changelogs.
Suggesting adding the changelogs to F-Droid.

**Comment by Docile-Alligator** [comment]
Not sure how to add changelogs in fdroid but I have been adding changelogs to GitHub since v5.1.0.

**Comment by seniorm0ment** [comment]
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
