### ISSUE TITLE
Subreddit 'SIDEBAR' text weird

### ISSUE THREAD

**Issue by EncryptedCicada** [Docile-Alligator/Infinity-For-Reddit#449]
When viewing a subreddit, the sidebar text os not as it is supposed to be. Screenshot for reference:
![Screenshot_20210827-182959_Infinity](https://user-images.githubusercontent.com/52757733/131555696-d5e36dfc-9ca3-4e01-aec0-8c4a684adfb4.png)

Happens with every sub so it isn't sub specific. Didn't happen earlier as I've been using infinity for a long time. Cheers for the great app nevertheless :)

**Comment by Docile-Alligator** [comment]
I will change it to "About"
