### ISSUE TITLE
Fab is all over the place

### ISSUE THREAD

**Issue by 1chriis1** [Docile-Alligator/Infinity-For-Reddit#45]
It's in the top left!

![Screenshot](https://i.imgur.com/KdpTiWs.jpg)

**Comment by Docile-Alligator** [comment]
Haha I noticed it too. A fix will be in the next update. For now, you can log in to Reddit.

**Comment by Docile-Alligator** [comment]
Fixed in version 2.2.0.

**Comment by 1chriis1** [comment]
Thanks for fixing that!
