### ISSUE TITLE
[Feature Request] Let streamable videos use Infinity's video player

### ISSUE THREAD

**Issue by sweetlikekendy** [Docile-Alligator/Infinity-For-Reddit#450]
Hello,

I'm really enjoying the autoplay with video controls video player on Infinity! 

I frequently browse sports subreddits and they upload their videos to streamable's platform/website. 

These videos don't seem to be supported by Infinity's video player. When I watch a video, I have to open them in the browser.

Here's an [example](https://www.reddit.com/r/nba/comments/pfw645/jimmy_butler_on_his_agent_telling_him_to_stop/).

It would be nice if these videos were supported. 

Thank you, Docile Alligator & other contributors 🙂

**Comment by Docile-Alligator** [comment]
Done. Thank you.
