### ISSUE TITLE
[Bug] Second tab uses incorrect feed

### ISSUE THREAD

**Issue by Skehmatics** [Docile-Alligator/Infinity-For-Reddit#456]
When customizing tabs, if you set the tab count to 1 and have something else filling in tabs (multireddits. Subreddits), then the second tab pulls the wrong feed.

Steps to reproduce:
1. Go to Settings > Interface > Customize Tabs in Main Page
2. Set tab count to 1 and enable any of the "more tabs" options at the bottom
3. Restart app
4. Go to second tab on the main page

Expected behavior: 
Feed pulled for that tab matches its name

Actual behavior:
Feed pulled for that tab is the same as if you had tab count set to 2 ("popular" by default)

**Comment by DOFfactory** [comment]
I confirm this. no matter how I set it, it always gives me rubbish and not my favourite multireddits or subreddit. Please amend.
