### ISSUE TITLE
[Feature] Go back to the top of the feed button

### ISSUE THREAD

**Issue by AmitGolden** [Docile-Alligator/Infinity-For-Reddit#457]
Hi,
I really dig this reddit client!
The only thing it lacks for me is a - go back to the top button. (Preferably not placed on the bottom like in the official reddit app, that can cause a lot of missclicks... or misstaps?)

That will make Infinity perfect for me

**Comment by tarkant** [comment]
I second this. I thought they could do like some other apps where you click the current tab (for example home/popular/all) and it scrolls you back on top.
