### ISSUE TITLE
[Feature Request] Option to export/import subscriptions

### ISSUE THREAD

**Issue by ghost** [Docile-Alligator/Infinity-For-Reddit#458]
Hi!

Please could you add an option to export/import subscriptions to/from a list. I use the app in anonymous mode & this option would really help.

**Comment by Docile-Alligator** [comment]
Done

**Comment by tegutistgut** [comment]
When will the feature arrive?

**Comment by Docile-Alligator** [comment]
Settings->Advanced->Backup settings will export a list of your subscribed subreddits in anonymous mode.
