### ISSUE TITLE
Feature Request: Add option to open link in chrome custom tab

### ISSUE THREAD

**Issue by Pinetrax** [Docile-Alligator/Infinity-For-Reddit#46]
Add an option to open links in chrome custom tab instead of the default browser. That way we don't have to switch to the browser if we want to use chrome.

**Comment by Docile-Alligator** [comment]
Ok. It will probably be released in the next update.

**Comment by Pinetrax** [comment]
Feature is implemented, thank you! For further improvements, there could be a list with links to open outside of custom tabs to open these in their native apps, but that is not part of this issue
