### ISSUE TITLE
Swipe between posts is buggy in Landscape mode

### ISSUE THREAD

**Issue by Mav3r1x** [Docile-Alligator/Infinity-For-Reddit#462]
I use the app on Galaxy tab in Landscape mode. When "swipe between posts" option is turned on, the navigation is super buggy.
I think the swipe distance needs to be longer, or manually adjustable. Because swipe up and down for comments accidentally swipes left/right for posts instead. If the swipe distance for posts is longer, this should be fixed.

**Comment by Wladefant** [comment]
Related to #996

**Comment by Wladefant** [comment]
@Mav3r1x is this still an issue?
