### ISSUE TITLE
Streamable Autoplay Support

### ISSUE THREAD

**Issue by livejamie** [Docile-Alligator/Infinity-For-Reddit#465]
Hello! Most of the big sport subreddits mainly use streamable video clips, could you please add autoplay support for them?

/r/nfl is probably the biggest example.

Thanks!

**Comment by seizue** [comment]
I was about to submit an issue about this. Glad someone submitted one.

Video clips from r/NBA are from streamable too. Hope the dev is working this on. It's the only feature I wanted the most.

**Comment by Docile-Alligator** [comment]
Done.
