### ISSUE TITLE
App not automatically loading posts and comments

### ISSUE THREAD

**Issue by Jassy7** [Docile-Alligator/Infinity-For-Reddit#467]
I am running the app on a oneplus 6 running android 11. A few issues:

> The app does not automatically load comments when I click a post.

> My feed stops at some point and shows a error loading posts error

> Sometimes images do not load

I have to either disconnect my WiFi or 4g connection and reconnect to get everything to load

**Comment by Jassy7** [comment]
Any fix for this? It makes the app impossible to use

**Comment by Docile-Alligator** [comment]
I don't think this is a bug from Infinity. Probably related to your network quality.
