### ISSUE TITLE
Handle reddit.app.link

### ISSUE THREAD

**Issue by ghost** [Docile-Alligator/Infinity-For-Reddit#472]
Currently Infinity will not load deep links starting with reddit.app.link commonly found on mobile site content gate prompting you to install the official reddit app

**Comment by Docile-Alligator** [comment]
Done

**Comment by orariley70** [comment]
doesn't work for Mature contents

**Comment by orariley70** [comment]
@Docile-Alligator doesn't work for mature content prompt.
