### ISSUE TITLE
Secure mode for tablet

### ISSUE THREAD

**Issue by gitshoko** [Docile-Alligator/Infinity-For-Reddit#489]
I have Infinity installed on both my Android phone as well as Android tablet. On my phone, I have the "Security" settings but it is lacking on my tablet. I assume it is because my tablet doesn't have a fingerprint sensor, which is needed to open the Security settings. Since the "Secure mode" is found in the Security settings, I cannot use this on my tablet. Would it be possible to enable these settings for all devices?

**Comment by Wladefant** [comment]
Hey @gitshoko, still an issue?
