### ISSUE TITLE
When tapping back button in media viewing page then it will go back to other pages except post page.  

### ISSUE THREAD

**Issue by Edfgdz** [Docile-Alligator/Infinity-For-Reddit#490]
I find i can't record screen to explain this problem because when i do it then screen recorder app would say recording failed. 

So i will explain this problem as clearly as i can.

When i type Photograph in search bar then this app would get these results. 

![Screenshot_2021-10-10-23-46-10-711_ml docilealligator infinityforreddit](https://user-images.githubusercontent.com/26460124/136703276-926b77f7-d304-4ca7-ade2-5b83e2d9f022.jpg)

So for some reason i choose first subreddit and go into it,then when i click one image to view in this page,for example like this picture in this post.

![Screenshot_2021-10-10-23-45-57-311_ml docilealligator infinityforreddit](https://user-images.githubusercontent.com/26460124/136703700-f8d96963-3244-46eb-8d75-46c6554b319b.jpg)

This page would popup to let me see it.

![Screenshot_2021-10-11-00-02-43-484_ml docilealligator infinityforreddit](https://user-images.githubusercontent.com/26460124/136703818-e0c444cb-15d4-4583-a27d-9acc090496fb.jpg)

Problem is when i tap phone home button to quit Infinity app in media viewing page then when i go into app again,in this situation,if i tap phone back button wanting to go to this page 

![Screenshot_2021-10-10-23-59-32-141_ml docilealligator infinityforreddit](https://user-images.githubusercontent.com/26460124/136703715-135a609c-9005-4a24-98aa-684071060faa.jpg)

This app would go to this page directly

![Screenshot_2021-10-10-23-46-10-711_ml docilealligator infinityforreddit](https://user-images.githubusercontent.com/26460124/136703727-396faf4c-4eeb-4d7e-b288-708323f74b4e.jpg)

And i find i can't swipe up and down in this page,only solution i find at present is that when i quit this app and go into it again then it will change back to this page normally. 

![Screenshot_2021-10-10-23-59-32-141_ml docilealligator infinityforreddit](https://user-images.githubusercontent.com/26460124/136703787-38e3a4f0-6759-4bff-848a-db85c57e2bb6.jpg)

This problem is very annoying when using this app and can't be sure if this problem is related to phone brands so wish developer could solve it.

**Comment by Docile-Alligator** [comment]
I am afraid this is not Infinity's issue.

**Comment by Edfgdz** [comment]
maybe,but when i use other Reddit apps like relay or boost for reddit then this problem won't appear. 

So i think maybe it is still possible to fix this problem.

**Comment by Edfgdz** [comment]
this is my phone information

![Phone system information](https://user-images.githubusercontent.com/26460124/140632829-8ddd1051-f508-4639-9a3a-3d8eacb0be6f.png)

**Comment by Edfgdz** [comment]
I find these two open source reddit apps and when trying them this problem will not appear.

https://github.com/QuantumBadger/RedReader

https://github.com/Tunous/Dawn

**Comment by Edfgdz** [comment]
So is it possible this problem could be solved?

**Comment by Wladefant** [comment]
Can not reproduce that
