### ISSUE TITLE
Feature Request: Collapse Comments

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#5]
It would be nice to be able to collapse a comment/comment chain, presumably via tapping or long-pressing.

**Comment by Docile-Alligator** [comment]
Hi, collapsing comments is available since day one. You just click the up arrow in a comment to collapse the comment tree. And I will add long pressing to collapse/expand in the future.

**Comment by BeeeWall** [comment]
Thanks, I apparently missed that!
