### ISSUE TITLE
Allow copying text from comments and posts

### ISSUE THREAD

**Issue by PopeRigby** [Docile-Alligator/Infinity-For-Reddit#50]

**Comment by Docile-Alligator** [comment]
This feature will be available in the next update.

**Comment by Wilker-a** [comment]
cool \^\^

i haven't looked at the update yet. does it allow copying both on reading the comment as well as replying to it? :3

**Comment by Docile-Alligator** [comment]
Available in version 2.2.0. You can copy the comment when you read it, not reply to it.
