### ISSUE TITLE
App crashes while browsing "saved posts"

### ISSUE THREAD

**Issue by Immunitty** [Docile-Alligator/Infinity-For-Reddit#501]
https://user-images.githubusercontent.com/92908900/138220971-e8552c84-345e-4e41-851a-01ca052cdf97.mp4

App crashes while in saved post section.

**Comment by Nan123721** [comment]
This also happens when clicking on a saved post, or on an image in the saved posts section.

**Comment by EdgeCon** [comment]
The same problem is happening to me too. I cannot browse past the 4th saved post in the saved posts section. After browsing past the fourth post, Infinity suddenly crashes. In addition, I experience the same issue of Infinity crashing when I click on a saved post.

**Comment by EdgeCon** [comment]
The issue was fixed for me in the most recent update.

**Comment by Docile-Alligator** [comment]
@Immunitty @Nan123721 Does this still happen in v5.1.0-beta2?

**Comment by Nan123721** [comment]
@Docile-Alligator fixed, closing.
