### ISSUE TITLE
Viewing our own profile shouldn't show us an option to follow

### ISSUE THREAD

**Issue by Immunitty** [Docile-Alligator/Infinity-For-Reddit#502]
https://user-images.githubusercontent.com/92908900/138222091-49bd51c9-7e18-4286-b22d-2091781e9b87.mp4

![Screenshot_2021-10-21-11-44-49-039_ml docilealligator infinityforreddit~2](https://user-images.githubusercontent.com/92908900/138222103-806e6692-1f4b-4df8-b755-1899b4dfcc90.jpg)

It is kind of stupid since this button doesn't do anything

**Comment by Docile-Alligator** [comment]
It allows you to follow yourself. It is not "doesn't do anything".
