### ISSUE TITLE
3 Button Navigation blocks video player controls

### ISSUE THREAD

**Issue by SlinkyThePerson** [Docile-Alligator/Infinity-For-Reddit#506]
App version: 5.0.4
Device: Nokia XR20
Android Version: 11 (see screenshot)

The default video player does not adjust the height of the controls for 3-button navigation, so the scrub bar is inaccessible behind the navbar. (see [Screen recording](https://imgur.com/a/1iS883A) ) 
![Screenshot_20211029-185046](https://user-images.githubusercontent.com/78572987/139512330-62c5ebba-8601-4b05-a680-85bee41026f4.png)
#

**Comment by Docile-Alligator** [comment]
Did you enable Ignore navigation bar in video player in settings->video?

**Comment by SlinkyThePerson** [comment]
Yes apparently I did, thank you.
