### ISSUE TITLE
Changing upvote from inside a post doesn't remove previous upvote

### ISSUE THREAD

**Issue by JackH3103** [Docile-Alligator/Infinity-For-Reddit#509]
To reproduce:
1. Upvote a post
2. Open post
3. Remove upvote or change to downvote
4. Exit post

Observed result:
Vote colour will not have updated.
Changing the vote will make it return to normal.

Expected result:
Vote colours should have updated.

This is occurs for downvotes.

Video:
https://user-images.githubusercontent.com/23507259/139588274-38f0c9a8-b654-448f-8cbb-9124769df456.mp4

**Comment by thebradness** [comment]
I think this got fixed as I can't reproduce it.

**Comment by JackH3103** [comment]
Yep, fixed for me too
