### ISSUE TITLE
Tiny size cards and comments. 

### ISSUE THREAD

**Issue by Fatcakes** [Docile-Alligator/Infinity-For-Reddit#51]

**Comment by Docile-Alligator** [comment]
I will try adding this as an option.

**Comment by Wladefant** [comment]
@Fatcakes can you explain a little bit more?

**Comment by TheCarpetMerchant** [comment]
Is there any work being done on this ? The app wastes so much space, simply removing most of the padding between elements would be satisfactory to me.

**Comment by Pentaphon** [comment]
I also want a more compact layout than the current compact. 

Call it "Compact Layout 2"
