### ISSUE TITLE
Some v.reddit videos don't play properly

### ISSUE THREAD

**Issue by JackH3103** [Docile-Alligator/Infinity-For-Reddit#510]
Some v.redd.it videos play with weird artifacts.
One example is https://www.reddit.com/r/MysteryDungeon/comments/qi60jw/what_dialga_doin/

**Comment by flexagoon** [comment]
The video plays fine for me. Can you attach a screenshot?

**Comment by Docile-Alligator** [comment]
This is because it's an HDR video. Your phone may not support it.
