### ISSUE TITLE
Feature Request: Option to "fully collapse" comments

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#52]
It would be nice to be able to "fully collapse" a comment, which if you haven't seen in other apps means collapsing the text of the comment. Screenshot of what this looks like in the Slide for Reddit app:

![Screenshot of fully collapsed comments in Slide for Reddit](https://i.imgur.com/zrooKsb_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by Docile-Alligator** [comment]
Oh. That's a good idea.

**Comment by Docile-Alligator** [comment]
Done
