### ISSUE TITLE
Bug in the latest beta?

### ISSUE THREAD

**Issue by Metalfan666** [Docile-Alligator/Infinity-For-Reddit#524]
When editing tabs it wont change tab names, it does show the correct subreddit, it just doesnt show the correct tab name. Even though I edit the tab name it wont apply them, and yes, I restarted the app after editing.

![Screenshot_20211110-233743_Infinity](https://user-images.githubusercontent.com/94081666/141197463-af39a861-a501-4b1c-b981-5ed13f773f4c.jpg)

**Comment by Docile-Alligator** [comment]
Cannot reproduce this bug. Could you send me a recording?

**Comment by Docile-Alligator** [comment]
Turns out this bug only happens in anonymous mode. Will be fixed soon. Thank you for reporting it. No need to send me a recording 😁.

**Comment by Metalfan666** [comment]
Thank yoy for fixing it, I confirm this bug as fixed.
