### ISSUE TITLE
Spoiler text broken - visual error, random on/off and markup/character display

### ISSUE THREAD

**Issue by CanadianVice** [Docile-Alligator/Infinity-For-Reddit#527]
Basically, when text in comments (at minimum those that a user has written) is in a spoiler, Infinity often breaks it (visually - other viewers show the spoiler itself remains intact).

Ie, it'll show random sections without spoilers, or the markup will be visible (sometimes interspersing with text at either end to about 3 chars), etc etc.

It gets a lot worse if an edit is done on the content within the app, any part of it.

This likely is an issue in posts proper, but from memory I've only noticed it in my own submissions.

LG G8X ThinQ, Android 11 Stock
I don't have any obvious things that'd be interacting to cause this.

**Comment by scria1000** [comment]
Possibly related to #327. Seems to be fixed in the `master` branch, but it's not out yet.

**Comment by CanadianVice** [comment]
> Possibly related to #327. Seems to be fixed in the `master` branch, but it's not out yet.

Sorry about that gov, I was on mobile - so search and whatnot is a bit of a PITA. But yes, that does indeed seem to describe the error.
