### ISSUE TITLE
"Sidebar" Title Wrapping

### ISSUE THREAD

**Issue by zacshann** [Docile-Alligator/Infinity-For-Reddit#528]
When using Harmonia Sans (normal size) for all fonts, and opening a subreddit the text for indicating the "Sidebar" tab is wrapping the word to two lines instead of just being one line, like the "Posts" tab.

Here is a sample:
![Screenshot_20211111-121943](https://user-images.githubusercontent.com/94133254/141342088-d5e4c0a0-409b-4a66-9e6f-de929087b577.png)

**Comment by Metalfan666** [comment]
This was fixed in #449, make sure youre using the latest version.

**Comment by zacshann** [comment]
Hi, thanks for the response! I'm using version 5.0.4, which appears to be the latest version in the playstore that's available? Though it appears #449 was fixed after the latest playstore release dated August 26th, so I'm assuming it's fixed in the beta program version and I just can't see it yet. 

Thanks again for the response. :)

**Comment by Metalfan666** [comment]
You can download beta versions from here too:

https://github.com/Docile-Alligator/Infinity-For-Reddit/releases
