### ISSUE TITLE
Long pressing spoilers shows link dialog

### ISSUE THREAD

**Issue by scria1000** [Docile-Alligator/Infinity-For-Reddit#529]
Doesn't matter if it actually contains a link or not.
 
As shown:
<img src="https://user-images.githubusercontent.com/91804886/141647426-0e2d480e-48a8-432a-9602-8509ec9d949a.png" width=30% height=30%>

If the spoiler contain some non-word character like ) there is no reddit.com:
<img src="https://user-images.githubusercontent.com/91804886/141647586-0ada4453-bfee-453e-adbc-423eeb3ae340.png" width=30% height=30%>

probably a LinkifyPlugin issue?

**Comment by Docile-Alligator** [comment]
It's because the spoiler is rendered as a ClickableSpan. LinkMovementMethod treat it as a valid link.
