### ISSUE TITLE
Content reporting

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#53]
reports can be important sometimes. having the proper subreddit and sitewide rules to report as would be good too, as well as the personalized text

**Comment by Docile-Alligator** [comment]
You are right! 😁

**Comment by Docile-Alligator** [comment]
Done.

**Comment by Wilker-a** [comment]
a few improvements that can be done now would be
- to include visual cues for when the subreddit rules are loading and
- separate site-wide rules from subreddit rules,
- and include the field for user-specified text.
- maybe also make the screen a popup like the app exit prompt and
- make the checkboxes be radio buttons instead, as you can only select one.
- also set the report categories non selectable to make them expand into the specific options instead.

this is what i can think of for now ^^'

**Comment by Wilker-a** [comment]
thank you for all this <3
