### ISSUE TITLE
Readability Issue in Chat

### ISSUE THREAD

**Issue by ramansg** [Docile-Alligator/Infinity-For-Reddit#536]
The text color of the links in the chat juxtaposed on the background of chat bubble creates a readability issue — making it very difficult to read the links.

![Screenshot_20211116-143930_Infinity](https://user-images.githubusercontent.com/19746632/141958901-e811fbe5-7df9-4c5a-ace9-51ea8068c404.png)

**Comment by Nojuuu** [comment]
You can edit these colours in `Settings --> Theme` to suit your preferences, but I agree that the default colours should probably be changed to make them more readable.

**Comment by Wladefant** [comment]
Please add a [Feature Request]to the title

**Comment by Wladefant** [comment]
You can edit the colors under settings>theme>receibed Massage background color
