### ISSUE TITLE
Video playback speed controls are barely legible in dark mode (v 5.1.0)

### ISSUE THREAD

**Issue by Matipolit** [Docile-Alligator/Infinity-For-Reddit#539]
![Screenshot_20211117-102501_Infinity.png](https://user-images.githubusercontent.com/25749447/142173817-8a6ce581-e487-4842-b913-4d3a88aa0890.png)
As visible in the screenshot, there is very little contrast between the black text and gray background of the video speed control panel.
The text should have more contrast.

**Comment by Docile-Alligator** [comment]
Fixed
