### ISSUE TITLE
[Feature Request] Allow bookmark in Anonymous mode

### ISSUE THREAD

**Issue by NSTAdventure** [Docile-Alligator/Infinity-For-Reddit#542]
Title described everything so i no need to explain anymore

Except this:
1. I don't want create account i just want to become a guest visitor due to my account is banned without any reason

**Comment by Docile-Alligator** [comment]
Bookmark? You mean subscribing to a subreddit?

**Comment by NSTAdventure** [comment]
> Bookmark? You mean subscribing to a subreddit?
![IMG_20220116_153734](https://user-images.githubusercontent.com/50813528/149653022-08323e6a-ea4e-4a50-82bb-82aee3f510b9.jpg)
i referring to this one bruh 🗿🗿🗿🗿🗿🗿🗿


(bruh idk why people is really adorable nowadays🗿🗿🗿🗿🗿🗿)

**Comment by Wladefant** [comment]
@NSTAdventure You don't speak in this tone to developers

**Comment by NSTAdventure** [comment]
> @NSTAdventure You don't speak in this tone to developers

Yes deleted sorry developers 🙏😥
