### ISSUE TITLE
Some posts appear multiple times

### ISSUE THREAD

**Issue by entodoays** [Docile-Alligator/Infinity-For-Reddit#55]
Sometimes while scrolling certain posts appear in the feed multiple times. Occasionally it happens to even having the same post showing with just one post in between the two instances. This seems like a bug to me.

**Comment by watson387** [comment]
I have also noticed this. It happens every time I scroll down more than 20 or so posts.

**Comment by Docile-Alligator** [comment]
Yes. This is a bug of Reddit API itself.

**Comment by OHermesJunior** [comment]
Can be closed.

**Comment by Docile-Alligator** [comment]
I have implemented a solution for this and it reduces the duplicate posts. But it doesn't totally eliminate duplicate posts and I don't know why.

**Comment by Docile-Alligator** [comment]
Fixed.
