### ISSUE TITLE
[BUG] Hypertext links disappear when I return to previously viewed post

### ISSUE THREAD

**Issue by OnlyC0RE** [Docile-Alligator/Infinity-For-Reddit#552]
As title says. Refresh fixes it

https://user-images.githubusercontent.com/90108562/143691447-20adbba0-9700-4dbd-a6ac-b768adf11002.mp4

**Comment by scria1000** [comment]
Hmm, it seems this bug was introduced in 5.1.0 (possibly by me). I'll take a look.

**Comment by scria1000** [comment]
should be fixed now

**Comment by OnlyC0RE** [comment]
Can confirm 5.1.3 fixed it. Though the comments seem to load very slowly now.
