### ISSUE TITLE
Feature request: scroll to top on refresh

### ISSUE THREAD

**Issue by JeeVee11** [Docile-Alligator/Infinity-For-Reddit#554]
When you leave the front page and come back it remembers the post you where on. Sometimes when it's been a while I would like to scroll back to the top of the front page and refresh, but I don't think this is possible now.

This could be done on refresh, or maybe a dedicated scroll to top button.

**Comment by Metalfan666** [comment]
There is a scroll to top button, its in the bottom navigation bar. You can also push and hold top navigation bar tab texts to go to top.

If youd like to get a special go to top button then +1 #499.

**Comment by KaKi87** [comment]
What's the bottom navigation bar ? I don't see any such thing 🤔

**Comment by kingprawn22** [comment]
I was also looking for this and seem to be missing the bottom navigation bar. Do you need to be logged in to see it?

**Comment by KaKi87** [comment]
I am logged in and do not see anything

**Comment by kingprawn22** [comment]
Good to know. No idea on how to get it to appear then... It doesn't show in any of the views for me (Home/Popular/All or a single subreddit).

**Comment by Docile-Alligator** [comment]
To enable bottom navigation bar, please turn on Enable Bottom Navigation in settings->Interface.

Done.

**Comment by KaKi87** [comment]
Well, I enabled it and am not seeing any *scroll to top* button 🤔
