### ISSUE TITLE
Open by Default getting reset

### ISSUE THREAD

**Issue by JasonKraft** [Docile-Alligator/Infinity-For-Reddit#559]
I'm using Infinity 5.1.2 on my Pixel 3 with Android 12. I've noticed recently when clicking on Reddit links in Brave, reddit opens in my browser instead of the Infinity app. When I open my app settings and go to "Open by Default", I see "0 verified links", however, I can manually check off various link types to force them to open with Infinity.

The problem is that this setting gets randomly reset about once per week, so I have to routinely go back into my settings and manually add back all the supported links.

Is there a workaround to prevent this from happening? Please let me know if there's any other useful info I can provide.

**Comment by Metalfan666** [comment]
Im not sure how much different Pixel is from S21, but you can go to Infinity settings and uncheck "Remove permissions if app is unused".

![Screenshot_20211202-001416_Settings](https://user-images.githubusercontent.com/94081666/144322733-91bf2a07-6d17-4498-ab23-d1eb7d4d331d.jpg)

**Comment by Docile-Alligator** [comment]
Android 12 has a feature that automatically removes all the selected links whenever an app update occurs. It's not a bug and there is nothing I can do about it.
