### ISSUE TITLE
Long private messages conversations crash 

### ISSUE THREAD

**Issue by Pipetto-crypto** [Docile-Alligator/Infinity-For-Reddit#560]
I am using the last available version of Infinity from the PlayStore on my Xiaomi Venus with Android 11 but this issue happens in other devices I tested and with other versions as well.

Everytime I try to open a very long pms conversation the app crashes and I have to re-open the app

This is a detailed crash report:

https://ibb.co/LpR2Fqs
https://ibb.co/KK

P.S I am not able to recieve notifications from these conversations as well

**Comment by scria1000** [comment]
Line of interest: Caused by: android.os.[TranscationTooLargeException](https://developer.android.com/reference/android/os/TransactionTooLargeException): data parcel size 4722336 bytes

Private Message Replies were too big to be sent over the Intent, probably should be handled in some other way.

**Comment by Docile-Alligator** [comment]
Thank you for this! I will look into it.

**Comment by llee8820** [comment]
Same issue. Long private messages crash. Short ones are ok.

**Comment by Docile-Alligator** [comment]
Fixed.
