### ISSUE TITLE
Posts without votes in Best

### ISSUE THREAD

**Issue by Caedael** [Docile-Alligator/Infinity-For-Reddit#578]
In Best are a lot of posts without votes or with less then 40 up votes while few posts from best in reddit app aren't shown.

**Comment by Docile-Alligator** [comment]
Did you enable Save scrolled position in home?

**Comment by Caedael** [comment]
> Did you enable Save scrolled position in home?

Yes I did.

**Comment by Caedael** [comment]
Closed because it is an issue in reddit api
