### ISSUE TITLE
[Reddit API issue] JSON responses of some major subreddits no longer contain link previews

### ISSUE THREAD

**Issue by scria1000** [Docile-Alligator/Infinity-For-Reddit#582]
I don't know if this is a recent thing, but in some of these major subreddits, the preview key simply does not exists for links. It also seems to have broken Streamable support. I think it's because of this secure_media thing they are rolling out or some other change in how the API should be used.

https://www.reddit.com/r/nfl/hot.json?raw_json=1&limit=25

https://www.reddit.com/r/worldnews/hot.json?raw_json=1&limit=25

**Comment by Docile-Alligator** [comment]
Streamable support is fixed for no preview links.

**Comment by scria1000** [comment]
@Docile-Alligator 
Because Posts are reused from PostRecyclerViewAdapter upon first viewing a PostDetail, the preview (image, video, link doesn't matter) won't load (because some subreddits did not give us a preview key in PostRecyclerViewAdapter) until we do a refresh and make a request for a single post (which will then contain a preview key)

hope this helps
