### ISSUE TITLE
Holup prediction posts

### ISSUE THREAD

**Issue by Gottarocket** [Docile-Alligator/Infinity-For-Reddit#583]
https://reddit.com/r/HolUp/predictions?tournament=tnmt-3c5b35d2-f20e-483e-8c9c-e256277329f5 prediction posts dont work and post says it wont on old.reddit.com or browser but on app any workaround?

**Comment by flexagoon** [comment]
Reddit doesn't allow third party client API to access and interact with prediction posts. This is not just about predictions, some other newer features like polls are not available for custom clients as well. I guess they're doing it to make more people use the official app and make more money from ads.

**Comment by Docile-Alligator** [comment]
No there is no workaround. There is no way for 3rd-party apps to load prediction posts.
