### ISSUE TITLE
Collapsed comment threads needs more visual cues, & options should be more descriptive

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#59]
limitations also includes reading replies from the inbox — only the main parent comment is shown, but also when trying to read posts as usually.

**Comment by Docile-Alligator** [comment]
Hi! You mean notifications for comments do not show up?

**Comment by Wilker-a** [comment]
i mean comment replies in a thread,

**Comment by Wilker-a** [comment]
**i found the problem!**

the issue was that i had enabled "Show Top-Level Comments first" all along.

that said, it is a bad wording. what i assumed when i had it enabled, was that it would put pinned comments and such at the top, but even now it desn't help understanding it much.

my suggestion for an improvement is to replace this text entirely with something like "Collapse comment threads by default". more descriptive, addresses the specific points in the comments, and makes you aware of what to expect.

another improvement to make, is that even whenever this is enabled, it should still expand the threads up to the point of the highlighted comment, which would make it more intuitive and easier to navigate.

one more: collapsed threads needs more visual cues than just an upside-down arrow. maybe by having a colored icon besides the nametag, or painting the current one pink (the same as the crosspost icon), or change the height of the comment container in a subtle but visible way.

in any case, thank you for maintaining this project. i love it uwu❤️

###### btw i'm editing the title
