### ISSUE TITLE
Don't reload when phone is rotated

### ISSUE THREAD

**Issue by yephny** [Docile-Alligator/Infinity-For-Reddit#597]
Rotating your phone will take you back to the top of the page wherever you are. It's an issue when watching videos/GIFs also, as it starts from the beginning / reloads the file, which takes time.

I don't know if it's possible but it'd be great if it didn't reload the page when you rotate your phone.

**Comment by Docile-Alligator** [comment]
It should not take you to the top of the page. Maybe there is a bug. And also it won't reload when watching videos. Did you change some options in developer settings on your phone?

**Comment by yephny** [comment]
I can't reproduce the video issue, perhaps it was specific to v.5.1.3.

It does take you to the top in the comment section though. [Here is a video of it](https://qu.ax/AITh.mp4). Let me know if you can't access the file.

**Comment by Wladefant** [comment]
It does not reload the post but it does take you to the top when scrolling through comments
