### ISSUE TITLE
Feature Request: Show subscriptions in side menu

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#6]
A lot of Reddit apps have the ability to show the subscriptions in the side drawer, which is more convenient than a separate page (although not a strictly necessary feature).

**Comment by Docile-Alligator** [comment]
Hi there, actually I put all the subscriptions in the side drawer before, but it consumed more memory since if the height is not fixed, the RecyclerView will have to inflate all the subreddits view and thus taking up a lot of memory. But I will still try to implement it in a better way.

**Comment by BeeeWall** [comment]
Looks like this has been added. Thanks!
