### ISSUE TITLE
Comments with \^ adds another ^ sometimes

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#60]
there is not much need to sanitize that.

**Comment by Docile-Alligator** [comment]
Yes. The markdown rendering library I use only supports showing content as superscript when two ^ are present. Reddit markdown is different and the superscript is shown after only one ^ is present. So, I have to use regex to manually add another ^ but the regex is not perfect. Thus, sometimes it shows weird ^.

**Comment by Docile-Alligator** [comment]
Fixed in v4.3.0-beta1
