### ISSUE TITLE
how to remove the + button?

### ISSUE THREAD

**Issue by LMWH03** [Docile-Alligator/Infinity-For-Reddit#601]
hi, how can i remove the + button and the treding?

**Comment by flexagoon** [comment]
It's probably not possible, because you wouldnt be able to post anything without this buttom

**Comment by LMWH03** [comment]
> It's probably not possible, because you wouldnt be able to post anything without this button

I don't post anything on reddit, so I wanted to remove the button.

**Comment by Wladefant** [comment]
#1036
