### ISSUE TITLE
(feature) different color(s) for collapsed comments

### ISSUE THREAD

**Issue by brij1234** [Docile-Alligator/Infinity-For-Reddit#604]
The green color is a little jarring. Maybe change to a more comfortable color? Or allow the user to customize?

![Screenshot_20211219-211018](https://user-images.githubusercontent.com/9251787/146702385-d3e23f7e-03e2-4574-b72b-f35a84aa4d29.png)

**Comment by flexagoon** [comment]
You can customize it already. Just go to `Settings -> Theme -> Manage Themes` then click on the theme you're using and find "fully-collapsed comment background color". You can change it there.

**Comment by brij1234** [comment]
@flexagoon awesome! Didn't know that.
