### ISSUE TITLE
Internal browser: button for “Open in browser”

### ISSUE THREAD

**Issue by brij1234** [Docile-Alligator/Infinity-For-Reddit#606]
Extends #460 

The internal browser is awesome for privacy and to browse a link quickly. But, a “open in browser” option would be awesome too. This way, I can take advantage of the system default browser.

Example image from the **Boost Reddit app**:
![image](https://user-images.githubusercontent.com/9251787/146818274-b864ab39-5f09-41d1-b9b9-c9573a5b8924.png)

**Comment by Docile-Alligator** [comment]
Done
