### ISSUE TITLE
spoilers containing links open link instead of revealing spoiler

### ISSUE THREAD

**Issue by ghost** [Docile-Alligator/Infinity-For-Reddit#609]
This issue happens in the newest stable release. If there is a spoiler with a link, if you press the part of the spoiler containing the link, it presses the link instead of revelling the spoiler. This post is an example
https://www.reddit.com/r/u_nan123721/comments/rmet9k/test/

**Comment by Wladefant** [comment]
Please share another example

**Comment by RSBat** [comment]
Hi @Docile-Alligator 
I started looking into this bug and noticed that spoilers behave differently on the website. You can hide spoiler after viewing it in the app but not on the website.
Do you want to keep current behavior or to make it the same as on the website?

**Comment by Wladefant** [comment]
Hey, @RSBat thanks again.
I think it should be like on the website, but I will start a little poll to know what the users think.
And of course the opinion @Docile-Alligator also does matter.

**Comment by Docile-Alligator** [comment]
@RSBat I would like to keep the current behavior. But if keeping it this way makes fixing the bug too hard, then that's fine to make it the same as on the website.

**Comment by Wladefant** [comment]
@Docile-Alligator why would like it to keep it this way? I mean from the user perspective it doesn't make much sense: you want to see a spoiler and you are tapping on it, but why do you want to hide it?
