### ISSUE TITLE
Feature improvement: when the bottom navbar is enabled, the whole + button should be in it

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#61]
that would make it occupy a lot less space on the screen while it could stay in the middle :3

while we're at that, the background color could be the same as the rest of the navbar, but with the primary color just as a circled outline so it doesn't get too distracting, while still indicative :3

**Comment by Docile-Alligator** [comment]
Good suggestion. Maybe I will add an option for this.
