### ISSUE TITLE
[Request] Export and import subreddits

### ISSUE THREAD

**Issue by tegutistgut** [Docile-Alligator/Infinity-For-Reddit#612]
Hello.

My request is a feature, where we can export a list of our subscribed/followed subreddits.

And a feature to import a exported list of subscribed/followed subreddits to the "anonymous" account mode.

Thats it

Thanks

**Comment by TheLastZombie** [comment]
This is a duplicate of #458, though I haven't been able to find the actual interface - I assume it will arrive with 5.2.

**Comment by Docile-Alligator** [comment]
Settings->Advanced->Backup settings will export a list of your subscribed subreddits in anonymous mode.
