### ISSUE TITLE
Changing Sort Type no longer resets distance scrolled

### ISSUE THREAD

**Issue by softwareAnarchist** [Docile-Alligator/Infinity-For-Reddit#614]
Not a major issue. If you're on the first post and sort by Top of All Time for example, the first post will be the top post. But if you have scrolled quite a bit then sort by Top of All Time, you have to scroll back up to the top

**Comment by Disaster-Master** [comment]
I also experience this. I don't know if it is intended behavior or not.

**Comment by Docile-Alligator** [comment]
It is normal behavior. But now it automatically goes back to the top after refreshing or changing sort types.
