### ISSUE TITLE
[Bug] View goes into the notification area

### ISSUE THREAD

**Issue by Tursko** [Docile-Alligator/Infinity-For-Reddit#619]
I notice this on my pixel 5. Makes stuff hard to read. ![Screenshot_20211230-143602~2.png](https://user-images.githubusercontent.com/18274896/147786499-026c8507-98b1-466f-992b-c2e5893a2575.png)

**Comment by RodneyRichardson** [comment]
I find this particularly annoying when trying to zoom into text at the top of an image. I can't mive the top of the image below the notification area.

**Comment by Tursko** [comment]
> I find this particularly annoying when trying to zoom into text at the top of an image. I can't mive the top of the image below the notification area. 

It's certainly a bug. Hopefully the dev has some time to account for the notification area.

**Comment by Docile-Alligator** [comment]
This is not a bug. It's by design. You can disable Settings->Immersive interface.

**Comment by Tursko** [comment]
> This is not a bug. It's by design. You can disable Settings->Immersive interface.

Maybe it should be on my default then? Although cool it certainly hurts the experience.
