### ISSUE TITLE
Buttons often overlaps in long comment threads

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#62]
when there is a long chain of comment replies, the vote buttons often gets overlapped with the collapse button and others.

maybe tweaking the spacing of the buttons can solve part of the issue?

**Comment by Docile-Alligator** [comment]
Yes. I haven't fixed this issue but I will try fixing it after I added other features.

**Comment by Docile-Alligator** [comment]
Fixed in v4.3.0-beta1
