### ISSUE TITLE
Can't access login page from "add account "anymore

### ISSUE THREAD

**Issue by lifesaver666** [Docile-Alligator/Infinity-For-Reddit#624]
Getting an errorcode: 502ssl

![Screenshot_20220105-213907-178](https://user-images.githubusercontent.com/93796915/148320387-2e36ffb9-13e1-47f3-904c-7cc7f70a95dd.png)

**Comment by lifesaver666** [comment]
works again now.

**Comment by Docile-Alligator** [comment]
Sometimes Reddit server goes down.
