### ISSUE TITLE
[Feature Request] Share videos and gifs directly from the player + some more

### ISSUE THREAD

**Issue by KR2206** [Docile-Alligator/Infinity-For-Reddit#626]
Hello,

I am a boost user,started getting comfortable with Infinity but one thing I miss is the ability to share vids and gifs directly from the media player itself. (Reference below)

![Screenshot_20220109-182552_Boost.jpg](https://user-images.githubusercontent.com/76439155/148683022-be52225d-c6ff-4dc7-bca0-a1add62246d5.jpg)

Another useful qol feature would be able to show the avatars of comments and options to copy text from various parts of post(like post text,oc username, comments text, comments author username. (Reference below)

![Screenshot_20220109-182946_Boost.jpg](https://user-images.githubusercontent.com/76439155/148683154-4b4b62fb-3940-49eb-a6c2-a31730fb2d16.jpg)

**Comment by electrona** [comment]
I think what needs to be done to share a link direct is to download to file to a temp location and then share the file directly from the file system.
