### ISSUE TITLE
Multireddit tab name not capitalizing first letter

### ISSUE THREAD

**Issue by TAOcroatia** [Docile-Alligator/Infinity-For-Reddit#627]
Best described with pictures. 
Not a huge issue, but an eyesore for sure

![Screenshot_20220109-142145_Infinity~3](https://user-images.githubusercontent.com/34100820/148684032-18f3bdb9-150b-4da4-aee2-03b22d47cba3.png)
![Screenshot_20220109-142335_Infinity~3](https://user-images.githubusercontent.com/34100820/148684034-1d3ca2d8-37db-4ca2-975d-f23747661034.png)

**Comment by ffreling** [comment]
Is "croatia" the original name of the multireddit?

I have a similar issue: the original name (maybe it's its internal id) appears on the tab, whereas the current name that I edited afterwards, appears in the list of multireddits.

**Comment by angrybacon** [comment]
> Is "croatia" the original name of the multireddit?

I tried again just now, creating the multi-reddit from either old or current reddit.com results in the lowercased name from the tabs within Infinity

**Comment by DeathPhantom77** [comment]
Addressed in https://github.com/Docile-Alligator/Infinity-For-Reddit/pull/1279
