### ISSUE TITLE
Add reddit.app.link to supported links

### ISSUE THREAD

**Issue by federico2407** [Docile-Alligator/Infinity-For-Reddit#628]
The reddit mobile website uses the app.link service for the "open in app" button, that then redirects to the play store / official reddit app.
I think it would be useful to have all reddit.app.link URLs open in infinity

**Comment by Wladefant** [comment]
On my phone it opens infinity automatically, because the original reddit app is not installed. 

Just uninstall the app and all links will open in infinity. 😀

**Comment by federico2407** [comment]
> On my phone it opens infinity automatically, because the original reddit app is not installed.
> 
> Just uninstall the app and all links will open in infinity. grinning
> 
> But you are right a support for the link would be nice

I don't have the original reddit app, when i click the "open in app" button it sends an intent that only app stores (and i assume the original reddit app that i don't have) can recieve.

**Comment by Wladefant** [comment]
> > On my phone it opens infinity automatically, because the original reddit app is not installed.
> > 
> > Just uninstall the app and all links will open in infinity. grinning
> > 
> > But you are right a support for the link would be nice
> 
> I don't have the original reddit app, when i click the "open in app" button it sends an intent that only app stores (and i assume the original reddit app that i don't have) can recieve.
> Screenshots: https://imgur.com/a/AnVzCtb

Just checked the support for the link is already there

**Comment by Wladefant** [comment]
I think you just need to toggle the link and then close this issue

**Comment by federico2407** [comment]
> I think you just need to toggle the link and then close this issue

I checked that previously and it was already enabled. Just noticed it was a firefox settings problem (i had to enable open links in app), now it works, thank you, i'm closing the issue

**Comment by Wladefant** [comment]
> > I think you just need to toggle the link and then close this issue
> 
> I checked that previously and it was already enabled. Just noticed it was a firefox settings problem (i had to enable open links in app), now it works, thank you, i'm closing the issue

@federico2407 you are welcome
