### ISSUE TITLE
Feature request: crossposts should have the parent posts shown as a smaller square/rectangle inside of the post revealing the original details and origins of it

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#63]
:3

**Comment by Docile-Alligator** [comment]
Haha, it will be the same as the official Reddit app.

**Comment by Wilker-a** [comment]
i see \^\^'

the pink icon is actually faster to pick up the information. maybe having it as the rectangle frame, or just having the sub where it came from in the side of the button (or in a toast) could be another solution? :3
