### ISSUE TITLE
[Bug] Videos not playing well

### ISSUE THREAD

**Issue by asfhrbgna** [Docile-Alligator/Infinity-For-Reddit#633]
Despite having good internet, some videos play well and some videos NEVER play

**Comment by sal0max** [comment]
Maybe you should give some examples of the slow videos.

**Comment by Docile-Alligator** [comment]
Could you provide some post links?

**Comment by Wladefant** [comment]
@asfhrbgna please provide some examples like post links, screen recordings, images

**Comment by removed0** [comment]
same

**Comment by removed0** [comment]
same problem
