### ISSUE TITLE
app crashed every minute 

### ISSUE THREAD

**Issue by amayra** [Docile-Alligator/Infinity-For-Reddit#635]
Infinity crashed every minute with error "out of memory" 

i have only 2gb ram and i can't upgrade rights now 

this problem i used to have with official app but they fixed in changelog 

there way to clean ram or cache so app don't excess available RAM that phone have for app to use ?

ps: i send crash report with google play if this help

**Comment by amayra** [comment]
Is there any way to fix this I cant keep using the app for less than 1 min without crashing?
https://developer.android.com/reference/java/lang/OutOfMemoryError

**Comment by Docile-Alligator** [comment]
Could you try turning on data saving mode?
