### ISSUE TITLE
Not every dot is a link

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#64]
having.dot typos displayed as .a link can be distracting when reading. an option to disable would be good, while still having the usual effect on full urls (with protocols:// and stuff)

**Comment by Docile-Alligator** [comment]
You mean some invalid links shown in comments and post content?

**Comment by Wilker-a** [comment]
pretty much every pair of words with a dot in between, except for the usual phrase ends.

**Comment by OHermesJunior** [comment]
I think this is fixed. If not, can you provide an specific example?
