### ISSUE TITLE
Some subreddit links send the user to a post

### ISSUE THREAD

**Issue by 5265644D61736F6E** [Docile-Alligator/Infinity-For-Reddit#641]
In [this comment](https://www.reddit.com/r/memes/comments/rz0kes/one_of_the_worst_sentences/hrs184o/), someone links to a subreddit in a rather unusual way: `[r/furry](r/furry)` (found using Copy Raw Text)

In the Infinity app, the link takes the user to [Rethinking Javascript Object Enumeration](https://www.reddit.com/furry) instead of https://www.reddit.com/r/furry. If the user holds down on the link, it says `https://www.reddit.comr/furry`, which is not on Reddit. The other subreddit links send the user to posts that cannot be loaded.

**Comment by Docile-Alligator** [comment]
Fixed.
