### ISSUE TITLE
Bottom navigation bar missing

### ISSUE THREAD

**Issue by kingprawn22** [Docile-Alligator/Infinity-For-Reddit#643]
On my Samsung S21 Ultra, I have no bottom navigation bar. This applies to all views, Home, Popular and All, as well as individual subreddits. I didn't know there even was a bottom navigation bar until I saw some screenshots of the app and was wondering how you get back to the top of the page (I'm having to force close the app then reopen it to get back to the top).

Does anybody know what could be going on here? I love the app but not being able to go to the top is irritating.

I am using 5.1.6 from F-Droid, althohgh I have updated through several versions over time and haven't seen the navigation bar on any of them.

**Comment by qrhfz** [comment]
You need to enable it in Settings->Interface-> Enable Bottom Navigation

**Comment by kingprawn22** [comment]
Oh I see! I was thinking it was an on-by-default kinda thing, but I really should have checked. That's it working as epected now, so thanks for that.
