### ISSUE TITLE
Allow users to hide/turn off comment author avatar

### ISSUE THREAD

**Issue by vishalnandagopal** [Docile-Alligator/Infinity-For-Reddit#647]
Comment author avatars are definitely a good addition, but an option to disable them will be useful too.

On a slow connection, the avatars take a few seconds to load. It distracts you from reading a comment when they load slowly, one by one. And I'm sure people using the old reddit interface on desktop will appreciate a toggle that disables coment avatars.

When the option to hide comment author avatars is turned on, the loading of avatars should also be disabled to save mobile data.

Thank you for the app!

**Comment by Docile-Alligator** [comment]
Thank you. This is now available.
