### ISSUE TITLE
[Bug] redd.it short links open in a custom tab rather than as a post

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#65]
Steps:
1. Click on a redd.it short link (such as [this one](https://redd.it/f9vzf5)). 
2. Select to open it with Infinity when prompted. 

Expected behavior: It opens in Infinity properly. 

Actual behavior: it opens in a custom tab within Infinity. Normal links (such as [this](https://reddit.com/r/MurderedByWords/comments/f9vzf5/karen_got_real_quiet_after_this_one/)) open fine still.

**Comment by Docile-Alligator** [comment]
Oh. I haven't checked the structure of redd.it links.

**Comment by BeeeWall** [comment]
Looks like it works now, not sure when you fixed it but I'll close this since apparently you did lol
