### ISSUE TITLE
History

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#651]
Make it possible to have history for read posts. I would like a list of all posts I visited.

Also, an option to delete history, option to only keep items for at most a specified time period (i.e. delete everything older than 1 month) and an option to only keep last x entries in history.

**Comment by soredake** [comment]
@Docile-Alligator

**Comment by AhmedMudkip** [comment]
> Make it possible to have history for read posts. I would like a list of all posts I visited.
Yes please

**Comment by Wladefant** [comment]
Now available in v5.3.0-beta1
