### ISSUE TITLE
Edge-to-edge rendering (immersive interface) does not apply to the whole app when enabled

### ISSUE THREAD

**Issue by Jnss98b** [Docile-Alligator/Infinity-For-Reddit#66]
Regardless of your settings, the settings page and the whole app while in landscape have opaque system bars
![Screenshot_20200226-234408](https://user-images.githubusercontent.com/24306400/75413110-a31ae480-58f2-11ea-9fe7-38e966ffbf6b.png)
![Screenshot_20200225-015850](https://user-images.githubusercontent.com/24306400/75413116-a8782f00-58f2-11ea-8161-ce6df3d22e8f.png)

**Comment by Docile-Alligator** [comment]
Some pages cannot have immersive interfaces because the snack bar will be hidden by the keyboard. I will try implementing immersive interface in landscape mode.

**Comment by Jnss98b** [comment]
What pages are you talking about exactly? I don't think the keyboard will ever open in the settings page at all

**Comment by Jnss98b** [comment]
Also, take a look at the page below for the solution to show the snack bar above the software keyboard
https://stackoverflow.com/questions/33138433/show-android-snackbar-above-keyboard

**Comment by Docile-Alligator** [comment]
The page for submitting posts (text post, image post, link post, and video post). I am just a bit lazy so I haven't implemented the immersive interface on the settings page and also, settings page doesn't have any posts in it.

Actually I have used the solution in the link but unfortunately, when the immersive mode is enabled, the solution doesn't work.

**Comment by Jnss98b** [comment]
> Actually I have used the solution in the link but unfortunately, when the immersive mode is enabled, the solution doesn't work.

You could try asking around. I'm sure there has to be a way for it to work.

**Comment by Docile-Alligator** [comment]
Ok. I will try searching it.

**Comment by OHermesJunior** [comment]
I am pretty sure this is solved, right?

**Comment by Jnss98b** [comment]
> I am pretty sure this is solved, right?

No

**Comment by OHermesJunior** [comment]
Oh, right. Landscape works for me, only the Settings and Search screens that doesn't.

**Comment by Jnss98b** [comment]
This isn't resolved yet why is it closed
