### ISSUE TITLE
Unable to access any subreddit starting with "u_"

### ISSUE THREAD

**Issue by Oplopanax-horridus** [Docile-Alligator/Infinity-For-Reddit#660]
And there are many such subreddits, mostly NSFW models. An example is u/gcupbabyofficial. Notice that she often posts in r/u_gcupbabyofficial, although in Infinity the subreddit name is mis-rendered as u/gcupbabyofficial. Clicking the link for the subreddit redirects you to the user, not the subreddit.

**Comment by Docile-Alligator** [comment]
Fixed.
