### ISSUE TITLE
[Bug] Filtering never returns any results from nsfw subreddits

### ISSUE THREAD

**Issue by ginobo** [Docile-Alligator/Infinity-For-Reddit#667]
Whenever filtering by flare in a nsfw subreddit Infinity will always return "No results" if it is being searched in an nsfw subreddit.

Safe place for testing r/handholding

**Comment by Docile-Alligator** [comment]
I will look into it.

**Comment by ginobo** [comment]
@Docile-Alligator Thanks for looking into this, unfortunately this still does not seem to be working in v5.1.9-beta1
