### ISSUE TITLE
[Feature Request] Make the number of members of a sub be displayed like 5966121 like 5.966.121

### ISSUE THREAD

**Issue by cmarincia** [Docile-Alligator/Infinity-For-Reddit#672]

**Comment by derpyderpaderp** [comment]
Why would you use periods and not commas?

**Comment by cmarincia** [comment]
That's good too, I don't see a problem with that.

**Comment by winstoncooke** [comment]
I've changed the formatting of the XML string to add separators accounting for the difference in locale of using either commas or periods as separators.
