### ISSUE TITLE
It's hard to swipe between subreddits in the top bar.

### ISSUE THREAD

**Issue by vinoff** [Docile-Alligator/Infinity-For-Reddit#673]
As it is, it is quite hard to swipe/change between subreddits available in the top bar. It is not smooth. For example, slide does it perfectly.

In infinity, I need to press it hard and my finger travels quite a fair distance before I see the screen change. Would it be possible to make it faster/smoother/not-so-hard?

**Comment by Docile-Alligator** [comment]
This is because I intentionally increased the threshold. Otherwise, you will accidentally swipe to other subreddits too easily. It's caused by the ViewPager2 library.
