### ISSUE TITLE
Message typing box font is way too small

### ISSUE THREAD

**Issue by ramansg** [Docile-Alligator/Infinity-For-Reddit#677]
The text box in the chat where the typed message is displayed before sending it, has a very small font size in comparison to the sent and receive text messages.

![Screenshot_20220227-220111_Infinity~2](https://user-images.githubusercontent.com/19746632/155895215-2d4dbfa4-7d48-4250-a679-b17a796ec05e.png)

 There should be a global setting of the minimum font size in settings.

**Comment by Docile-Alligator** [comment]
You can change its font size to Large in Settings->Interface->Font->Font Size
