### ISSUE TITLE
[Bug] Post layout stuck as card layout 2

### ISSUE THREAD

**Issue by MyNameIsKeegan** [Docile-Alligator/Infinity-For-Reddit#678]
I was exploring all of the settings for Infinity, and since I had never changed the "Default Post Layout" option, I decided to see what the other options looked like. Unfortunately, after changing to card layout 2 and back to card layout, all posts are still stuck as card layout 2. It correctly displays which option I've selected, but it doesn't actually apply to the posts no matter the selection.

Also of note is that setting the "Default Link Post Layout" from auto to a specific layout does work to override card layout 2 (but only for link posts, of course).

This is annoying, I do not like card layout 2.

**Comment by Docile-Alligator** [comment]
Fixed.
