### ISSUE TITLE
Default app

### ISSUE THREAD

**Issue by The-Mer0vingian** [Docile-Alligator/Infinity-For-Reddit#68]
Hello, how can i set Infinity as default reddit app?
When i'm on firefox and i click on a reddit result then click "USE APP" at the top of the page , i'm redirected to playstore to install official reddit client.

**Comment by Docile-Alligator** [comment]
This is because the official Reddit site only opens the official Reddit app.

**Comment by OHermesJunior** [comment]
Can't be done. Can be closed.

**Comment by Docile-Alligator** [comment]
Thanks.

**Comment by Wilker-a** [comment]
there is likely a way to recognize if the link opened sends an intent from the browser that can be directed to the app. if the official app can receive it, others can do too.

**Comment by OHermesJunior** [comment]
Right, I got it working, but it looses context (like if it should open in a subreddit, or a specific post). Will be working on it and send a pull request.

**Comment by OHermesJunior** [comment]
It works fully now. Sent the pull request.
