### ISSUE TITLE
App Crashes when unlocking device

### ISSUE THREAD

**Issue by legendsayantan** [Docile-Alligator/Infinity-For-Reddit#682]
If I had Infinity running before locking the device , and then unlock the device later... Infinity opens and crashes immediately.

_Device in running android 11._

**Comment by legendsayantan** [comment]
This is the logcat output...

`03-10 22:51:04.434 29578 29578 D AndroidRuntime: Shutting down VM
03-10 22:51:04.435 29578 29578 E AndroidRuntime: FATAL EXCEPTION: main
03-10 22:51:04.435 29578 29578 E AndroidRuntime: Process: ml.docilealligator.infinityforreddit, PID: 29578
03-10 22:51:04.435 29578 29578 E AndroidRuntime: java.lang.IllegalStateException: Can't access ViewModels from detached fragment
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at androidx.fragment.app.Fragment.getViewModelStore(Fragment.java:398)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at androidx.lifecycle.ViewModelProvider.<init>(ViewModelProvider.java:114)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at ml.docilealligator.infinityforreddit.fragments.PostFragment.initializeAndBindPostViewModel(PostFragment.java:1195)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at ml.docilealligator.infinityforreddit.fragments.PostFragment.lambda$onCreateView$3$PostFragment(PostFragment.java:942)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at ml.docilealligator.infinityforreddit.fragments.PostFragment$$ExternalSyntheticLambda4.success(Unknown Source:2)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at ml.docilealligator.infinityforreddit.FetchPostFilterReadPostsAndConcatenatedSubredditNames.lambda$fetchPostFilterAndReadPosts$1(FetchPostFilterReadPostsAndConcatenatedSubredditNames.java:37)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at ml.docilealligator.infinityforreddit.FetchPostFilterReadPostsAndConcatenatedSubredditNames$$ExternalSyntheticLambda4.run(Unknown Source:4)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:255)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8212)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
03-10 22:51:04.435 29578 29578 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)03-10 22:51:04.436  1679  1718 V ColorZoomWindowManagerService: onAnimationFinished:  r = ActivityRecord{8b28d1d u0 ml.docilealligator.infinityforreddit/.activities.MainActivity t12806}
03-10 22:51:04.436  1679  1718 I ColorAppSwitchManagerService:  handleAppVisible , r = ActivityRecord{8b28d1d u0 ml.docilealligator.infinityforreddit/.activities.MainActivity t12806}
03-10 22:51:04.437  1679  1718 I OplusMirageDisplayManagerService: onAnimationFinished:
03-10 22:51:04.447   908   908 D OppoExLayer: ~Layer() sequence=106592, name=Surface(name=Task=12806)/@0x6e89a1 - animation-leash#0@0xb4000073ede27000
03-10 22:51:04.447   908   908 D OppoExLayer: ~Layer() sequence=106593, name=Surface(name=c52f778 ColorOSEdgeFloatBar)/@0xf5e3cb4 - animation-leash#0@0xb4000073ede8e000`

**Comment by Docile-Alligator** [comment]
Thank you for the logs! I will look into it.

**Comment by Docile-Alligator** [comment]
It's probably fixed now. And you can wait for v5.1.9 release to see if this is still happening.

**Comment by legendsayantan** [comment]
Updated to 5.1.9

Still crashing some times, but less frequent.
