### ISSUE TITLE
Inapp webview states get lost after device rotation

### ISSUE THREAD

**Issue by mmc20520** [Docile-Alligator/Infinity-For-Reddit#683]
Inapp webview states get lost after device rotation

Before rotation:
<img width="293" alt="Screen Shot 2022-03-07 at 4 18 48 PM" src="https://user-images.githubusercontent.com/100833575/156993909-894f57e0-84e1-4f74-83ed-083060860405.png">

After rotation:

<img width="619" alt="Screen Shot 2022-03-07 at 4 18 58 PM" src="https://user-images.githubusercontent.com/100833575/156993936-a88e2298-764e-4568-b3b5-71f2055ffcb4.png">

I was testing on v5.1.7 on Android 10

**Comment by Docile-Alligator** [comment]
Fixed.
