### ISSUE TITLE
Remove floating action button.

### ISSUE THREAD

**Issue by CopKillerAnarchist** [Docile-Alligator/Infinity-For-Reddit#684]
I want the bottom navigation toolbar without a floating button. I propose having the option to integrate that button into the toolbar itself.

**Comment by Beventar** [comment]
I agree its just annoying and looks bad

 I didnt see this issue already here so i created mine with the same thing

So im going to close mine in favour of this one

**Comment by Wladefant** [comment]
duplicate of #1036
