### ISSUE TITLE
2 feature requests

### ISSUE THREAD

**Issue by fighuass** [Docile-Alligator/Infinity-For-Reddit#69]
Hi, I just switched to Infinity from Sync since I was looking for a FOSS reddit client, but I'm missing two things that I'd like to see:

* Option for single pane UI with posts + comments to the right (for tablet users)? Similar to how Sync does it: [example](https://lh3.googleusercontent.com/_YQ1Xt3RvGBlut2tax1yFTlZxjSHgPgwrAqP3SE-fmDgKcgn6eaxXr3J5RoVo-_hVy4=w1920-h954), except more compact if possible.
* Automatic night mode (detect sunrise and sunset and automatically apply light/dark themes based on the time). 

Could you add these, please?

**Comment by Docile-Alligator** [comment]
Ok. I will try.

**Comment by Wladefant** [comment]
1. implemented
2. duplicate #18
