### ISSUE TITLE
NSFW blurred in locally created multireddits

### ISSUE THREAD

**Issue by Donkey-Doug** [Docile-Alligator/Infinity-For-Reddit#693]
All NSFW posts are blurred in locally created multireddits, even when NSFW posts are enabled.

Version 5.1.8

**Comment by Donkey-Doug** [comment]
Might only be images, not sure. It seems to work for gifs and videos.

**Comment by Docile-Alligator** [comment]
You need to disable Blur NSFW Images in Settings->NSFW & Spoiler.

**Comment by Donkey-Doug** [comment]
It is disabled. It is still blurred in local multireddits.

**Comment by traviss64** [comment]
> You need to disable Blur NSFW Images in Settings->NSFW & Spoiler.

I have tried this and played with all the option in this NSFW & SPOILER section, but still the images and videos are blurred in multireddit NSFW subreddit in ANONYMOUS mode.

**Comment by Donkey-Doug** [comment]
Same. It is a bug/issue and not a feature.

**Comment by Docile-Alligator** [comment]
Thank you. This is fixed now.
