### ISSUE TITLE
Feature Request: Show user flairs

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#7]
Text flairs and image flairs would both be nice, although text ones would be better than none.

**Comment by Docile-Alligator** [comment]
Hi, good suggestions! I will try to implement it.

**Comment by Docile-Alligator** [comment]
Hi! Text flairs are now available.

**Comment by BeeeWall** [comment]
Thanks!

**Comment by Docile-Alligator** [comment]
You are welcome!
