### ISSUE TITLE
Redgifs not Loading on Tor

### ISSUE THREAD

**Issue by MetalNeo** [Docile-Alligator/Infinity-For-Reddit#702]
Redgifs videos/gifs do not load when proxies through Tor. Issue is not present when using a VPN or no proxy. When trying to open the video link in the Tor Browser, the video fails to play there as well.

The issue appears to stem from the v.redd.it link being used to link to the video. When playing it directly from the Redgifs website, there is no issue playing the video.

Error: Error fetching Redgifs video
Phone: Pixel 5a
OS: Android 12/GrapheneOS
App Version: 5.1.9

Example post: https://www.reddit.com/r/SunnyLeone/comments/sxprl5/made_this_edit_click_redgifs_link_for_sound/
Video link from Infinity: https://v.redd.it/f1d9dz55r5j81/DASH_1080.mp4
Direct Video link on Redgifs: https://www.redgifs.com/watch/butteryfemininerhodesianridgeback

**Comment by Docile-Alligator** [comment]
This is related to Tor, not Infinity.

**Comment by MetalNeo** [comment]
Alright. I'll try and get in touch with Redgifs.

**Comment by marconiradio** [comment]
Any luck getting Redgifs working on tor?
