### ISSUE TITLE
[Feature Request] Integration of removed posts/comments service inside the app

### ISSUE THREAD

**Issue by engineer22** [Docile-Alligator/Infinity-For-Reddit#703]
It would be awesome, if it's possible, to integrate one of the most popular sites used to read deleted posts/comments natively in the app.

Add a setting to enable or disable, and when enabled add the deleted comments for example in the comment section with a special flag.

I don't know if this is out of scope for the app, but as a user who's going to those sites when a post is so controversial that mods have removed tons of comments, it would be a game changer to be able to read them within the app.

**Comment by Wladefant** [comment]
Implemented :)
