### ISSUE TITLE
NSFW options doesn't work in multireddit (in Anonymous mode)

### ISSUE THREAD

**Issue by traviss64** [Docile-Alligator/Infinity-For-Reddit#708]
I have created a multireddit with NSFW subreddits in Anonymous mode, but when I access a multireddit, the posts are blurred.

In settings, I have enabled NSFW and Blur option is off. These settings work normally browsing NSFW SUBREDDITS but when I try to browse the multireddit then these option don't work and all posts are blurred.

**Comment by Docile-Alligator** [comment]
Fixed.

**Comment by mintogreen7** [comment]
I have the same issue, although not in anonymous mode (haven't tested it).

I'm logged in, have a private multireddit with mixed NSFW/SFW subs and the NSFW stuff is blurred.

My settings:
Sensitive Content: true
Blur Sensitive Images: true
Don't blur Sensitive Images in Sensitive Subreddits: true
Blur Spoiler images: false

App version: 7.5.1
Got it from Github
