### ISSUE TITLE
In multireddit, when we filter posts, the "sort" icon doesn't work. 

### ISSUE THREAD

**Issue by traviss64** [Docile-Alligator/Infinity-For-Reddit#709]
In multireddit, when we filter posts, the “sort” icon doesn't work. 

I click on it, but it doesn't show any option. But outside multireddit the sorting function works during a filter on.

**Comment by Docile-Alligator** [comment]
Cannot reproduce this. What is your app version?

**Comment by traviss64** [comment]
> Cannot reproduce this. What is your app version?

5.1.6

[Made a post on reddit with details](https://www.reddit.com/r/Infinity_For_Reddit/comments/tpewti/anonymous_mode_issues/)

`....We found that, when browsing Infinity for Reddit app in anonymous mode there are a few issues that persist, but when we log in with our Reddit account, those issues don't seem to be there.

The issues being:-

    In anonymous mode, when we are browsing the home feed or a multireddit feed and if we apply the filter – the SORTING won't work at all.

    In anonymous mode, when we browse multireddit NSFW feed, the posts are blurred. We checked all the NSFW settings and the NSFW settings is working (posts being no blurred) if we go to a NSFW Subreddit but inside the multireddit feed all the NSFW posts are blurred out.`

**Comment by Docile-Alligator** [comment]
Fixed.

**Comment by traviss64** [comment]
Hey, 

I downloaded your v5.2.0-beta1 release and in the version the issues I talked about above are present. Can't sort with "Filter" in on in multireddit in anon mode and in multireddit nsfw posts are blurred in anon mode.
