### ISSUE TITLE
[Feature request] Copy/paste links & open in external apps

### ISSUE THREAD

**Issue by KaKi87** [Docile-Alligator/Infinity-For-Reddit#71]
Hello,

When I click on a link, it will forcibly open in the embedded browser.

Instead, I would like to be able to copy/paste them, and open them in external browsers and apps.

Thanks

**Comment by Docile-Alligator** [comment]
This feature will be available in the next update.

**Comment by Docile-Alligator** [comment]
This feature is now implemented

**Comment by KaKi87** [comment]
Now I can copy/paste raw text, thanks !
However, I still can't copy/paste links nor open them in external apps.
