### ISSUE TITLE
I took setting backup from my phone and tried to restore it in another phone and in my WSA but its not working some settings like how many tabs to display are not restored

### ISSUE THREAD

**Issue by Tetrax-10** [Docile-Alligator/Infinity-For-Reddit#717]

**Comment by engineer22** [comment]
I don't know if it's a bug, intended or even forgotten, but I did the exact same thing today and ran into the same problem.

I had to change the side panel settings and one or two more if I remember correctly, but other than that everything else restored as expected.

**Comment by Tetrax-10** [comment]
@engineer22  Yeah many settings are not working. I don't know whether [Docile-Alligator](https://github.com/Docile-Alligator) is reading these issues or not. He created this very good app and a lot of people use it but now, he is not carrying about it. The issue count is 226.

**Comment by winstoncooke** [comment]
> @engineer22 Yeah many settings are not working. I don't know whether [Docile-Alligator](https://github.com/Docile-Alligator) is reading these issues or not. He created this very good app and a lot of people use it but now, he is not carrying about it. The issue count is 226.

Hi @Tetrax-10 . Thank you for bringing this issue to attention. Please note maintaining a project of this size without payment requires an incredible amount of effort. Additional help to get through every issue is more realistic than a single developer taking it on by themselves. If you are able to help with this issue, I welcome you to fix it and make a pull request!

**Comment by winstoncooke** [comment]
> I don't know if it's a bug, intended or even forgotten, but I did the exact same thing today and ran into the same problem.
> 
> I had to change the side panel settings and one or two more if I remember correctly, but other than that everything else restored as expected.

Would you and @Tetrax-10 be able to compile a list of the settings that did not successfully transfer over?

**Comment by engineer22** [comment]
> > I don't know if it's a bug, intended or even forgotten, but I did the exact same thing today and ran into the same problem.
> > 
> > I had to change the side panel settings and one or two more if I remember correctly, but other than that everything else restored as expected.
> 
> Would you and @Tetrax-10 be able to compile a list of the settings that did not successfully transfer over?

I'd love to help. I will reproduce the issue on a clean install and take note of undone changes.

Do you want me to tag you later this week with the list, in this thread?

**Comment by winstoncooke** [comment]
Sure thing! I can't promise I'll be the one to fix it, but it would be very helpful to have a complete list here.
It may simply be the case of new features that were added after the import tool was created, and it needs to be updated.

**Comment by Tetrax-10** [comment]
@winstoncooke sure, shortly i will post a list of settings that are not syncing with the backup file
