### ISSUE TITLE
[Bug] Images viewer is broken most of the times i open a picture

### ISSUE THREAD

**Issue by DaniAndTheWeb** [Docile-Alligator/Infinity-For-Reddit#721]
The image viewer is behaving strangely, throught scrolling everything is fine but when i open a picture the image viewer can't load the images correctly most of the times and it's unable to zoom.
![Screenshot_20220331-084604_Infinity](https://user-images.githubusercontent.com/57776841/160995499-64486c2b-bc85-4505-9b37-9adcf6dbb50b.png)
![Screenshot_20220331-084609_Infinity](https://user-images.githubusercontent.com/57776841/160995518-48eb3cdc-061a-407a-ad4e-cdb9d502cd73.png)

**Comment by Docile-Alligator** [comment]
Cannot reproduce this. What is your device? Did you change any settings related to dpi?

**Comment by DaniAndTheWeb** [comment]
I'm using a poco f3 on android 12 but it also happens on my galaxy s9 with aosp rom. I don't changed any dpi setting.
I tried downloading the images but they're simple jpegs.

**Comment by DaniAndTheWeb** [comment]
On the latest beta build the problem seems to have been fixed. I haven't seen the commit that has fixed the behaviour but for now I think it's right to close the issue.
