### ISSUE TITLE
GIFs are not displayed in post view

### ISSUE THREAD

**Issue by kappa7194** [Docile-Alligator/Infinity-For-Reddit#723]
When I open a post that contains a GIF image the image is not shown and the "link" placeholder image is displayed in its place.

When I click the area where the image should be displayed the image is immediately displayed full-screen.

When I click the "share" button it too thinks that the GIF is a link instead of an image (it displays "copy link URL" instead of "image").

Infinity for Reddit version: 5.1.9

Android version: 12

**Example**

Post URL:

https://www.reddit.com/r/dataisbeautiful/comments/ts5nbl/antarctic_heatwave_march_2022_oc/

Image URL:

https://i.redd.it/mbhluienoiq81.gif

What is shown in the app:

![Screenshot_20220331-110930_Infinity](https://user-images.githubusercontent.com/1249988/161020904-afbf923b-6461-46c0-85ff-242c7e38b86a.png)

![Screenshot_20220331-111233_Infinity](https://user-images.githubusercontent.com/1249988/161020920-d5d34d80-5624-4ded-888d-b0c93722d3e0.png)

![Screenshot_20220331-110938_Infinity](https://user-images.githubusercontent.com/1249988/161020936-8156f5e3-3974-4ab3-a888-727f635312d8.png)

**Comment by Wladefant** [comment]
Is it still an issue?
