### ISSUE TITLE
There's a `!<` at the end of the spoiler text

### ISSUE THREAD

**Issue by BreadGenie** [Docile-Alligator/Infinity-For-Reddit#726]
There's a `!<` at the end of the spoiler text and it seems like the last letter of the text is replaced by `!<`.
![Screenshot_20220402-113221_Infinity~2.png](https://user-images.githubusercontent.com/63963181/161369139-f86114e2-37da-49d4-9a0a-9908b1b91c9f.png)

[comment link](https://www.reddit.com/r/Unexpected/comments/tu930o/whats_up_peppa/i32fmdt/)

**Comment by Docile-Alligator** [comment]
Thank you for reporting this. It's fixed.
