### ISSUE TITLE
Spoiler tags overwrite last two characters

### ISSUE THREAD

**Issue by godkarmachine** [Docile-Alligator/Infinity-For-Reddit#728]
I'm experiencing a problem in recent versions with spoiler formatting. The last two characters of the spoiler appear to be overwritten with the close spoiler tag.

Using this comment as an example: https://www.reddit.com/r/SquaredCircle/comments/tuwcno/live_wwe_wrestlemania_38_wrestlemania_saturday/i35yggd/

This is what I am seeing. 
![IMG_20220402_185349](https://user-images.githubusercontent.com/1330252/161405380-571f256c-882a-4560-a43f-853d1931ed46.jpg)

I am running Infinity 5.1.9 on a OnePlus 6 running LineageOS 18.1.

**Comment by ywssp** [comment]
Also happens on my device
Android 10
Infinity v5.1.9

![Screenshot_20220404-092416_Infinity](https://user-images.githubusercontent.com/46750010/161459497-41458388-9929-4c91-ba45-2d49d9b3b681.jpg)

**Comment by minhperry** [comment]
![Screenshot_20220406-142047_Infinity](https://user-images.githubusercontent.com/46137516/161973495-d4961af6-bd42-4391-a680-acd7e615042a.jpg)
Can confirm, Android 12 latest infinity version

**Comment by Pixxel123** [comment]
Can also confirm this is happening on my device.

Android 10
One UI 2.5

Infinity version 5.1.9

**Comment by Docile-Alligator** [comment]
This will be fixed in v5.2.0. Thank you.
