### ISSUE TITLE
Can't Follow User in Search Results List

### ISSUE THREAD

**Issue by enchainingrealm** [Docile-Alligator/Infinity-For-Reddit#732]
I am running Infinity 5.1.9 on a Pixel 2 running Android 11.

Steps to reproduce the bug:

1. Open the app and search for any user.
2. Tap the Users tab in the search results page.
3. Tap a "+" button in the search results list to follow that user.

Instead of following the user, a toast appears that says "Following Failed". To follow the user, I need to:

4. Tap the username in the search results list to open that user's page.
5. Tap the "Follow" button.

**Comment by Docile-Alligator** [comment]
Cannot reproduce this. Is this problem still happening?

**Comment by elea11** [comment]
> Cannot reproduce this. Is this problem still happening?

Yes, happening here too. Neither following from search list nor via opening the profile and tapping 'follow' works.

Tried to reinstall, re-login, cleared app data. Disabled Adaway. Nothing helped.

Latest Infinity version (5.3.4), Pixel 4a 5G, Lineage OS 20 (Android 13), MicroG.

**Comment by Wladefant** [comment]
hey @elea11 that is another issue. Try opening a new bug report? (not sure if we can help you)

**Comment by elea11** [comment]
> hey @elea11 that is another issue. Try opening a new bug report? (not sure if we can help you)

Done in #1361.
