### ISSUE TITLE
Customise Bottom Navigation Bar behaves incorrectly 

### ISSUE THREAD

**Issue by accelyte** [Docile-Alligator/Infinity-For-Reddit#734]
To reproduce:
1. Choose "Refresh" as floating button action type
2. Restart app
3. Return to app to see the setting indicate that I'm using "Change Sort Type"

Seems like the selector is incremented incorrectly. If you choose the last option "Filter Posts", the app crashes back to the home screen.

**Comment by Docile-Alligator** [comment]
Cannot reproduce this problem. What is your app version?

**Comment by accelyte** [comment]
Version 5.1.9, I'm on the Pixel 6

**Comment by accelyte** [comment]
Here's a short video of the same issue that I recorded on Bluestacks: https://imgur.com/a/bNoN8fO

**Comment by Docile-Alligator** [comment]
Fixed.

**Comment by huubert** [comment]
I have just encountered this issue while messing with the Navigation Bar settings. It's totally bugged, even after restarting the phone.
