### ISSUE TITLE
Feature Request: Open Multireddit Links

### ISSUE THREAD

**Issue by DatAres37** [Docile-Alligator/Infinity-For-Reddit#74]
Hi, I've just switched to Infinity and I noticed that it's not possible to open multireddit links like https://www.reddit.com/r/news+worldnews/ if you open them with the app. The link is opened in the default browser inside Infinity.

Thanks & Cya

**Comment by Docile-Alligator** [comment]
Yes. I haven't seen this kind of links before.

**Comment by OHermesJunior** [comment]
Done, can be closed.
