### ISSUE TITLE
Feature request: Post limit to prevent doomscrolling

### ISSUE THREAD

**Issue by TheEdgeOfRage** [Docile-Alligator/Infinity-For-Reddit#740]
Having an endlessly scrolling feed is quite addicting to me, so having a feature where I could limit the number of posts that can show up in a given feed would be pretty cool. A possible addition would be to be able to set the limit only on some feeds, like the frontpage, /r/All, etc.

I found issue #155 that is asking for a similar thing, but having just the hard limit is a different feature and might be easier to implement than pagination in a mobile app when there's already an endless-scrolling library in use.

**Comment by yaomtc** [comment]
That issue was converted to a discussion. https://github.com/Docile-Alligator/Infinity-For-Reddit/discussions/913

I just found [RedReader](https://github.com/QuantumBadger/RedReader/) has this feature, so I'm using that now.
