### ISSUE TITLE
Caret doesn't format properly in code blocks

### ISSUE THREAD

**Issue by ztiaa** [Docile-Alligator/Infinity-For-Reddit#742]
When using a caret (^) inside a code block (\`\`\`) it formats as ```<sup>...</sup>```

How I typed it:

![IMG_20220410_014906.jpg](https://user-images.githubusercontent.com/68632494/162595307-c9c47108-e7b8-483b-8c5f-d1e487597ced.jpg)

How it appears:

![IMG_20220410_014954.jpg](https://user-images.githubusercontent.com/68632494/162595318-e3efcfd3-d98e-4e45-b6b4-6b2267ccd136.jpg)

**Version: 5.1.9**

**Comment by quazar-omega** [comment]
Same is true for inline code:
![infinityforreddit-mardown-code-caret](https://user-images.githubusercontent.com/56311398/169707483-92c2d11b-acc9-42ba-9a9c-dd14f3eb6176.jpg)
![infinityforreddit-mardown-code-caret-preview](https://user-images.githubusercontent.com/56311398/169707484-4d0a41fc-3636-46e2-a98b-9c2009547800.jpg)

**Comment by Wladefant** [comment]
Hey @casperklein I am not able to reproduce your bug. 5.4.0 beta. But I don't think we changed the parser in the meantime. 

![Screenshot_20230202-231610_Infinity.jpg](https://user-images.githubusercontent.com/79611093/216461700-8fcc9ce7-959a-4e26-9f90-c9e7f23ad646.jpg)

**Comment by casperklein** [comment]
I've updated to `v5.4.0-beta4` and the issue is gone 👍
