### ISSUE TITLE
Filter doesn't work with nsfw posts.

### ISSUE THREAD

**Issue by Readf0x** [Docile-Alligator/Infinity-For-Reddit#749]
Nsfw posts don't show up when you use the filter option, which also means that if you attempt to use flair or post type sorting it doesn't show nsfw posts. This doesn't apply to permanent filters set manually in settings, only temporary ones. I tried downgrading to 5.1.8, but the issue persisted, though that did work for others.

**Comment by Docile-Alligator** [comment]
Fixed.
