### ISSUE TITLE
No Notifications and not push detect using MicroG

### ISSUE THREAD

**Issue by Milor123** [Docile-Alligator/Infinity-For-Reddit#753]
Hi dear guys! It cant recieved notifications 

I am using CrDroid lastest, A12L rooted phone with microG, i try clean the app, reconfigure, do a clean install in a new ROM but it not work for me

I  would like get my reddit notifications on push, please help me. Thank u very much for this app, is amazing i love it.

**Comment by Docile-Alligator** [comment]
You could try v5.2.0-beta1. It probably fixes notification problems.

**Comment by Milor123** [comment]
> You could try v5.2.0-beta1. It probably fixes notification problems

Not work, yesterday and today I`ve  tested it, not work in nothing version, neither the beta. Simply microG font register the GCM push and if u are using other methods not work :(

**Comment by Wladefant** [comment]
Please download the latest version and check if it works for you
