### ISSUE TITLE
[Feature request] Open link in the app with Share [share link handler]

### ISSUE THREAD

**Issue by Dangelman** [Docile-Alligator/Infinity-For-Reddit#754]
**Requested feature:**
Add the possibility to open Reddit links in the app with the share option (not posting, just opening).
It's a common feature that can be found in many apps like Sync (Reddit) and NewPipe (YouTube), and I find it handy

**Screenshot:**
![Screenshots_2022-04-20-14-51-32](https://user-images.githubusercontent.com/26676154/164234537-19a28ea7-993c-4613-b93d-18547a5b9f5b.png)

**Comment by SimpleProgrammingAU** [comment]
If you have the latest version of Android, you need to give the app specific permission to open links.

Go to App Info (by pressing and holding on the app icon) --> Open By Default --> + Add Link

Then you can select the links you would like to open from the app.

**Comment by Dangelman** [comment]
@SimpleProgrammingAU I have Android 11 and I've set Reddit links to open in Infinity by default, but that's not what I meant with the post.

I'm specifically asking for the feature to open links with Infinity through the Share button which allows for easy transition to Infinity if for whatever reason I'm browsing posts on the Reddit app or another app where I can't just click a Reddit URL.

**Comment by Docile-Alligator** [comment]
Done.
