### ISSUE TITLE
Clicking "Submit a new report" links you to a nsfw post that happens to have "report" in its url.

### ISSUE THREAD

**Issue by gurraba** [Docile-Alligator/Infinity-For-Reddit#757]
![Screenshot_20220426-120341](https://user-images.githubusercontent.com/60556506/165278270-8a3ffa71-f74a-45db-9a34-ff8d57da9fa4.jpg)
![Screenshot_20220426-121008](https://user-images.githubusercontent.com/60556506/165278284-c0b8fc02-2163-4191-bcfa-b02c10bd81c2.jpg)

**Comment by Docile-Alligator** [comment]
Is the report page's url https://reddit.com/report ?

**Comment by Wladefant** [comment]
> Is the report page's url https://reddit.com/report ?

Yes it is
