### ISSUE TITLE
NSFW post does not get blurred out, when using search function.

### ISSUE THREAD

**Issue by MrDuck6** [Docile-Alligator/Infinity-For-Reddit#769]
When searching reddit through search bar, any post containing NSFW images/videos does not get blurred out. 

Only happens in results page, clicking on post blurs out the post.

NSFW settings:

Enable NSFW: ON
BLUR NSFW images: ON
Don't blur NSFW images in NSFW subreddits: OFF
Blur spoiler images: ON

**Comment by MrDuck6** [comment]
update: Blur work but only for images and videos. NSFW gif does not get blurred out.

**Comment by Docile-Alligator** [comment]
Fixed.
