### ISSUE TITLE
Missing Confirm Edit button

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#77]
version 3.0.0 on Android 5.1.1

the button for sending comment edits is missing from the comment edit screen.

###### in the post edit screen, the button seems to remain.

**Comment by Docile-Alligator** [comment]
Could you send a screenshot?

**Comment by Wilker-a** [comment]
i couldn't find a good comment to screenshot on, but what i found is that comments long enough to enable scrolling hides the top bar and makes me unable to click the buttons, and that is the thing causing the issue for me..

**Comment by zwu513** [comment]
I can replicate this issue on 3.0.2. 
https://imgur.com/a/C1mkwQK

**Comment by Docile-Alligator** [comment]
This bug is fixed on version 3.0.3.

**Comment by Wilker-a** [comment]
thank you uwu :heart:
