### ISSUE TITLE
Use redd.it short-links whenever possible when sharing

### ISSUE THREAD

**Issue by anyone00** [Docile-Alligator/Infinity-For-Reddit#775]
when sharing comment and post links from Infinity, it is sometimes very long and would be nice to use the redd.it short links.

for example from:
https://www.reddit.com/r/Infinity_For_Reddit/comments/k1hyaj/support_me_on_patreon/

to:
https://redd.it/k1hyaj

**Comment by yephny** [comment]
I don't think this is a good approach at all. You never know what page a shortened link is going to lead to before you click it.

**Comment by Wladefant** [comment]
I also think the full link is better

**Comment by Docile-Alligator** [comment]
The response from Reddit API does not contain shortened link.
