### ISSUE TITLE
Unable to build as some dependencies are no longer publicly available

### ISSUE THREAD

**Issue by xeals** [Docile-Alligator/Infinity-For-Reddit#779]
Copying this from my Reddit comment bringing up the issue:

With the closure of JCenter, some dependencies of Infinity are no longer available at either their configured group-artifact-version triples or at all. This affects building via CI for providers that don't have the cached dependencies from nearly six months ago, and new contributors and people building for themselves.

https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/3df7b761a29159368b4df32a28b1caed5006783a/app/build.gradle#L74-L78

Google provides a Maven repository at https://maven.google.com/, but does not provide builds of the version that Infinity uses. https://github.com/Docile-Alligator/Infinity-For-Reddit/pull/593#issuecomment-1013976203 locks us to this version, however. [JitPack is unable to build it](https://jitpack.io/com/github/google/exoplayer/r2.10.8/build.log), which should probably be reported upstream it if it's something that can be resolved.

https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/3df7b761a29159368b4df32a28b1caed5006783a/app/build.gradle#L79-L83

Toro is publicly available and builds through JitPack; the group ID only needs updating to `com.github.eneim.toro`.

https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/3df7b761a29159368b4df32a28b1caed5006783a/app/build.gradle#L171

As best as I can find, [this dependency](https://mvnrepository.com/artifact/com.libRG/customtextview/2.4) has [no public builds](https://github.com/Rajagopalr3/CustomizedTextView) after v2.2. It appears to not have been uploaded to any other Maven repository and the source repository (based on commit/release dates) does not contain code for v2.4.

**Comment by xeals** [comment]
CustomTextView seems fine (as in, doesn't break the app) to downgrade to the last available build.

ExoPlayer has breaking API changes between 2.10 and 2.13 (the oldest version in the Google repo) and Toro won't accept running with the newer version. I'm not 100% sure how involved porting it to 2.13+ would be, because Android Studio won't let me work with it (build scripts too old), and I'm not interesting in maintaining it either.

Given the licenses allow for it (both Apache), it might be easier for someone with ExoPlayer 2.10.8 and CustomTextView 2.4 to vendor them into the tree until they can be upgraded or replaced.

**Comment by Docile-Alligator** [comment]
Fixed. Infinity is now using the latest version of ExoPlayer.
