### ISSUE TITLE
[Feature request] Implement search in the Subscriptions page

### ISSUE THREAD

**Issue by Jnss98b** [Docile-Alligator/Infinity-For-Reddit#78]
It would be really convenient if we could search for our subscribed subreddits and users instead of having to scroll manually

![Screenshot_20200407-170436](https://user-images.githubusercontent.com/24306400/78719596-2e27cb00-78f2-11ea-9462-bfd806770834.png)

**Comment by Docile-Alligator** [comment]
I will try.

**Comment by Docile-Alligator** [comment]
Done
