### ISSUE TITLE
[Bug] Spoiler tags replace two last characters after clicking

### ISSUE THREAD

**Issue by vahaala** [Docile-Alligator/Infinity-For-Reddit#781]
Version : 5.1.9
Theme : Dark, with Amoled Dark

![Screenshot_20220520-161827_Infinity](https://user-images.githubusercontent.com/5729654/169548630-e65ef32b-2f30-48cb-8f22-ebbe362beaa3.jpg)
This is how spoiler tag appears when typing it in. Pretty normal, right?
Now let's see if it works.
![Screenshot_20220520-161831_Infinity](https://user-images.githubusercontent.com/5729654/169548712-6a528b6d-f3cf-4587-98f3-1d8dc03dce78.jpg)
It looks like it does. But once you click on the spoiler tagged content, it gets cut up and last two (sometimes, but rarely, more) characters are replaced with spoiler closing tags.
![Screenshot_20220520-161835_Infinity](https://user-images.githubusercontent.com/5729654/169548947-7b1aefc3-7830-43a2-bd37-548d7625c5e6.jpg)

This is happening on every spoiler tagged text I've come across.

**Comment by TheSingular** [comment]
The same is happening to me, I was just going to post a bug report about this:
![Screenshot_20220531-190137_Infinity](https://user-images.githubusercontent.com/18699171/171218578-71491d98-7530-4fec-8e81-c716dcc70e70.jpg)

**Comment by vahaala** [comment]
It appears to be fixed now.
![Screenshot_20220606-003001_Infinity](https://user-images.githubusercontent.com/5729654/172073273-c8b85f33-5ec3-483c-87a3-6b919c593034.jpg)
![Screenshot_20220606-003009_Infinity](https://user-images.githubusercontent.com/5729654/172073276-c6e96cf6-aaf0-4a80-9515-f0f2716944d3.jpg)
![Screenshot_20220606-003012_Infinity](https://user-images.githubusercontent.com/5729654/172073284-c57c7fce-0b86-43be-ac3f-f1f20da58915.jpg)

If someone can confirm it is indeed fixed, that would be nice.

**Comment by Docile-Alligator** [comment]
Fixed in v5.2.0.
