### ISSUE TITLE
Floating action button disappears on posts when scrolling down

### ISSUE THREAD

**Issue by jac0b-w** [Docile-Alligator/Infinity-For-Reddit#79]
When on a post the 'next comment' floating button disappears when you scroll down.

This means as you start to scroll down the page to look at the next comment this button disappears right when you need it. I suggest that this button doesn't disappear at all or only when scrolling up (not down).

**Comment by Docile-Alligator** [comment]
Go to settings-> gestures & buttons -> Turn on Lock Jump to Next Top-level Comment Button
