### ISSUE TITLE
Horizontal Scrolling Issue with Tables

### ISSUE THREAD

**Issue by realmain** [Docile-Alligator/Infinity-For-Reddit#796]
I can scroll to the right without any issue for tables, but whenever I try to scroll to the left, it wants to take me back to the post feed instead of scrolling the table.

I.E. https://www.reddit.com/r/arknights/comments/v8ad5w/module_details_lingering_echoes/

**Comment by Wladefant** [comment]
https://user-images.githubusercontent.com/79611093/178490569-d257dd7d-ca69-456a-91b6-2cfe135ee0d9.mp4

**Comment by 1rre** [comment]
I have the same issue - I'd say it's categorically a bug as there's no way to get the table back to the left without reloading the post

**Comment by 1rre** [comment]
Ah that works, but definitely seems illogical, especially when you're all the way to the right
