### ISSUE TITLE
Back navigation gesture broken on Android 13 beta 3

### ISSUE THREAD

**Issue by andreaippo** [Docile-Alligator/Infinity-For-Reddit#798]
Hello, I'm using a Pixel 6 Pro with Android 13 beta 3 and gesture navigation enabled. Infinity for Reddit 5.2.0

Since updating to this beta I've noticed that the back gesture is not effective in Infinity when opening a post, trying to comment on it, and then trying to go back to the main stream (e.g. Home or Popular).

Could you please look into it?

Thanks!

Screen recording here:
https://photos.app.goo.gl/TXTGHXQ2s7oXvaNG7

**Comment by Docile-Alligator** [comment]
Thank you for reporting this. I will check if this is an issue from Android 13 or not.

**Comment by Docile-Alligator** [comment]
I think this problem is fixed in Android 13 Beta 3.2. Could you update your device and check it?

**Comment by andreaippo** [comment]
Indeed it's working fine with the latest beta! Thanks anyway.
Close #798.

**Comment by Wladefant** [comment]
> Indeed it's working fine with the latest beta! Thanks anyway.
> Feel free to close :)

You cam also close this issue :)

**Comment by andreaippo** [comment]
> > Indeed it's working fine with the latest beta! Thanks anyway.
> > Feel free to close :)
> 
> You cam also close this issue :)

Indeed I hadn't noticed I had the power to do so, wow! Closed 😊
