### ISSUE TITLE
Feature Request: Subreddit sidebars

### ISSUE THREAD

**Issue by BeeeWall** [Docile-Alligator/Infinity-For-Reddit#8]
Either via a button, similar to what if I remember correctly the mobile site has, or via swiping out from one side.

(Also, sorry for making so many issues, these are just all features I thought of and wanted to suggest before I forgot, and I feel GitHub is a better place to do so than the /r/Android thread I saw.)

**Comment by Docile-Alligator** [comment]
Hi there, I will implement it in the future. No problem! I am really happy to get these suggestions!

**Comment by prathwishshetty** [comment]
Well I'm not really sure this is a good idea as Android is moving towards gesture navigation and is trying to get rid of the side bar. maybe you can have it as an option.

**Comment by Docile-Alligator** [comment]
Hey! No problem! Hopefully I can come up with a good solution.

**Comment by Docile-Alligator** [comment]
Hey! No problem! Hopefully I can come up with a good solution.

**Comment by Docile-Alligator** [comment]
Solved.
