### ISSUE TITLE
Missing comments

### ISSUE THREAD

**Issue by hho** [Docile-Alligator/Infinity-For-Reddit#800]
Some (but not all?) third-level comments are never shown. For example, in https://www.reddit.com/r/XMG_gg/comments/v8cx7r/schenker_vision_14_2022_refresh_concerns_about/ there are 2 third-level replies to https://www.reddit.com/r/XMG_gg/comments/v8cx7r/schenker_vision_14_2022_refresh_concerns_about/ibqt3x4/ - but these are only shown when you open the comment link directly, not via the post link (not even after clicking "Load more comments").

What gives?

**Comment by Wladefant** [comment]
It does work when you click load more comments

**Comment by hho** [comment]
It doesn't for me: https://user-images.githubusercontent.com/478228/184339836-a32f8fcd-0e9a-4623-bd17-993cf3747e86.mp4
