### ISSUE TITLE
[BUG] Account selection authentication only works once

### ISSUE THREAD

**Issue by Obsidiman01** [Docile-Alligator/Infinity-For-Reddit#802]
The option to require authentication before opening the account selection drop-down only forces authentication once. After that, the drop-down can be accessed freely without authentication. Turning the setting off and on makes it work again, but still only one time.

**Comment by Docile-Alligator** [comment]
I think this is already fixed in v5.2.0. Could you update your app and check it?

**Comment by Obsidiman01** [comment]
I can confirm that updating did indeed fix it. I thought I had checked for a new version before opening this issue, but maybe F-Droid just didn't show it. Anyway, problem solved, cheers!
