### ISSUE TITLE
Most videos are showing "Fetch Redgifs video failed"

### ISSUE THREAD

**Issue by KazKaz90** [Docile-Alligator/Infinity-For-Reddit#803]
I used to be able to play the videos, and they are also viewable on the web, but now the majority of them display "Fetch Redgifs video failed."

⚠️ NSFW stuff btw

**Comment by milkywaymetropolis** [comment]
Same here. Almost every video says it.

**Comment by Dark-WizZ** [comment]
Please.fix this

**Comment by Mac-or-Mac** [comment]
Experiencing the same issue. Tried vpn off and on, resetting application and deleting / installing again no change. Only started the last couple of days that I have noticed.

**Comment by Docile-Alligator** [comment]
I think this is caused by the redgifs server. It fetches the videos without error now. Could you help me check it?

**Comment by gabey14** [comment]
Problem is fixed I think

**Comment by Docile-Alligator** [comment]
I cannot reproduce this issue but I am aware of it. @milkywaymetropolis

**Comment by Docile-Alligator** [comment]
@milkywaymetropolis I will disable saving videos with audio in the next version for Android version < 7.1. The problem is because one library file is not available in lower Android versions.
