### ISSUE TITLE
App No notification 3 works. phones differents

### ISSUE THREAD

**Issue by Milor123** [Docile-Alligator/Infinity-For-Reddit#807]
Infinity notifications push not work

Poco x3 pro root crDroid A12 (MicroG)
{Only works, the messages notification }
![IMG_20220618_050515_343.jpg](https://user-images.githubusercontent.com/14153649/174433082-8549b916-b8ad-424f-816c-da62377c7ebc.jpg)

Samsung galaxy s7 stock ROM A11 (no root, with google services)
![IMG_20220618_050518_958.jpg](https://user-images.githubusercontent.com/14153649/174433097-a4add0be-f539-4e7c-b7c7-98e10328609f.jpg)

Huawei mate 10 lite root CAOS A11 (MicroG)
![IMG_20220618_050528_850.jpg](https://user-images.githubusercontent.com/14153649/174433125-3cd6e7a8-a226-4d62-b50b-f39136d569a2.jpg)

All my notification are enabled in my account,  it not work in inifity, in the nornal reddit app work good like you can see in the next
 photo:![IMG_20220618_050517_526.jpg](https://user-images.githubusercontent.com/14153649/174433204-a22c4755-5e92-4531-9d37-e98c36530204.jpg)

**Comment by Wladefant** [comment]
Please download the latest version and check if it works
