### ISSUE TITLE
[Feature Request] Add single tap to close comments

### ISSUE THREAD

**Issue by sweetlikekendy** [Docile-Alligator/Infinity-For-Reddit#81]
Hello, love this reddit client. Been thinking about using it over boost. But I was wondering if it's possible to add a single tap to close the comments instead of a long press?  

Edit:
Another request, user's flair(s) per subreddit?

**Comment by Docile-Alligator** [comment]
Good idea. You mean showing user's flair in posts?

**Comment by sweetlikekendy** [comment]
I was more concerned about comments. For example, in r/NBA, some users would have a flair of the team they support.

**Comment by OHermesJunior** [comment]
Done, can be closed.
