### ISSUE TITLE
Downloaded Videos are all broken 

### ISSUE THREAD

**Issue by Nabiota** [Docile-Alligator/Infinity-For-Reddit#813]
I noticed my downloaded videos are all broken. Then I installed a clean version of Infinity for reddit, downloaded several videos. Interesting fact is that only the first video is not broken, but after that all the videos are broken. (Broken meaning players tells me 'cannot play this file')

**Comment by Docile-Alligator** [comment]
Hi @Nabiota is your Android version lower than 7.1?

**Comment by Nabiota** [comment]
I really don't know the problem, but recently i switched to a new phone and it's working. Sorry for opening this issue.
