### ISSUE TITLE
[Feature request] Some feature requests to the UI

### ISSUE THREAD

**Issue by Indreya** [Docile-Alligator/Infinity-For-Reddit#815]
1. Make the divider between posts thicker
![infinity-1](https://user-images.githubusercontent.com/26198011/175489096-e4f397f7-c999-48d9-a251-eb1366226d24.jpg)

2. Add an option to move the post title, subreddit, OP and tags above the post image in cards 2.0.
![infinity-3](https://user-images.githubusercontent.com/26198011/175488763-cdc0899c-d31d-4082-bcee-034ccfe7dce7.jpg)

3. Make the divider between parent comments thicker similar to the post divider above
4. Make the upvote and downvote arrow like in the image above
5. Reduce the space between the post title, tags and the post actions (upvote, downvote and comment bar)

**Comment by Wladefant** [comment]
1. Agree for card layout 2
2. Definitely, as this makes much more sense
3. Agree
4. Looks better, but maybe nothing that thick and nearer together
5. Agree

**Comment by Wladefant** [comment]
Everyone who is interested in this feature please upvote

**Comment by Uka-Uka** [comment]
> 4. Looks better, but maybe nothing that thick and nearer together

I wish infinity inherits reddit native app icons

**Comment by Wladefant** [comment]
Please add each request to its own post

**Comment by Wladefant** [comment]
@Indreya Please add your feature requests to the github discussion and one per post

**Comment by Drangonfly30** [comment]
@Wladefant  I'm really interested in this Layout. Can I add this feature request to github discussion as you asked?

**Comment by Wladefant** [comment]
@Drangonfly30 yes of course
