### ISSUE TITLE
Notifications bypass security

### ISSUE THREAD

**Issue by andmagdo** [Docile-Alligator/Infinity-For-Reddit#816]
Explanation: the app polls for inbox items every so often and displays them as notifications. These notifications force the app to ignore the security restrictions.

Expected outcome: When the app is locked, clicking on a notification will prompt the user to log in

Real outcome: When the app is locked, notifications allow access to the inbox without any unlock prompt

Video showing this anomaly follows; however due to the security of android, the biometric security does not show up (with the screen blacked out instead), and due to my laziness, I don't show the cursor. The initial unlock was to show the security settings, then the app was closed and the issue is shown.

https://user-images.githubusercontent.com/62532857/175750802-f773deb2-32c5-4fed-bd79-d7d09752cc41.mp4

**Comment by Docile-Alligator** [comment]
Cannot reproduce this.
