### ISSUE TITLE
A counter for the amount of legacy settings detected

### ISSUE THREAD

**Issue by MysteriousOrb2000** [Docile-Alligator/Infinity-For-Reddit#819]
In Settings > Advanced > Delete All Legacy Settings, I was wondering if you add a count underneath that setting for the amount of legacy settings detected in the database. This would help notify the user that there were settings that were marked by the user within the database that no longer exists in the newer version of the app.

**Comment by Wladefant** [comment]
Do the legacy settings apply to the legacy mode? (Old reddit)
