### ISSUE TITLE
Pressing "See removed comment" will "edit" wrong message 

### ISSUE THREAD

**Issue by us3rname101** [Docile-Alligator/Infinity-For-Reddit#822]
If you press see removed comment and open a another comment's replies, it will edit reply instead of the deleted comment. See video of what I'm describing.
https://user-images.githubusercontent.com/95178906/176198626-c38f04fd-e63d-4927-a6eb-03e2ef882dd3.mp4

**Comment by Wladefant** [comment]
Please label this issue as a bug.
Can you reproduce it everywhere?
Can you explain a bit more what you mean?

**Comment by us3rname101** [comment]
Yes it is reproducible. If you want me to explain more, just watch the video.

**Comment by us3rname101** [comment]
@Wladefant  No. We have a deleted comment. (Comment 1) I press "see removed comment". Before Infinity fetches the deleted comment I open comment 2 replies. Infinity proceeds to alter comment 2 reply content instead of comment 1.

**Comment by Blahaj-Samoyed** [comment]
Hey @Docile-Alligator I am thinking about making a pull request for this. But based on your current implementation, I am wondering if I can make it ignore the fetched removed comments after expanding another comment?

**Comment by Docile-Alligator** [comment]
Alright. You can make a pull request and I will see. @Blahaj-Samoyed

**Comment by RSBat** [comment]
@Wladefant fixed in #1192
