### ISSUE TITLE
Image/Link posts getting marked as spam

### ISSUE THREAD

**Issue by jmbreuer** [Docile-Alligator/Infinity-For-Reddit#824]
Eg:

https://www.reddit.com/r/theyknew/comments/vnldu2/they_knew_about_energy_and_resonance/

Which site does Infinity use to upload/host images?

Is there rate/volume limiting on its API key or such?

I think it's unlikely that my account has tripped any limits, I post one or two things every couple of days max.

**Comment by Wladefant** [comment]
As mentioned in [this](https://github.com/Docile-Alligator/Docile-Alligator.github.io) repository infinity uses imgur public api as reddit also does. 

I can not see any problems with your post shared above and therefore do not understand what you mean. Can you explain yourself a bit more?

If you want to proceed Please label this issue as a bug
