### ISSUE TITLE
Home shows "No posts found", same with Subscriptions> subreddits and users

### ISSUE THREAD

**Issue by 4chieve** [Docile-Alligator/Infinity-For-Reddit#827]
It has been happening for a few days. 
Popular and All load normally.
If I change the filter for a different type such as Best or New, sometimes it loads but it's not consistent. When it does load eventually I reach a point where there's no more post to be viewed, I would roughly guess it only loads 20 posts, then I need to try to reload and change the filter.
I've deleted the cache and it still persists.

OnePlus 7 Pro
Oxygen OS 11.0.8.1GM21BA

**Comment by Wladefant** [comment]
Please label this issue as a bug

**Comment by Seltyk** [comment]
I am now experiencing this bug after unsubscribing from a couple dozen subreddits on desktop. My other accounts are unaffected, r/popular and r/all are also unaffected

**Comment by Wladefant** [comment]
Please add the bug with the new bug template
