### ISSUE TITLE
Make it easier to access backup password or disable it entirely 

### ISSUE THREAD

**Issue by AlertSubject** [Docile-Alligator/Infinity-For-Reddit#829]
When backing up my settings a toast is displayed that tells me the backup password is "xxxx...."

The message is too long to be displayed at once and there's no other way to see, change, or modify the password

Please give us another way of viewing the password, or just disable it entirely since the user is likely able to store it in a safe place themselves
And some settings aren't that sensitive

**Comment by Docile-Alligator** [comment]
The password is 123321

**Comment by AlertSubject** [comment]
> The password is 123321

Thank you

What do you think about adding a little paragraph of text in the backup section of the app with the password in there?

**Comment by Wladefant** [comment]
> > The password is 123321
> 
> Thank you
> 
> What do you think about adding a little paragraph of text in the backup section of the app with the password in there? 

I support that, or just the text: password: 123321 in small letters next to the backup settings button
