### ISSUE TITLE
about socks proxy

### ISSUE THREAD

**Issue by History-exe** [Docile-Alligator/Infinity-For-Reddit#83]
- Socks or http proxy wanted.

- And would you like to add some translation for this app? I can help to translate the zh-CN.

**Comment by Docile-Alligator** [comment]
Could you use a system-wide proxy or VPN? Yes. Thank you. I may start translating this app after I have finished implementing video autoplay, etc.

**Comment by History-exe** [comment]
@Docile-Alligator Thanks reply. Now I use the Android default HTTP proxy, sometimes it's not works very well. Any way, it basically worked.

**Comment by Docile-Alligator** [comment]
Nice
