### ISSUE TITLE
Some links open in webview

### ISSUE THREAD

**Issue by yephny** [Docile-Alligator/Infinity-For-Reddit#830]
Infinity opens some links in webview, for some reason.

Compare the links below, link 1 works as expected unlike link 2.

- [1](https://www.reddit.com/r/bodyweightfitness/wiki/exercises/handstand)

- [2](https://www.reddit.com/r/bodyweightfitness/wiki/exercises/l-sit)

**Comment by Wladefant** [comment]
Can confirm it.
Please label it as a bug.
Does it happen when you try to open the topic link through the app?

**Comment by yephny** [comment]
@Wladefant Can you elaborate? When I open these links, no matter if it's within the app or not, I am experiencing different behaviors, etc. one link opening in webview.

**Comment by yephny** [comment]
@Wladefant I've experienced it in multiple subreddits as far as I remember.
