### ISSUE TITLE
Volume button scroll does not work in multireddit view

### ISSUE THREAD

**Issue by leifan89** [Docile-Alligator/Infinity-For-Reddit#831]
### Description
After enabling "Use Volume Keys to Navigate Posts", volume up/down buttons for scrolling between posts work in Home view and when looking at a specific subreddit, but does not work in multireddit view.

### Steps to reproduce
* Left sidebar -> Settings -> Gestures and Buttons, enable both "Use Volume Keys to Navigate Comments in Posts" and "Use Volume Keys to Navigate Posts".
* Go back to Home, confirm that volume keys work for scrolling between posts.
* Go to a subreddit, confirm that volume keys work for scrolling between posts.
* Left sidebar -> Multireddit -> Pick a multireddit, volume keys DO NOT work for scrolling between posts (when pressed, volume control comes up).

### Version
5.2.1

### Device
Hisense A9 eink phone running customized Android 11

**Comment by Wladefant** [comment]
Would be nice if you could label it as a bug

**Comment by Wladefant** [comment]
@leifan89 @patrickdemers6 referenced an pull request to fix this issue. If you like this solution please close this issue

**Comment by patrickdemers6** [comment]
Probably would be good to keep the issue open until the PR is merged. At that time, this issue will auto close. @Wladefant

**Comment by Wladefant** [comment]
> Probably would be good to keep the issue open until the PR is merged. At that time, this issue will auto close. @Wladefant 

You are right sorry, my mistake
