### ISSUE TITLE
Filtering not working on NSFW accounts

### ISSUE THREAD

**Issue by NTB45** [Docile-Alligator/Infinity-For-Reddit#847]
I used filtering to filter out videos and photos from nsfw content 
but after a few updates it stopped working.

Example Opening r/porn and using filters to show only videos and nsfw content. Even tho r/porn is mostly videos it fails to load anything

**Comment by silentnoodlemaster** [comment]
`mNsfwAndSpoilerSharedPreferences.getBoolean((mAccountName == null || mAccountName.equals("-") ? "" : mAccountName) + SharedPreferencesUtils.NSFW_BASE, false)` in https://github.com/Docile-Alligator/Infinity-For-Reddit/blob/767bfb5af6480e4a2fdce72d49f0bc0e0484b59b/app/src/main/java/ml/docilealligator/infinityforreddit/activities/FilteredPostsActivity.java#L160 always returns false,

Definitely a bug

**Comment by Docile-Alligator** [comment]
Fixed. For now, you can enable NSFW in anonymous mode first.
