### ISSUE TITLE
[Feature Request] Add option to filter reddit posts

### ISSUE THREAD

**Issue by datream** [Docile-Alligator/Infinity-For-Reddit#85]
I love this client. I'd be cool to be able to filter my feed. As in filtering out certain subreddits or users I may not wish to view.

**Comment by zwu513** [comment]
You mean in your own feed or in All and Popular?

**Comment by datream** [comment]
Global filters, so in my own feed, all and popular

**Comment by zwu513** [comment]
I'm confused why you would want to filter certain subreddits in your own feed.

**Comment by datream** [comment]
I meant filtering undesired subreddits off all and popular, and undesired users globally.

**Comment by Docile-Alligator** [comment]
You can join the beta program and install the latest beta which has subreddit filters for all and popular.
