### ISSUE TITLE
Posts not loading with Card Layout

### ISSUE THREAD

**Issue by superrm11** [Docile-Alligator/Infinity-For-Reddit#852]
### Checklist

- [X] I have used the search function for [open](https://github.com/AntennaPod/AntennaPod/issues) **and** [closed](https://github.com/AntennaPod/AntennaPod/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

12

### Device model

Google Pixel 5

### First occurred

Since I've started using Infinity, about a year ago

### Steps to reproduce

1. Change layout type to Card in Settings>Interface>Post
2. Tap on a post on the homepage
3. Continue swiping right until posts stop loading

### Expected behaviour

Posts should continuously load as you swipe through them, and not require you to exit back to the homepage to load more posts

### Current behaviour

Currently, once you reach the end of your loaded posts, you're unable to continue swiping right. You are forced to exit back to the homepage and scroll down to load more posts before you are able to tap back in and continue swiping right

**Comment by Wladefant** [comment]
Yes, confirmed, but of course that happens only if you have settings>Gestures & Buttons>Swipe Between Posts turned on

**Comment by Docile-Alligator** [comment]
Fixed in v5.4.0.
