### ISSUE TITLE
Images not loading after a while of scrolling 

### ISSUE THREAD

**Issue by Matszwe02** [Docile-Alligator/Infinity-For-Reddit#862]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

12

### Device model

Samsung S22

### First occurred

Always 

### Steps to reproduce

Scroll in popular for a while (in my case an hour or so)
Images will start to load lazily
A bit further and images won't load at all
Restarting app resets it

### Expected behaviour

Imaggles loading correctly 

### Current behaviour

Images not loading correctly 

### Logs

-

**Comment by Wladefant** [comment]
Thank you for the bug report! It would also be very ni e if you could upload some images.

**Comment by Wladefant** [comment]
@Matszwe02 Just tried it out! And it seems that only some pictures does not load after a while of scrolling, but when you tap on them they are loading fine. Are you getting the same problem?

**Comment by Matszwe02** [comment]
> @Matszwe02 Just tried it out! And it seems that only some pictures does not load after a while of scrolling, but when you tap on them they are loading fine. Are you getting the same problem?

Right. For me ~80% aren't loading, but it's right as you wrote.

**Comment by Docile-Alligator** [comment]
@fusionneur @Matszwe02 Did you scroll very fast?

**Comment by Matszwe02** [comment]
> @fusionneur @Matszwe02 Did you scroll very fast?

No, but was skipping some posts that I'm not interested in, so I'll call it a medium speed (max 1 post per sec)

**Comment by kappa7194** [comment]
> @Matszwe02 Just tried it out! And it seems that only some pictures does not load after a while of scrolling, but when you tap on them they are loading fine. Are you getting the same problem?

Could this be linked to the issue I'm having where after side-swiping for a while the posts "stop"?

I start from the home feed, open a post, then start swiping right to go to the next post, after a while the swipe stops working as if there are no posts left. When I go back to feed and swipe down fast I can see that the feed suddenly "ends" at the same post where the right-swipe broke, and after a second (or more) more posts appear and I can resume swiping.

**Comment by Docile-Alligator** [comment]
Fixed.
