### ISSUE TITLE
Publish In Main F-Droid Repo

### ISSUE THREAD

**Issue by trymeouteh** [Docile-Alligator/Infinity-For-Reddit#87]
I am glad this app is available on the IzzyOnDroid F-Droid Repository, but it will be great if it was available on the main F-Droid repo. This way it will get more visibility.

**Comment by Docile-Alligator** [comment]
Thank you. I may not add it to the main repo because F-Droid will build it themselves and the signed key will be different than mine. This means that the two apks will not be interchangeable.

**Comment by Wilker-a** [comment]
this is a similar issue to NewPipe, where both the f-droid and the Github/releases versions have different signatures, but i don't see much of a problem with that unless backups is the issue.

**Comment by Docile-Alligator** [comment]
Another reason (disadvantage) is that I need to publish my API key to my GitHub repo so that F-Droid can build it and this means that my API key will longer stay private.

**Comment by Wilker-a** [comment]
sounds like a problem if API keys permissions aren't manually granted in Github, i don't remember how this function works...

**Comment by foresto** [comment]
Another perspective on this issue:

For many security-conscious users, the main F-Droid repo is more than just a convenience. As Android's single most widely used, well-established, trusted independent software archive, it provides an assurance of [integrity](https://en.wikipedia.org/wiki/Information_security#Integrity) that a developer's repo cannot. For example, if the code or signing keys were ever compromised, it would be far more likely to be discovered and fixed quickly on the main F-Droid repo than on any private repo.

This layer of security is an important one, and the principle behind it is part of why Google and Apple discourage side-loading. It is why some of us will not install apps from a private repo. It helps keep us all safe.

> F-Droid will build it themselves and the signed key will be different than mine. This means that the two apks will not be interchangeable.

Is interchangeability important to someone? In my experience, once someone installs an app, they expect to receive updates from the same source. If you're really concerned, I suppose you could just use a different application ID for the F-Droid build to avoid any conflict with your personal build.

> Another reason (disadvantage) is that I need to publish my API key to my GitHub repo so that F-Droid can build it and this means that my API key will longer stay private.

According to Reddit's Documentation [here](https://github.com/reddit-archive/reddit/wiki/OAuth2) and [here](https://github.com/reddit-archive/reddit/wiki/oauth2-app-types#installed-app), no, you would not. Infinity is what Reddit calls an Installed App, and the docs explain how to do this without sending an API key. They even have [specific instructions](https://github.com/reddit-archive/reddit/wiki/OAuth2#application-only-oauth) on how to make requests on behalf of a user who is not logged in.

By the way, if you have been putting your API key in the APK, it is already not safe. Extracting files from an APK, decompiling binaries, and finding private keys in the data is trivially easy for people who know just a little about reverse engineering.

+1 for publishing on the main F-Droid repo. It would allow more people to discover and use it, including me.

**Comment by grravity** [comment]
I would highly be for this.

I am confused though, I see on F-Droid it says that the app uses Google Ads and GMS, I do not remember this every being there. Are these recently added things? If so, why was this done? 
It would be very nice to have an F-Droid build that didn't use these non-free dependencies.. that's kinda why people use F-Droid. Otherwise I guess I'm going to have to consider moving away from the app, which sucks because I love it, but it's stuff like this that are dealbreakers.

**Comment by Shadowspear123** [comment]
Excellent excellent comment by @foresto I agree, adding to the main repo will not only grant the app a wider reach and audience, it will also give users a little more peace of mind. I'm also concerned about the anti features indicated on the app's f-droid page which includes Google Ads and GMS. Those things are indeed dealbreakers

**Comment by Docile-Alligator** [comment]
Thank you @OHermesJunior for helping me publishing the app to the main F-Droid repo. He has already submitted a request.

**Comment by realmain** [comment]
Link to F-Droid Submission Tracker

https://gitlab.com/fdroid/rfp/-/issues/1394

**Comment by austinhuang0131** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7390

RemindMe! 1 week "Ping maintainers"

**Comment by austinhuang0131** [comment]
https://f-droid.org/en/packages/ml.docilealligator.infinityforreddit/

we did it reddit

**Comment by Docile-Alligator** [comment]
Oh nice! Thank you very much!
