### ISSUE TITLE
Option to show child comments count without opening comment toolbar.

### ISSUE THREAD

**Issue by lewdpatriot** [Docile-Alligator/Infinity-For-Reddit#870]
Btw I have enabled this option but it doesn't work. Only shows upvote count when toolbar is hidden. 
![Screenshot_2022-08-01-12-22-20-86_2656fe66d4cc08342e93fbdd9fd1d373](https://user-images.githubusercontent.com/63286528/182091071-cb9f4af5-a7c4-48a3-ac61-b23597f62081.jpg)

_Originally posted by @lewdpatriot in https://github.com/Docile-Alligator/Infinity-For-Reddit/discussions/869_

**Comment by lewdpatriot** [comment]
I want to see if a comment has any child comments, without showing the comment bar because showing the bar under every comment makes the comment section messy.

The above mentioned toggle should've done that. 
![IMG_20220801_141552](https://user-images.githubusercontent.com/63286528/182110522-3439e8cd-ec6d-4447-883b-a84306d97083.jpg)
Like in this pic (boost for reddit) the bar is hidden but there is a counter indicating the comment has 4 child comments.
I hope its clear this time.

**Comment by Wladefant** [comment]
> I want to see if a comment has any child comments, without showing the comment bar because showing the bar under every comment makes the comment section messy.
> 
> The above mentioned toggle should've done that. 
> ![IMG_20220801_141552](https://user-images.githubusercontent.com/63286528/182110522-3439e8cd-ec6d-4447-883b-a84306d97083.jpg)
> Like in this pic (boost for reddit) the bar is hidden but there is a counter indicating the comment has 4 child comments.
> I hope its clear this time. 

You shouldn't write it here: the issues tab is only for bug reports, you should add it to the discussion. The part I asked about was the last part with the last picture. I think you tried to say that this toggle is not working right? (Bug)

**Comment by lewdpatriot** [comment]
I'm still not sure if it's a bug or not because toggling the option on or off doesn't seem to do anything.
What does the option do anyway?

**Comment by jake770321** [comment]
Any update on this? I have the "Always show the number of child comments" toggle enabled but it only shows if the comment toolbar is open.

**Comment by Wladefant** [comment]
@jake770321 #869

**Comment by lewdpatriot** [comment]
> Any update on this? I have the "Always show the number of child comments" toggle enabled but it only shows if the comment toolbar is open.

No. For whatever reason the developer didn't understand what I wanted. I tried my best to explain. If you can, maybe open a new feature request cause I still want that feature.
