### ISSUE TITLE
Image Description Hidden by Navigation Bar

### ISSUE THREAD

**Issue by patrickdemers6** [Docile-Alligator/Infinity-For-Reddit#882]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

12

### Device model

Galaxy S20 Ultra 5G (SM-G988U1)

### First occurred

Months ago

### Steps to reproduce

1. Navigate to a post with more than 5 images that have a description. [Example post](https://www.reddit.com/r/pcmasterrace/comments/wddcpe/giveaway_giving_away_10_deskmats_from_the_ai/).
2. Swipe through the pictures.
3. Notice images 1-4 display the description properly. (note: in the example post, image one does not have a description)
4. Notice image 5 and on has the description displayed too low. It is hidden by the navigation bar. If you slightly swipe up, the description will be displayed.

### Expected behaviour

Images 5 to the end should display their description, just like the first four.

### Current behaviour

Images 1-4 have their description properly displayed whereas images 5+ do not.

### Logs

[Video link](we.tl/t-a1bFODTaL5). Download from We Transfer.

**Comment by Docile-Alligator** [comment]
Fixed.
