### ISSUE TITLE
Image captions missing

### ISSUE THREAD

**Issue by Shazzkid** [Docile-Alligator/Infinity-For-Reddit#884]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

F-Droid

### Android version

12

### Device model

Galaxy Note 10+

### First occurred

~2 weeks

### Steps to reproduce

See: https://www.reddit.com/r/spiders/comments/wfd8qk/anyone_know_what_kind_of_spider_this_is_brown/

Image has captions, but does not show in Infinity. This is regardless or clearing app cache, restarting app etc

However, see: https://www.reddit.com/r/flashlight/comments/wervag/modded_emisar_d4v1_with_9amp_driver_lighted/?utm_medium=android_app&utm_source=share

Image has captions and DOES show up in infinity.

The issue is consistent between posts, so the posts that it  works fine on now, it will continue to work fine. And the posts it doesn't work on, it never works. I don't know why specific posts are having issues and others aren't. 

### **First post (has captions and displays captions) works as intended. Shown on reddit app and Infinity**

![Screenshot_20220810-184454_Reddit.jpg](https://user-images.githubusercontent.com/110567772/183981238-1fdb07f9-ed43-4cd0-8f64-7d3ac9499ca3.jpg)
_As seen, reddit app shows post images has captions_

![Screenshot_20220810-184505_Infinity.jpg](https://user-images.githubusercontent.com/110567772/183981260-88f35bc6-4e63-4fac-81b0-f46b5b6222ef.jpg) 
_As seen, infinity app shows post images has captions as intended_

### **Second post**(has captions but does not display captions) does not work as intended. Shown on reddit app (where captions always show as intended) and Infinity. 

![Screenshot_20220810-184245_Reddit.jpg](https://user-images.githubusercontent.com/110567772/183981524-a8ec1eef-8d64-4c1f-9ff3-f1bbf96e3654.jpg)
_As seen, reddit app shows post images has captions_

![Screenshot_20220810-184432_Infinity.jpg](https://user-images.githubusercontent.com/110567772/183981538-8d844704-be96-4127-9b53-232a59d7730c.jpg)
_As seen, infinity app does not correctly display caption_

**Comment by Wladefant** [comment]
Please provide a Screenshot of the same post with a description

**Comment by Shazzkid** [comment]
> Please provide a Screenshot of the same post with a description

Updated with screenshots and description 👍

**Comment by Docile-Alligator** [comment]
Thank you for reporting this. It will be fixed soon.

**Comment by Docile-Alligator** [comment]
Fixed.
