### ISSUE TITLE
Feature request: An option to hide this top bar as soon as we scroll down. 

### ISSUE THREAD

**Issue by Invisigon1** [Docile-Alligator/Infinity-For-Reddit#885]
This top bar will not hide until comments are displayed on screen.  I would like an option to hide the top bar as soon as we scroll.  Scrolling up shows the top bar, of course. 
![https://i.postimg.cc/DzBxYF07/Screenshot-20220803-160749-Infinity.png](url)

**Comment by Invisigon1** [comment]
Not sure why it is not displaying...Here is the link to the image. 

https://i.postimg.cc/DzBxYF07/Screenshot-20220803-160749-Infinity.png

**Comment by Wladefant** [comment]
Please add feature requests to github discussions

**Comment by Invisigon1** [comment]
@Wladefant Umm, how may I do this?

**Comment by Wladefant** [comment]
> @Wladefant Umm, how may I do this? 

@Invisigon1 through the github discussions tab>new discussion in ideas

**Comment by Invisigon1** [comment]
> > @Wladefant Umm, how may I do this?
> 
> @Invisigon1 through the github discussions tab>new discussion in ideas

Thanks!  I have submitted my request in the discussions.

**Comment by Wladefant** [comment]
@Invisigon1 thank you!
