### ISSUE TITLE
[Feature request] Mark posts as read

### ISSUE THREAD

**Issue by Armaldio** [Docile-Alligator/Infinity-For-Reddit#89]
Could be cool to have an option to mark posts are ready on scroll 
And have the ability to hide posts that you already have readed

**Comment by Docile-Alligator** [comment]
I will start implementing this feature after I have done video autoplay and swipe between posts.

**Comment by lazerleif** [comment]
I need this so i can switch from slide 😄

**Comment by Docile-Alligator** [comment]
This will be available in v4.2.0.
