### ISSUE TITLE
Feature Request: "Hide Read" button

### ISSUE THREAD

**Issue by SkyLord52** [Docile-Alligator/Infinity-For-Reddit#9]
A lot of the time whenever I open the app I see posts that I've already seen. You should add a "Hide Read" button to the 3 dots menu in the top right corner, or add an option to hide read posts automatically.

**Comment by Docile-Alligator** [comment]
Hi there, I will implement it in the future. But keep in mind, it will take some time.

**Comment by PinkDev1** [comment]
I would love this on a future release
@Docile-Alligator , any progress on this?

**Comment by Docile-Alligator** [comment]
I haven't because this is the most difficult feature to be implemented. I need to finish other features first.

**Comment by PinkDev1** [comment]
I've been thinking: The easiest way to implement this might be to hide _interacted-with_ posts; hide down/upvoted posts.

**Comment by Docile-Alligator** [comment]
This will be available in v4.2.0.
