### ISSUE TITLE
Get inbox notification on all login accounts

### ISSUE THREAD

**Issue by trymeouteh** [Docile-Alligator/Infinity-For-Reddit#90]
Myabe it is just me but I find that I only get notifications from the current selected account and not my second account when the app is closed. Is it possible to be able to get notifications for all of your logged in reddit accounts?

**Comment by Docile-Alligator** [comment]
Actually it does fetch new messages for all the accounts.

**Comment by trymeouteh** [comment]
Ok, now I just realise this too. My bad.
