### ISSUE TITLE
If a deleted comment from an OP is recovered, the OP badge does not show

### ISSUE THREAD

**Issue by KSPAtlas** [Docile-Alligator/Infinity-For-Reddit#904]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

F-Droid

### Android version

12, GrapheneOS

### Device model

Google Pixel 3

### First occurred

Today, although it may have happened before

### Steps to reproduce

1. Find a post where OP has deleted comments
2. Recover it
3. Notice that the op badge is missing

### Expected behaviour

Show the OP badge

Also, why does this section say antennapod?

### Current behaviour

Show them as a regular user

![Screenshot_20220812-110630_1](https://user-images.githubusercontent.com/72895702/184333087-651387be-d5a5-4ac6-97ca-f298318b7b69.png)

**Comment by Wladefant** [comment]
Hey, @KSPAtlas thank you for your bug report. Fixed the typo. Can you share a post link for faster confirmation?

**Comment by KSPAtlas** [comment]
https://www.reddit.com/r/SubwayCreatures/comments/whso9o/this_smiley_boi_ttc/
