### ISSUE TITLE
Question: Does Infinity store history

### ISSUE THREAD

**Issue by trymeouteh** [Docile-Alligator/Infinity-For-Reddit#91]
Does Infinity store search history and what posts, comments, subreddits you been to within the app, especially when your using the anonymous (no account) mode? I want to know if infinity when using the anonymous mode is just as good as inconigo/private mode in a browser.

And if infinity store any history, can you delete it easily?

**Comment by Docile-Alligator** [comment]
Hi. Infinity does not store any of your post history, search history, subreddits and comments history. So it is as good as incognito mode in a browser. Furthermore, I don't have a server so don't worry about sending your private data to me.

**Comment by OHermesJunior** [comment]
Answered, could be closed.
