### ISSUE TITLE
Reading comments looks awful and routinely collapsing comment threads is too

### ISSUE THREAD

**Issue by desbest** [Docile-Alligator/Infinity-For-Reddit#934]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

4.6.1

### Where did you get the app from

Other

### Android version

Windows 10 21H2

### Device model

Windows 10 21H2

### First occurred

Yesterday

### Steps to reproduce

Open a Reddit thread with lots of comments like on r/askreddit

### Expected behaviour

1) It should be made much easier to collapse comment threads, especially on threads with over 250 comments 

2) The screen for viewing replies to comments should not appear in a modal/lightbox but should instead show on the same page.

### Current behaviour

See the images below for details 

![FC401B3A-D566-4307-BB18-07CA5ADC4F1B](https://user-images.githubusercontent.com/1139316/184472260-3e9d279f-326f-49d0-b491-469fdfc92950.png)
![74A701F3-D509-43B6-BE09-6CB39F393E68](https://user-images.githubusercontent.com/1139316/184472261-3704f220-095f-4506-b530-fd58ee6b2143.png)

### Logs

I got the app from Microsoft Store. And yes it is called Infinity For Reddit.

**Comment by Docile-Alligator** [comment]
This repo is for Infinity for Reddit on Android, not Windows.
