### ISSUE TITLE
Post show up multiple times (I do not talk about reposts)

### ISSUE THREAD

**Issue by Boerny41** [Docile-Alligator/Infinity-For-Reddit#94]
This is very strange and I never had it on any other app. It happens since weeks and it is really annoying...
What happens is, that the exact same post shows up multiple times in the "home" section. I'm not talking about repost I mean the same image uploaded in the same sub at the same time by the same person.
There is no strict order but I noticed some patterns. Is either a single post like: A, B, A, C, D, E, F....
or multiple post like: A, B, C, D, E, A, B, C, D, F, G, H  (letter = post)

Here is a picture of it that followes the second example (post 1-4, 5, 1-4, 6, 7, 8....)

![WhatsApp Image 2020-05-09 at 12 33 36](https://user-images.githubusercontent.com/49845653/81471476-a9321900-91f1-11ea-8408-387516528676.jpeg)

**Comment by DatAres37** [comment]
Same problem for me.

**Comment by watson387** [comment]
I also have this problem.

**Comment by Docile-Alligator** [comment]
This will be fixed in the next update.
