### ISSUE TITLE
Comment hierarchy is sometimes incorrect

### ISSUE THREAD

**Issue by E0697** [Docile-Alligator/Infinity-For-Reddit#953]
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

12

### Steps to reproduce

Sometimes when there too many comments and child comments, the hierarchy is gets messed up. Some child comments would have correct indents, but would be postioned below an inocrrect parent comment.

### Expected behaviour

Child comments should be displayed below their respective parent comment.

### Current behaviour

![IMG_20220814_155246](https://user-images.githubusercontent.com/66939100/184538750-a741cdd7-7837-45a3-973a-f3ece543150b.jpg)
![IMG_20220814_155513](https://user-images.githubusercontent.com/66939100/184538766-9ff52bfe-38da-4fd4-b284-3325c368101f.jpg)
![IMG_20220814_155805](https://user-images.githubusercontent.com/66939100/184538763-a04dd55c-6976-4436-bcc2-008b00406722.jpg)

**Comment by kappa7194** [comment]
I had this happen especially after re-expanding a collapsed thread; after the expansion children gets messed-up, being shown under the wrong parent or multiple times in the thread. Forcing a post reload (closing and reopening it or swiping down) fixes it.

**Comment by RSBat** [comment]
Found easy to reproduce case:
- Top level comment
- - Child 1
- - - Child 1.1
- - - - Child 1.1.1
- - - - Child 1.1.2
- - - Child 1.2
- - Child 2
- - - Child 2.1

Collapse and expand top level comment. `Child 2.1` will now be between `Child 1.1.2` and `Child 1.2`
